---
sidebar: sidebar 
permalink: cascade-replication.html 
keywords: replicate, cascade, cascade replication, cascade deployment, data protection, volume replication, replicate data protection volume 
summary: Replizieren Sie Datensicherungs-Volumes oder Kaskadenreplikation von Volume-Daten, um die Datensicherung auf tertiäre Systeme zu erweitern oder Ihre Daten zu migrieren. 
---
= Replizieren Sie Datensicherungs-Volumes in der BlueXP  Workload-Fabrik
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Replizieren Sie Datensicherungs-Volumes oder Kaskadenreplikation von Volume-Daten, um die Datensicherung auf tertiäre Systeme zu erweitern oder Ihre Daten zu migrieren.

.Über diese Aufgabe
Die BlueXP  Workload-Farm unterstützt die Replizierung von Datensicherungs-Volumes. In ONTAP wird die Replizierung von Datensicherungs-Volumes als eine _mirror-mirror-Kaskadenimplementierung_ betrachtet. Eine Kaskadierung mit Spiegelspiegelung besteht aus einer Kette von Beziehungen, bei denen ein Quell-Volume auf ein sekundäres Volume gespiegelt und das sekundäre Volume auf einem tertiären Volume gespiegelt wird. Falls das sekundäre Volume nicht mehr verfügbar ist, können Sie die Beziehung zwischen dem primären und dem tertiären Volume synchronisieren, ohne einen neuen Basistransfer durchführen zu müssen.

Diese Funktion wird für FSX für ONTAP-Dateisysteme mit ONTAP Version 9.6 und höher unterstützt. Siehe link:https://docs.netapp.com/us-en/ontap/data-protection/compatible-ontap-versions-snapmirror-concept.html#snapmirror-disaster-recovery-relationships["ONTAP-Dokumentation für kompatible ONTAP-Versionen"^].


NOTE: Wenn das Quell-Volume der Beziehung ein Data-Protection-Volume ist und ein Ziel einer anderen Beziehung ist, wird das Umkehren der Replikationsbeziehung nicht unterstützt.

.Bevor Sie beginnen
Beachten Sie, dass die erneute Synchronisierung von Volumes, die Teil einer Kaskadenkonfiguration sind, länger dauern kann.

[role="tabbed-block"]
====
.Replizieren eines einzelnen Volumes
--
Sie können ein Datensicherungs-Volume (DP) replizieren.


NOTE: Ein Replikat eines Datensicherungs-Volumes wird unterstützt. Sie können kein zweites Replikat eines DP-Volumes erstellen.

.Schritte
. Melden Sie sich mit einem der link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["Konsolenerfahrungen"^]an.
. Wählen Sie unter Speicher die Option zum Speicherbestand wechseln aus.
. Wählen Sie auf der Registerkarte FSX for ONTAP das drei-Punkt-Menü des zu aktualisierenden Dateisystems aus, und wählen Sie Verwalten aus.
. Wählen Sie die Registerkarte Volumes aus.
. Wählen Sie das drei-Punkt-Menü des Data Protection Volume (DP/Replicated Volume) aus und wählen Sie *Replicate Volume Data* aus.
. Geben Sie auf der Seite Replikation erstellen unter Replikationsziel Folgendes an:
+
.. * FSX für ONTAP Dateisystem*: Wählen Sie Anmeldeinformationen, Region und FSX für ONTAP Dateisystem Namen für das Ziel FSX für ONTAP Dateisystem.
.. *Name der Speicher-VM*: Wählen Sie die Speicher-VM aus dem Dropdown-Menü aus.
.. *Volumenname*: Der Name des Zielvolume wird automatisch im folgenden Format generiert `{OriginalVolumeName}_copy`. Sie können den automatisch generierten Volume-Namen verwenden oder einen anderen Volume-Namen eingeben.
.. *Anwendungsfall*: Wählen Sie einen der folgenden Anwendungsfälle für die Replikation aus.
+
*** Migration: Überträgt Ihre Daten an das Ziel-FSX für ONTAP-Filesystem
*** Hot Disaster Recovery: Hohe Verfügbarkeit und schnelles Disaster Recovery für kritische Workloads
*** Disaster Recovery in kalten oder archivierten Daten:
+
**** Cold Disaster Recovery: Verwendet längere Recovery-Zeitvorgaben (RTO) und Recovery-Zeitpunkte (RPO) zur Senkung der Kosten
**** Archiv: Replizierung von Daten für langfristige Speicherung und Compliance


*** Sonstiges


.. *Tiering Policy*: Wählen Sie die Tiering Policy für die auf dem Ziel-Volume gespeicherten Daten. Je nach ausgewähltem Anwendungsfall wird die Tiering-Richtlinie standardmäßig auf die empfohlene Tiering-Richtlinie für den Anwendungsfall zurückgesetzt.
+
_Balanced (Auto)_ ist die Standard-Tiering-Richtlinie beim Erstellen eines Volumes unter Verwendung der Benutzeroberfläche von Workload Factory FSX for ONTAP. Weitere Informationen zu Volume-Tiering-Richtlinien finden Sie link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/volume-storage-capacity.html#data-tiering-policy["Speicherkapazität für Volumes"^] in der Dokumentation zu AWS FSX for NetApp ONTAP.

.. *Max. Übertragungsrate*: Wählen Sie *Limited* und geben Sie die maximale Übertragungsgrenze in MB/s. ein Alternativ wählen Sie *Unlimited*.
+
Ohne Einschränkung kann die Netzwerk- und Anwendungsleistung abnehmen. Alternativ empfehlen wir eine unbegrenzte Übertragungsrate für die Dateisysteme FSX for ONTAP für kritische Workloads, zum Beispiel solche, die primär für die Disaster Recovery genutzt werden.



. Geben Sie unter Replikationseinstellungen Folgendes an:
+
.. *Replikationsintervall*: Wählen Sie die Häufigkeit, mit der Snapshots vom Quell-Volume auf das Ziel-Volume übertragen werden.
.. *Langfristige Aufbewahrung*: Optional können Snapshots für die langfristige Aufbewahrung aktiviert werden.
+
Wenn Sie die langfristige Aufbewahrung aktivieren, wählen Sie eine vorhandene Richtlinie aus, oder erstellen Sie eine neue Richtlinie, um die zu replizierenden Snapshots und die Anzahl der beizubehaltenden Snapshots zu definieren.

+
*** Wählen Sie für *vorhandene Richtlinie auswählen* eine vorhandene Richtlinie aus dem Dropdown-Menü aus.
*** Geben Sie für *Create a New Policy* Folgendes an:
+
**** *Richtlinienname*: Geben Sie einen Richtliniennamen ein.
**** *Snapshot-Richtlinien*: Wählen Sie in der Tabelle die Snapshot-Policy-Häufigkeit und die Anzahl der zu haltenden Kopien aus. Sie können mehrere Snapshot-Richtlinien auswählen.






. Wählen Sie *Erstellen*.


--
.Replizieren aller Volumes in einem Dateisystem
--
Sie können alle DP-Volumes (Data Protection) in einem Filesystem replizieren.


NOTE: Ein Replikat eines Datensicherungs-Volumes wird unterstützt. Sie können kein zweites Replikat eines DP-Volumes erstellen.

.Schritte
. Melden Sie sich mit einem der link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["Konsolenerfahrungen"^]an.
. Wählen Sie unter Speicher die Option *Gehe zu Lagerbestandsbestand* aus.
. Wählen Sie auf der Registerkarte FSX for ONTAP das drei-Punkt-Menü des Dateisystems mit den Volumes aus und wählen Sie dann *Verwalten*.
. Wählen Sie in der Dateisystemübersicht *Replikation erstellen* aus.
. Geben Sie auf der Seite Replikation erstellen unter Replikationsziel Folgendes an:
+
.. * FSX für ONTAP Dateisystem*: Wählen Sie Anmeldeinformationen, Region und FSX für ONTAP Dateisystem Namen für das Ziel FSX für ONTAP Dateisystem.
.. *Name der Speicher-VM*: Wählen Sie die Speicher-VM aus dem Dropdown-Menü aus.
.. *Volumenname*: Der Name des Zielvolume wird automatisch im folgenden Format generiert `{OriginalVolumeName}_copy`.
.. *Tiering Policy*: Wählen Sie die Tiering Policy für die auf dem Ziel-Volume gespeicherten Daten.
+
_Auto_ ist die Standard-Tiering-Richtlinie beim Erstellen eines Volumes unter Verwendung der Workload Factory FSX for ONTAP-Benutzeroberfläche. Weitere Informationen zu Volume-Tiering-Richtlinien finden Sie link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/volume-storage-capacity.html#data-tiering-policy["Speicherkapazität für Volumes"^]in der Dokumentation zu AWS FSX for NetApp ONTAP.

.. *Max. Übertragungsrate*: Wählen Sie *Limited* und geben Sie die maximale Übertragungsgrenze in MiB/s. ein Alternativ wählen Sie *Unlimited*.
+
Ohne Einschränkung kann die Netzwerk- und Anwendungsleistung abnehmen. Alternativ empfehlen wir eine unbegrenzte Übertragungsrate für die Dateisysteme FSX for ONTAP für kritische Workloads, zum Beispiel solche, die primär für die Disaster Recovery genutzt werden.



. Geben Sie unter Replikationseinstellungen Folgendes an:
+
.. *Replikationsintervall*: Wählen Sie die Häufigkeit, mit der Snapshots vom Quell-Volume auf das Ziel-Volume übertragen werden.
.. *Langfristige Aufbewahrung*: Optional können Snapshots für die langfristige Aufbewahrung aktiviert werden.
+
Wenn Sie die langfristige Aufbewahrung aktivieren, wählen Sie eine vorhandene Richtlinie aus, oder erstellen Sie eine neue Richtlinie, um die zu replizierenden Snapshots und die Anzahl der beizubehaltenden Snapshots zu definieren.

+
*** Wählen Sie für *vorhandene Richtlinie auswählen* eine vorhandene Richtlinie aus dem Dropdown-Menü aus.
*** Geben Sie für *Create a New Policy* Folgendes an:
+
**** *Richtlinienname*: Geben Sie einen Richtliniennamen ein.
**** *Snapshot-Richtlinien*: Wählen Sie in der Tabelle die Snapshot-Policy-Häufigkeit und die Anzahl der zu haltenden Kopien aus. Sie können mehrere Snapshot-Richtlinien auswählen.






. Wählen Sie *Erstellen*.


--
====
.Ergebnis
Das replizierte Volume oder die replizierten Volumes replizieren sich und erscheinen auf der Registerkarte *Replikationsbeziehungen* im Ziel-FSX für ONTAP-Dateisystem.
