---
sidebar: sidebar 
permalink: cascade-replication.html 
keywords: replicate, cascade, cascade replication, cascade deployment, data protection, volume replication, replicate data protection volume 
summary: Replizieren Sie Datensicherungs-Volumes oder Kaskadenreplikation von Volume-Daten, um die Datensicherung auf tertiäre Systeme zu erweitern oder Ihre Daten zu migrieren. 
---
= Replizieren Sie Datensicherungs-Volumes in der BlueXP  Workload-Fabrik
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Replizieren Sie Datensicherungs-Volumes oder Kaskadenreplikation von Volume-Daten, um die Datensicherung auf tertiäre Systeme zu erweitern oder Ihre Daten zu migrieren.

.Über diese Aufgabe
Die BlueXP  Workload-Farm unterstützt die Replizierung von Datensicherungs-Volumes, auch „Cascade Deployments“ genannt. Eine _Kaskadenbereitstellung_ besteht aus einer Beziehungskette, in der ein Quell-Volume auf ein sekundäres Volume gespiegelt wird (erster Hop) und das sekundäre Volume auf ein tertiäres Volume gespiegelt wird (zweiter Hop). Falls das sekundäre Volume nicht mehr verfügbar ist, können Sie die Beziehung zwischen dem primären und dem tertiären Volume synchronisieren, ohne einen neuen Basistransfer durchführen zu müssen.

Diese Funktion wird für FSX für ONTAP-Dateisysteme mit ONTAP Version 9.6 und höher unterstützt. Siehe link:https://docs.netapp.com/us-en/ontap/data-protection/compatible-ontap-versions-snapmirror-concept.html#snapmirror-disaster-recovery-relationships["ONTAP-Dokumentation für kompatible ONTAP-Versionen"^].

Erfahren Sie mehr über link:https://docs.netapp.com/us-en/ontap/data-protection/supported-deployment-config-concept.html#how-cascade-deployments-work["Funktionsweise von Kaskadenimplementierungen"^].

.Bevor Sie beginnen
Beachten Sie Folgendes, bevor Sie beginnen:

* Beachten Sie, dass die erneute Synchronisierung von Volumes, die Teil einer Kaskadenkonfiguration sind, länger dauern kann.
* Wenn das Quell-Volume der Beziehung ein Data-Protection-Volume ist und ein Ziel einer anderen Beziehung ist, wird das Umkehren der Replikationsbeziehung nicht unterstützt.
* Es wird ein Replikat eines Data-Protection-Volumes (oder ein zweiter Hop) unterstützt. Es gilt nicht als Best Practice, ein zweites Replikat eines Datensicherheitsvolumes (oder einen dritten Hop) zu erstellen.


.Schritte
. Melden Sie sich mit einem der link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["Konsolenerfahrungen"^]an.
. Wählen Sie unter Speicher die Option *Gehe zu Lagerbestandsbestand* aus.
. Wählen Sie auf der Registerkarte *FSX for ONTAP* das drei-Punkt-Menü des Dateisystems aus, das die zu replizierenden Volumes enthält, und wählen Sie dann *Verwalten*.
. Wählen Sie in der Dateisystemübersicht die Registerkarte *Volumes* aus.
. Wählen Sie in der Tabelle Volumes ein oder mehrere Data Protection Volumes (DP/Replicated Volumes) aus und wählen Sie dann *Replicate Data* aus.
. Geben Sie auf der Seite Daten replizieren unter Replikationsziel Folgendes an:
+
.. * FSX für ONTAP Dateisystem*: Wählen Sie Anmeldeinformationen, Region und FSX für ONTAP Dateisystem Namen für das Ziel FSX für ONTAP Dateisystem.
.. *Name der Speicher-VM*: Wählen Sie die Speicher-VM aus dem Dropdown-Menü aus.
.. *Volumenname*: Der Name des Zielvolume wird automatisch im folgenden Format generiert `{OriginalVolumeName}_copy`. Sie können den automatisch generierten Volume-Namen verwenden oder einen anderen Volume-Namen eingeben.
.. *Anwendungsfall*: Wählen Sie einen der folgenden Anwendungsfälle für die Replikation aus. Je nach ausgewähltem Anwendungsfall füllt die Workload Factory das Formular mit den empfohlenen Werten gemäß den Best Practices aus. Sie können die empfohlenen Werte akzeptieren oder Änderungen vornehmen, während Sie das Formular ausfüllen.
+
*** Migration: Überträgt Ihre Daten an das Ziel-FSX für ONTAP-Filesystem
*** Hot Disaster Recovery: Hohe Verfügbarkeit und schnelles Disaster Recovery für kritische Workloads
*** Disaster Recovery in kalten oder archivierten Daten:
+
**** Cold Disaster Recovery: Verwendet längere Recovery-Zeitvorgaben (RTO) und Recovery-Zeitpunkte (RPO) zur Senkung der Kosten
**** Archiv: Replizierung von Daten für langfristige Speicherung und Compliance


*** Sonstiges


.. *Tiering Policy*: Wählen Sie die Tiering Policy für die auf dem Ziel-Volume gespeicherten Daten. Die Tiering-Richtlinie wird standardmäßig auf die empfohlene Tiering-Richtlinie für den ausgewählten Anwendungsfall zurückgesetzt.
+
_Balanced (Auto)_ ist die Standard-Tiering-Richtlinie beim Erstellen eines Volumes mit der Workload Factory-Konsole. Weitere Informationen zu Volume-Tiering-Richtlinien finden Sie link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/volume-storage-capacity.html#data-tiering-policy["Speicherkapazität für Volumes"^] in der Dokumentation zu AWS FSX for NetApp ONTAP. Beachten Sie, dass Workload Factory für Tiering-Richtlinien auf Basis von Anwendungsfällen in der Workload Factory verwendet und Tiering-Richtliniennamen für FSX für ONTAP in Klammern enthält.

+
Wenn Sie den Anwendungsfall für die Migration ausgewählt haben, wählt die Workload Factory automatisch aus, die Tiering-Richtlinie des Quell-Volume auf das Ziel-Volume zu kopieren. Sie können das Kopieren der Tiering-Richtlinie deaktivieren und eine Tiering-Richtlinie auswählen, die auf das für die Replikation ausgewählte Volume zutrifft.

.. *Max. Übertragungsrate*: Wählen Sie *Limited* und geben Sie die maximale Übertragungsgrenze in MB/s. ein Alternativ wählen Sie *Unlimited*.
+
Ohne Einschränkung kann die Netzwerk- und Anwendungsleistung abnehmen. Alternativ empfehlen wir eine unbegrenzte Übertragungsrate für die Dateisysteme FSX for ONTAP für kritische Workloads, zum Beispiel solche, die primär für die Disaster Recovery genutzt werden.



. Geben Sie unter Replikationseinstellungen Folgendes an:
+
.. *Replikationsintervall*: Wählen Sie die Häufigkeit, mit der Snapshots vom Quell-Volume auf das Ziel-Volume übertragen werden.
.. *Langfristige Aufbewahrung*: Optional können Snapshots für die langfristige Aufbewahrung aktiviert werden. Dank der langfristigen Aufbewahrung können Business-Services auch bei einem vollständigen Standortausfall weiterlaufen und Applikationen mithilfe einer sekundären Kopie einen transparenten Failover unterstützen.
+
Wenn Sie die langfristige Aufbewahrung aktivieren, wählen Sie eine vorhandene Richtlinie aus, oder erstellen Sie eine neue Richtlinie, um die zu replizierenden Snapshots und die Anzahl der beizubehaltenden Snapshots zu definieren.

+

NOTE: Zur langfristigen Aufbewahrung sind passende Quell- und Zieletiketten erforderlich. Auf Wunsch kann Workload Factory fehlende Etiketten für Sie erstellen.

+
*** *Wählen Sie eine vorhandene Richtlinie*: Wählen Sie eine vorhandene Richtlinie aus dem Dropdown-Menü aus.
*** *Erstellen Sie eine neue Richtlinie*: Geben Sie Folgendes an:
+
**** *Richtlinienname*: Geben Sie einen Richtliniennamen ein.
**** Optional: Unveränderliche Snapshots aktivieren
+
***** Wählen Sie *Enable Immanable Snapshots* aus, um zu verhindern, dass in dieser Richtlinie ergriffene Snapshots während des Aufbewahrungszeitraums gelöscht werden.
***** Legen Sie die *Aufbewahrungsfrist* in Stunden, Tagen, Monaten oder Jahren fest.


**** *Snapshot-Richtlinien*: Wählen Sie in der Tabelle die Snapshot-Policy-Häufigkeit und die Anzahl der zu haltenden Kopien aus. Sie können mehrere Snapshot-Richtlinien auswählen.






. Wählen Sie *Erstellen*.


.Ergebnis
Das replizierte Volume oder die replizierten Volumes replizieren sich und erscheinen auf der Registerkarte *Replikationsbeziehungen* im Ziel-FSX für ONTAP-Dateisystem.
