---
sidebar: sidebar 
permalink: change-snapshot-policy.html 
keywords: snapshot policy, snapshot schedule, modify snapshot policy, edit snapshot policy, change snapshot policy 
summary: Die Snapshot-Richtlinie eines Volumes kann jederzeit aktualisiert werden. 
---
= Ändern der Snapshot-Richtlinie eines Volumes
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Aktualisieren Sie die Häufigkeit der für ein Volume erstellten Snapshots, oder deaktivieren Sie die automatischen Snapshots jederzeit.

.Bevor Sie beginnen
Zum Anzeigen vorhandener Snapshot-Richtlinien ist ein Link erforderlich. Um einen Link zuzuordnen, klicken Sie unter *Kontoname* auf *Associate Link*. Kehren Sie dann zu diesem Vorgang zurück.

.Schritte
. Melden Sie sich beim an link:https://console.workloads.netapp.com/["Workload Factory-Konsole"^]
. Wählen Sie unter Speicher die Option *Gehe zu Lagerbestandsbestand* aus.
. Wählen Sie auf der Registerkarte *FSX für ONTAP* das drei Punkte-Menü des FSX für ONTAP-Dateisystems aus, das das Volume mit der zu aktualisierenden Snapshot-Richtlinie enthält, und wählen Sie dann *Verwalten* aus.
. Wählen Sie auf der Registerkarte Übersicht des Dateisystems die Registerkarte *Volumes* aus.
. Wählen Sie die Registerkarte *Volumes*.
. Wählen Sie auf der Registerkarte *Volumes* das drei Punkte-Menü des Volumes aus, um die Snapshot-Richtlinie zu ändern.
. Wählen Sie *Data Protection actions*, *Snapshots* und dann *Manage Snapshot Policies*.
. Wählen Sie auf der Seite Snapshot Policy Management *Change an Existing Snapshot Policy* aus.
. Wählen Sie im Feld *Snapshot Policy Name* eine andere Snapshot Policy für dieses Volume aus.
+
Um automatische Snapshots zu deaktivieren, wählen Sie `none`.

+
Wenn keine anderen Snapshot-Richtlinien vorhanden sind, link:create-snapshot-policy.html["Erstellen Sie eine neue Snapshot-Richtlinie für dieses Volume"].

. Klicken Sie Auf *Anwenden*.

