---
sidebar: sidebar 
permalink: configuration-analysis.html 
keywords: configuration issues, issues, improve, analyze, storage configuration, Amazon FSx for NetApp ONTAP, FSx for ONTAP, recommendation, recommendations 
summary: NetApp Workload Factory analysiert Amazon FSx for NetApp ONTAP-Dateisystemkonfigurationen regelmäßig, um festzustellen, ob Konfigurationsprobleme vorliegen. 
---
= Konfigurationsanalyse für FSX für ONTAP-Dateisysteme
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp Workload Factory analysiert Amazon FSx for NetApp ONTAP-Dateisystemkonfigurationen regelmäßig, um festzustellen, ob Konfigurationsprobleme vorliegen. Werden Probleme gefunden, zeigt Workload Factory an, worin die Probleme bestehen, und erklärt, was geändert werden muss, damit Ihr Dateisystemspeicher optimale Leistung, Kosteneffizienz und die Einhaltung bewährter Verfahren erreicht.

Die wichtigsten Funktionen:

* Tägliche Konfigurationsanalyse
* Automatische Validierung von Best Practices
* Proaktive Beobachtbarkeit
* Einblick in Aktion
* AWS hat eine gut konzipierte Framework Advisor Architektur




[[how-it-works]]
== So funktioniert es

Workload Factory analysiert täglich Ihre Workloads, die auf Amazon FSx for NetApp ONTAP-Dateisystembereitstellungen laufen. Die Analyse liefert well-architected Status, Erkenntnisse und Empfehlungen.

Nach Abschluss der täglichen Analyse werden die Konfigurationen im Well-architected Dashboard für die Bereitstellung als „optimiert“ oder „nicht optimiert“ angezeigt. Sie finden die Gesamtoptimierungspunktzahl, Konfigurationsprobleme nach Kategorie und eine Liste der Konfigurationsprobleme und Empfehlungen. Sie können die Empfehlungen zu den Konfigurationsproblemen überprüfen. Einige Probleme können automatisch von Workload Factory behoben werden, während andere eine manuelle Intervention erfordern. In diesem Fall stellt Workload Factory detaillierte Anweisungen bereit, um Ihnen bei der Umsetzung der empfohlenen Änderungen zu helfen.

Sie können die Analyse von Konfigurationen ausblenden, die für Ihre Umgebungen nicht relevant sind. Dadurch werden unnötige Warnmeldungen und ungenaue Optimierungsergebnisse vermieden.

Es besteht auch die Möglichkeit, benutzerdefinierte Regeln in einfacher Sprache zu erstellen, um Ihre Umgebungen anhand der Standards Ihres Unternehmens und der NetApp Best Practices zu validieren. Regeln können mit einem Probelauf getestet und anschließend für die Ausführung in Ihren Umgebungen terminiert werden. link:https://docs.netapp.com/us-en/console-well-architected/learn-custom-rules.html["Weitere Informationen zu benutzerdefinierten Regeln"^].

Es besteht auch die Möglichkeit, benutzerdefinierte Regeln in einfacher Sprache zu erstellen, um Ihre Umgebungen anhand der Standards Ihres Unternehmens und der NetApp Best Practices zu validieren. Regeln können mit einem Probelauf getestet und anschließend für die Ausführung in Ihren Umgebungen terminiert werden.

link:https://docs.netapp.com/us-en/console-well-architected/learn-custom-rules.html["Weitere Informationen zu benutzerdefinierten Regeln"^].



[[why-it-matters]]
== Warum es wichtig ist

Workload Factory wendet Best Practices auf große Speicher-, Datenbank- und VMware-Umgebungen an, indem kontinuierliche Analysen mit Empfehlungseinblicken und Fehlerbehebungen kombiniert werden. Automatisierte Korrekturen, die in der Workload Factory-Konsole angewendet werden, reduzieren menschliche Fehler, gewährleisten einheitliches Management und erhalten Leistung und Zuverlässigkeit über Ihre Workload-Infrastrukturen hinweg.



[[analysis-requirements]]
== Analyseanforderungen

Für eine vollständige Dateisystemanalyse müssen Sie Folgendes tun:

* Verknüpfen Sie einen Link.  Die Link-Konnektivität ermöglicht es Workload Factory, alle Dateisystemkonfigurationen wie Datenschutz und Leistung zu analysieren.
+
link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["Erfahren Sie, wie Sie einen vorhandenen Link zuordnen oder einen neuen Link erstellen und zuordnen."].

* Gewähren Sie in Ihrem AWS-Konto die Berechtigungen _view, planning, and analysis_.
+
link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["Erfahren Sie, wie Sie einem AWS-Konto Berechtigungen erteilen"^]





[[best-practices-and-recommendations-for-storage-workloads]]
== Bewährte Verfahren und Empfehlungen für Speicher-Workloads

Das gut strukturierte Dashboard bewertet Speicherkonfigurationen anhand der ONTAP Best Practices und des AWS Well-Architected Framework. Die Bewertung enthält außerdem Empfehlungen für Verbesserungen und Fehlerbehebungen.

Die gut strukturierte Analyse kategorisiert Konfigurationen in den folgenden Säulen des Rahmenwerks: _Zuverlässigkeit_, _Sicherheit_, _operative Exzellenz_, _Kostenoptimierung_ und _Leistungseffizienz_.



[[reliability]]
=== Zuverlässigkeit

Zuverlässigkeit gewährleistet, dass Arbeitslasten ihre beabsichtigten Funktionen korrekt und konsistent erfüllen, selbst wenn es zu Störungen kommt.

* *Volume Backups*
+
Die Sicherung Ihrer Volumes unterstützt die Einhaltung von Aufbewahrungs- und Compliance-Anforderungen. Verwenden Sie Volume-Backups, um automatisierte Backups und Aufbewahrung für Ihre Daten einzurichten.

* *Snapshot Policy*
+
Lokale Snapshots für effiziente Datensicherung und schnelle Wiederherstellung einplanen. Snapshots sind sofortige, zeitpunktgenaue Abbilder Ihrer Volumes. Diese Empfehlung gilt nicht für Datenbankumgebungen.

* *Applikationskonsistente Snapshots*
+
Für Datenbankumgebungen werden applikationskonsistente Snapshots mit NetApp SnapCenter verwendet, um präzise und zuverlässige Snapshots Ihrer Volumendaten zu einem bestimmten Zeitpunkt zu erstellen. Dadurch laufen Ihre Anwendungen reibungslos und Ihre Daten bleiben sicher. SnapCenter vereinfacht die Datensicherung und unterstützt eine schnelle und korrekte Datenwiederherstellung, wodurch Ausfallzeiten reduziert und Ihre wichtigsten Workloads geschützt werden.

* *Regionenübergreifende Replikation*
+
Die regionsübergreifende Replikation stellt sicher, dass Ihre Daten in eine andere AWS-Region repliziert werden, was eine erhöhte Datenbeständigkeit und Verfügbarkeit bietet. Die Einrichtung der regionsübergreifenden Replikation unterstützt Notfallwiederherstellung und Compliance.

* *SSD-Kapazitätsreserve*
+
Die SSD-Speicherebene sollte eine Auslastung von maximal 80 % nicht überschreiten. Dies kann sich auf Lese- und Schreibvorgänge auf Ihrer Kapazitätspool-Speicherebene auswirken und die Durchsatzkapazität Ihres Dateisystems beeinträchtigen. Wenn die Kapazität erschöpft ist, werden Datenvolumes schreibgeschützt. Dienste, die versuchen, neue Daten zu schreiben, schlagen ebenfalls fehl.

* *Replikationsrichtlinienbezeichnungen*
+
Die Snapshot-Richtlinienbezeichnungen des Quellvolumes und die Replikationsrichtlinienbezeichnungen müssen übereinstimmen, um die Datenzuverlässigkeit zu gewährleisten.

* *Dateiobjektkapazität*
+
Um die Speicherkapazitätsgrenze des Volumes nicht zu erreichen, sollte der Schwellenwert für die Dateikapazität erhöht werden. Eine geringe Dateikapazität (Inodes) verhindert das Schreiben weiterer Daten auf das Volume. Workload Factory empfiehlt, die Dateikapazitätsauslastung unter 80 % zu halten, um die Erstellung neuer Dateien zu ermöglichen.





[[security]]
=== Sicherheit

Sicherheit betont den Schutz von Daten, Systemen und Vermögenswerten durch Risikobewertungen und Risikominderungsstrategien.

* *Schutz vor Ransomware (ARP/AI)*
+
NetApp Autonomous Ransomware Protection mit KI (ARP/AI) hilft, Ihre Volumes vor Ransomware-Bedrohungen zu schützen. Workload Factory empfiehlt, ARP/AI für alle Volumes zu aktivieren.

* *Nicht autorisierter iSCSI-Volume-Zugriff*
+
Volumes, die Anwendungsdaten über iSCSI bereitstellen, sollten nicht gleichzeitig NAS-Zugriff ermöglichen. Workload Factory empfiehlt, iSCSI-Volumes von der Verwendung anderer Protokolle auszuschließen.





[[operational-excellence]]
=== Operative Exzellenz

Operative Exzellenz konzentriert sich auf die Bereitstellung der optimalsten Architektur und des größten Geschäftswerts.

* *Automatisches Kapazitätsmanagement*
+
Automatisches Kapazitätsmanagement sollte aktiviert werden, um regelmäßig sicherzustellen, dass die SSD-Ebene den Schwellenwert nicht überschreitet.

* *Freier Volumenkapazitätsspielraum*
+
Workload Factory empfiehlt, dass die Volume-Kapazität die 80%ige Kapazitätsauslastung nicht überschreitet. Dies kann Auswirkungen auf Lese- und Schreibvorgänge Ihrer Anwendung haben. Volume-Kapazitätserhöhungen können manuell oder automatisch mithilfe der Volume automatische Größenanpassung-Funktion erfolgen.

* *FlexCache Schreibmodus*
+
Für optimale Leistung empfiehlt Workload Factory den Cache-Beziehungs-Schreibmodus, der am besten zu Ihrer Arbeitslast passt. Der Write-Around-Modus bietet eine bessere Leistung für leseintensive Arbeitslasten mit kleinen Dateien, während der Write-Back-Modus eine bessere Leistung für schreibintensive Arbeitslasten mit großen Dateien bietet.

* *FlexCache Replika-Größe*
+
Workload Factory empfiehlt, die automatische Größenanpassung und das Scrubbing auf Cache-Volumes zu aktivieren, um eine optimale Größe beizubehalten und den Cache auf Hot Data für maximale Effizienz zu fokussieren.

* *Für den Host sichtbare Kapazitätsberichterstattung*
+
Workload Factory empfiehlt, die host-sichtbare Kapazitätsberichterstattung zu aktivieren, um eine bessere Transparenz der Speichernutzung auf Volume-Ebene zu bieten.

* *Betriebssystem (OS) Typ*
+
Workload Factory empfiehlt, sicherzustellen, dass der ONTAP LUN-Betriebssystemtyp (OS) mit dem Partitionierungsschema des Betriebssystems übereinstimmt, um eine E/A-Ausrichtung zu erreichen. Eine fehlerhafte Konfiguration kann die Leistung beeinträchtigen.

* *Speicherplatzmanagement für Blockgeräte*
+
Workload Factory empfiehlt, die Einstellungen für den Blockgerätespeicher von LUNs, die von Datenbank-Hostinstanzen verwendet werden, so zu konfigurieren, dass Schreibfehler vermieden und die Speichereffizienz auf FSx für ONTAP verbessert werden. Diese Konfiguration gilt für die empfohlene Kombination von Einstellungen für Thin Provisioned Volumes: Speicherplatzreservierung, Speicherplatzzuweisung und fraktionelle Reserve.

* *Thin Provisioning*
+
Workload Factory empfiehlt die Konfiguration von Thin Provisioning für FSx for ONTAP Volumes, die Datenbankinstanzen hosten. Dieser Ansatz ermöglicht die Speicherung von mehr logischen Daten, als physisch verfügbar sind.





[[cost-optimization]]
=== Kostenoptimierung

Kostenoptimierung hilft Ihnen, den größtmöglichen Nutzen für Ihr Unternehmen zu erzielen und gleichzeitig die Kosten niedrig zu halten.

* *Kalte Datenauslagerung*
+
Cold-Data-Tiering kann aktiviert werden, um die SSD-Speichertier-Auslastung zu reduzieren. Workload Factory empfiehlt, für jedes Volume mit Fokus auf allgemeine Datenspeicherung eine Tiering-Richtlinie anzuwenden. Für Datenbank-Volumes wird empfohlen, Cold-Data-Tiering gegebenenfalls zu aktivieren. FSx für ONTAP scannt die Daten kontinuierlich nach Cold Data und verschiebt diese ohne Unterbrechung in die Kapazitätspool-Tier.

* *Speichereffizienzen*
+
Speichereffizienzmaßnahmen wie Verdichtung, Komprimierung und Deduplizierung ermöglichen eine optimierte Speicherauslastung und eine Reduzierung der Kosten der SSD-Ebene.

* *Ablauf der Backups*
+
Workload Factory empfiehlt, alle manuell erstellten Backups von gelöschten Volumes sowie alle Backups, die älter als zwei Wochen sind, zu löschen. Diese Backups verfallen nicht automatisch, können die Kosten erhöhen und die Komplexität steigern, wenn sie nicht mehr für SLA oder Wiederherstellung benötigt werden.

* *Ablauf der Snapshot*
+
Workload Factory empfiehlt das Löschen alter oder manuell erstellter Snapshots, die nicht mehr benötigt werden. Das Entfernen dieser Snapshots kann Kosten senken und die Unübersichtlichkeit verringern, insbesondere wenn sie nicht für Ihre SLA oder Wiederherstellungsanforderungen erforderlich sind.

* *Inaktive Blockgeräte*
+
Nachdem ein Blockgerät sieben Tage lang nicht verwendet wurde, empfiehlt Workload Factory, die Blockgerätedaten zu archivieren oder das ungenutzte Blockgerät zu löschen, um Kosten zu senken.

* *Überdimensionierte SSD-Kapazität*
+
Eine überdimensionierte SSD-Kapazitätsebene verursacht unnötige Kosten. Workload Factory empfiehlt, die SSD-Kapazität zu reduzieren, wobei ein freier Speicherplatzpuffer von 20 % beibehalten wird. Eine Reduzierungsoperation kann mehrere Stunden bis mehrere Tage dauern, und andere Dateisystemoperationen werden in dieser Zeit nicht unterstützt.

* *Inaktive NAS-Volumes*
+
Die Konfigurationsanalyse identifiziert NAS-Volumes, die nicht aktiv genutzt werden, und empfiehlt, die Volumes zu löschen oder zu archivieren, um Kosten zu reduzieren.





[[performance-efficiency]]
=== Performance-Effizienz

Leistungseffizienz trägt dazu bei, dass Ihre Speicherressourcen effektiv genutzt werden und Arbeitslasten optimal ausgeführt werden.

* *FlexGroup Volumes-Ausgleich*
+
Workload Factory empfiehlt, Ihre FlexGroup Volumes neu auszubalancieren, um die Effizienz zu verbessern. Nach der Skalierung kann die Kapazität und die Workload-Aktivität innerhalb des Volumes ungleichmäßig verteilt sein.

* *FlexVol Volumes-Ausgleich*
+
Workload Factory empfiehlt, Ihre FlexVol Volumes neu auszubalancieren, um die Effizienz zu verbessern. Nach der Skalierung kann die Kapazität und die Workload-Aktivität innerhalb des Volumes ungleichmäßig verteilt sein.



.Wie es weiter geht
link:improve-configurations.html["Sorgfältig konzipierte Filesystem-Konfigurationen implementieren"]
