---
sidebar: sidebar 
permalink: configure-active-directory.html 
keywords: configure AD, configure active directory, update ad, edit active directory 
summary:  
---
= Active Directory für eine Storage-VM konfigurieren und aktualisieren
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Konfigurieren und aktualisieren Sie Active Directory für eine Storage-VM in einem FSX für ONTAP-Dateisystem.

.Über diese Aufgabe
Die gleichen Schritte gelten für die Konfiguration und Aktualisierung von Active Directory für eine Speicher-VM.

.Schritte
. Melden Sie sich beim an link:https://console.workloads.netapp.com/["Workload Factory-Konsole"^]
. Wählen Sie unter Speicher die Option *Gehe zu Lagerbestandsbestand* aus.
. Wählen Sie auf der Registerkarte *FSX for ONTAP* das drei Punkte-Menü des Dateisystems mit der zu aktualisierenden Speicher-VM aus und wählen Sie dann *Verwalten*.
. Wählen Sie in der Dateisystemübersicht die Registerkarte *Storage VMs* aus.
. Wählen Sie auf der Registerkarte Storage VMs das Menü mit den drei Punkten der Storage-VM aus, für die Active Directory konfiguriert werden soll.
. Wählen Sie *AD-Konfiguration verwalten*.
. Geben Sie auf der Seite AD-Konfiguration managen Folgendes an:
+
.. *Active Directory-Domain zu verbinden*: Geben Sie den vollständig qualifizierten Domainnamen (FQDN) Ihres Active Directory ein.
.. *DNS-IP-Adressen*: Geben Sie bis zu drei IP-Adressen durch Kommas getrennt ein.
.. *SMB-Server NetBIOS-Name*: Geben Sie den SMB-Server NetBIOS-Namen des Active Directory-Computerobjekts ein, das für Ihre Speicher-VM erstellt werden soll. Dies ist der Name dieser SVM im Active Directory.
.. *Benutzername*: Geben Sie den Benutzernamen des Dienstkontos in Ihr vorhandenes Active Directory ein.
+
Geben Sie kein Domänenpräfix oder Suffix ein. Für `EXAMPLE\ADMIN`, verwenden `ADMIN`.

.. *Passwort*: Geben Sie das Passwort für das Service-Konto ein.
.. *Organisationseinheit (OU)*: Geben Sie die Organisationseinheit ein.
+
Die Organisationseinheit ist der Distinguished Path Name der Organisationseinheit, der Sie Ihr Dateisystem beitreten möchten.

.. *Delegierte Administratorengruppe*: Geben Sie optional die Gruppe Delegierte Dateisystemadministratoren ein.
+
Die Gruppe „Gelöschte Administratoren“ ist der Name der Gruppe in Ihrem Active Directory, die Ihr Dateisystem verwalten kann.

+
Wenn Sie Microsoft AD von AWS Managed verwenden, müssen Sie eine Gruppe wie AWS Delegated FSX Administrators, AWS Delegated Administrators oder eine benutzerdefinierte Gruppe mit delegierten Berechtigungen für die Organisationseinheit angeben.

+
Wenn Sie einem selbstverwalteten AD beitreten, verwenden Sie den Namen der Gruppe in Ihrem AD. Die Standardgruppe ist `Domain Admins`.



. Klicken Sie Auf *Anwenden*.

