---
sidebar: sidebar 
permalink: create-volume.html 
keywords: create volume, FSx for ONTAP volume 
summary: Nachdem Sie Ihr FSx für ONTAP-Dateisystem eingerichtet haben, erstellen Sie FSx für ONTAP-Volumes in der Workload Factory. 
---
= Erstellen Sie ein FSx für ONTAP-Volume in der Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Nachdem Sie Ihr FSx für ONTAP-Dateisystem eingerichtet haben, erstellen Sie FSx für ONTAP-Volumes in der Workload Factory als virtuelle Ressourcen zum Gruppieren Ihrer Daten.

.Über diese Aufgabe
FSx für ONTAP-Volumes gruppieren Daten virtuell, bestimmen, wie Daten gespeichert werden, und bestimmen die Art des Zugriffs auf Ihre Daten. Volumes verbrauchen keine Storage-Kapazität des Filesystems. Die in einem Volume gespeicherten Daten belegen primär SSD-Storage. Je nach der Tiering-Richtlinie des Volumes können die Daten auch Kapazitäts-Pool-Storage in Anspruch nehmen. Sie legen die Größe eines Volumes fest, wenn Sie es erstellen, und Sie können die Größe später ändern.

Die folgenden Protokolle können für Ihre Volumes verwendet werden:

* CIFS: File-Storage-Protokoll für Windows-Betriebssysteme
* NFS: File-Storage-Protokoll für Unix Betriebssysteme
* ISCSI: Block-Storage-Protokoll


.Bevor Sie beginnen
Überprüfen Sie die folgenden Voraussetzungen, bevor Sie ein Volume erstellen:

* Sie müssen über ein FSx für ONTAP-Dateisystem in der Workload Factory-Konsole verfügen.
* Sie benötigen eine Storage-VM.
* Für den Zugriff auf das Protokoll müssen Sie Folgendes ausführen:
+
** Um den Zugriff auf das Volume zu konfigurieren, müssen Sie einen Link zuordnen. link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["Erfahren Sie, wie Sie einen vorhandenen Link zuordnen oder einen neuen Link erstellen und zuordnen."]. Kehren Sie nach dem Verknüpfen zu diesem Vorgang zurück.
** Sie müssen den Zugriff für das ausgewählte Protokoll konfigurieren, entweder CIFS, NFS oder iSCSI.






== Erstellen eines Volumes

Sie können ein Volume mit den folgenden Tools in der Codebox erstellen: REST API, CloudFormation und Terraform. link:https://docs.netapp.com/us-en/workload-setup-admin/use-codebox.html#how-to-use-codebox["Erfahren Sie, wie Sie Codebox für die Automatisierung verwenden"^].


NOTE: Bei der Verwendung von Terraform aus der Codebox werden der Code, den Sie kopieren oder herunterladen, ausgeblendet `fsxadmin` und `vsadmin` Passwörter. Sie müssen die Passwörter erneut eingeben, wenn Sie den Code ausführen.

.Schritte
. Melden Sie sich mit einem der link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["Konsolenerfahrungen"^]an.
. Wählen Sie unter Speicher die Option *Gehe zu Lagerbestandsbestand* aus.
. Wählen Sie auf der Registerkarte *FSX for ONTAP* das drei-Punkt-Menü des Dateisystems aus, in dem Sie ein Volume erstellen möchten, und wählen Sie *Volume erstellen*.
. Geben Sie auf der Seite Volume erstellen unter Allgemeine Details die folgenden Details ein:
+
.. *Volumenname*: Geben Sie einen Namen für das Volume ein.
.. *Name der Speicher-VM*: Geben Sie optional einen Namen der Speicher-VM ein.
.. *Lautstärkestil*: Wählen Sie *FlexVol* oder *FlexGroup* Lautstärke.
+
Standardmäßig ist ein FlexVol-Volume-Stil ausgewählt.

+
Die Größe des FlexGroup-Volumes hängt von der Anzahl der Bestandteile ab und erfordert 100 GiB pro Bestandteil.

.. *Volumengröße*: Geben Sie die Volumengröße und Einheit ein.
+
Aktivieren Sie optional Volume Autogrow. Diese Option ist verfügbar, wenn Sie *Dateizugriff* als Zugriffstyp für das Volume auswählen.

.. *Volume-Autogrow*: Aktivieren Sie optional die Funktion „Volume-Autogrow“, um die Volume-Kapazität automatisch zu erweitern, bis das Volume die maximale Größe erreicht. Diese Funktion trägt der steigenden Datennutzung Rechnung und gewährleistet einen unterbrechungsfreien Betrieb.
+
Geben Sie die maximale Größe und Einheit für das Volumewachstum an. Sie können die maximale Wachstumsgröße nicht kleiner als die aktuelle Volumegröße einstellen

.. *Tags*: Optional können Sie bis zu 50 Tags hinzufügen.


. Geben Sie unter Zugriff (nur für Dateisysteme mit zugehörigen Links) die folgenden Details an:
+
.. *Zugriffstyp*: Wählen Sie *Dateizugriff* oder *Zugriff sperren*. Weitere Felder zur Konfiguration des Volume-Zugriffs unterscheiden sich je nach Auswahl.
+
*** *Dateizugriff*: Ermöglicht mehreren autorisierten Benutzern und Geräten den Zugriff auf das Volume mittels SMB/CIFS, NFS oder dualen Protokollen (SMB/NFS).
+
Füllen Sie die folgenden Felder aus, um den Dateizugriff auf das Volume einzurichten.

+
.... *NFS-Exportpolitik*: Geben Sie die folgenden Details an, um NFS-Zugriff zu ermöglichen:
+
..... *Zugriffskontrolle*: Wählen Sie eine *Benutzerdefinierte Exportrichtlinie*, *bestehende Exportpolitik* oder *kein Zugriff auf das Volume* aus dem Dropdown-Menü.
..... *Name der Exportpolitik*:
+
Wenn Sie eine benutzerdefinierte Exportrichtlinie ausgewählt haben, wählen Sie im Dropdown-Menü einen vorhandenen Richtliniennamen aus.

+
Wenn Sie eine vorhandene Exportrichtlinie ausgewählt haben, geben Sie einen neuen Richtliniennamen ein.

..... *Export Policy Rule* hinzufügen: Optional können Sie für eine benutzerdefinierte Export Policy Regeln zur Export Policy hinzufügen.


.... *CIFS-Share*: Geben Sie Folgendes an:
+
..... *Name*: Geben Sie den CIFS-Share-Namen ein, um SMB-Zugriff zu ermöglichen.
..... *Pfad*: Definieren Sie den Pfad entweder mit dem Standard-Volume-Namen oder stellen Sie eine Freigabe für ein internes Verzeichnis bereit.
+
Gültige Pfadeingaben für den Datenträgernamen, beispielsweise „Avocado“, sind wie folgt:

+
****** /Avocado
****** /avocado/ordner
****** /avocado/Ordner/Unterordner
****** /avocado/dateiname
+
Gültige Pfadangaben für den Freigabenamen, beispielsweise „Server“, sind wie folgt:

****** \\Server
****** \\Server\Projekte
****** \\Server\Projekte\Gemeinsame Ressourcen


..... *Berechtigungen*: Wählen Sie Vollzugriff, Lesen/Schreiben, Lesen oder keinen Zugriff und geben Sie dann die Benutzer oder Gruppen getrennt durch ein Semikolon ( ; ) ein. Bei Benutzern oder Gruppen wird zwischen Groß- und Kleinschreibung unterschieden, und die Domäne des Benutzers muss im Format „Domain\username“ enthalten sein.


.... *Sicherheitsstil*: Wählen Sie für Dual-Protokoll-Volumes entweder den UNIX- oder NTFS-Sicherheitstil aus. UNIX ist der Standard-Sicherheitstil für Dual-Protokoll-Volumes. Eine detaillierte Anleitung zum User Mapping finden Sie in diesem Kontext im AWS Blog-Artikel link:https://aws.amazon.com/blogs/storage/enabling-multiprotocol-workloads-with-amazon-fsx-for-netapp-ontap["Aktivieren von Multiprotokoll-Workloads mit Amazon FSX for NetApp ONTAP"^].


*** *Blockzugriff*: Ermöglicht Hosts, die kritische Geschäftsanwendungen ausführen, den Zugriff auf das Volume über das iSCSI-Protokoll. Der Block-Zugriff ist nur verfügbar, wenn die horizontal skalierbare Filesystem-Implementierung maximal sechs HA-Paare umfasst.
+
Füllen Sie die folgenden Felder aus, um den Blockzugriff auf das Volume einzurichten.

+
.... *ISCSI-Konfiguration*: Geben Sie die folgenden Details an, um iSCSI für den Blockzugriff auf das Volume zu konfigurieren.
+
..... Wählen Sie *Neue Initiatorgruppe erstellen* oder *vorhandene Initiatorgruppe zuordnen* aus.
..... Wählen Sie das *Host-Betriebssystem* aus dem Dropdown-Menü aus.
..... Geben Sie einen *Initiatorgruppennamen* für eine neue Initiatorgruppe ein.
..... Fügen Sie unter Host-Initiatoren einen oder mehrere iSCSI Qualified Name (IQN)-Hostinitiatoren hinzu.








. Geben Sie unter Effizienz und Sicherung folgende Informationen an:
+
.. *Speichereffizienz*: Standardmäßig aktiviert. Wählen Sie diese Option, um die Funktion zu deaktivieren.
+
ONTAP erreicht Speichereffizienz durch Deduplizierungs- und Komprimierungsfunktionen. Deduplizierung eliminiert doppelte Datenblöcke. Bei der Datenkomprimierung werden die Datenblöcke komprimiert, damit sie die erforderliche Menge an physischem Storage reduzieren können.

.. *Snapshot Policy*: Wählen Sie die Snapshot Policy aus, um die Häufigkeit und Aufbewahrung von Snapshots festzulegen.
+
Nachfolgend sind die Standardrichtlinien von AWS aufgeführt. Für benutzerdefinierte Snapshot-Richtlinien müssen Sie link:link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["Verknüpfen Sie eine Verknüpfung"] .

+
`default`:: Diese Richtlinie erstellt automatisch Snapshots nach dem folgenden Zeitplan. Die ältesten Snapshot-Kopien werden gelöscht, um Platz für neuere Kopien zu schaffen:
+
--
*** Maximal sechs stündliche Snapshots wurden fünf Minuten nach der Stunde erstellt.
*** Maximal zwei Snapshots täglich von Montag bis Samstag um 10 Minuten nach Mitternacht.
*** Maximal zwei wöchentliche Schnappschüsse, die jeden Sonntag um 15 Minuten nach Mitternacht erstellt wurden.
+

NOTE: Snapshot-Zeiten basieren auf der Zeitzone des Dateisystems, die standardmäßig auf Coordinated Universal Time (UTC) eingestellt ist. Informationen zum Ändern der Zeitzone finden Sie in link:https://library.netapp.com/ecmdocs/ECMP1155684/html/GUID-E26E4C94-DF74-4E31-A6E8-1D2D2287A9A1.html["Anzeigen und Einstellen der Systemzeitzone"^] der NetApp-Supportdokumentation.



--
`default-1weekly`:: Diese Richtlinie funktioniert auf die gleiche Weise wie die `default` Richtlinie, außer dass nur ein Snapshot aus dem wöchentlichen Zeitplan aufbewahrt wird.
`none`:: Diese Richtlinie erstellt keine Snapshots. Sie können diese Richtlinie Volumes zuweisen, um die automatische Erstellung von Snapshots zu verhindern.


.. *Tiering Policy*: Wählen Sie die Tiering Policy für die auf dem Volume gespeicherten Daten.
+
_Balanced (Auto)_ ist die Standard-Tiering-Richtlinie beim Erstellen eines Volumes mit der Workload Factory-Konsole. Weitere Informationen zu Volume-Tiering-Richtlinien finden Sie link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/volume-storage-capacity.html#data-tiering-policy["Speicherkapazität für Volumes"^] in der Dokumentation zu AWS FSX for NetApp ONTAP. Beachten Sie, dass Workload Factory für Tiering-Richtlinien auf Basis von Anwendungsfällen in der Workload Factory verwendet und Tiering-Richtliniennamen für FSX für ONTAP in Klammern enthält.

.. *Unveränderliche Dateien*: Dieses Feature, auch SnapLock genannt, ist standardmäßig deaktiviert. Durch die Aktivierung unveränderlicher Dateien wird das Löschen oder Überschreiben von Daten für einen festgelegten Zeitraum verhindert. Die Aktivierung dieser Funktion ist nur während der Volume-Erstellung möglich. Nachdem die Funktion aktiviert wurde, kann sie nicht deaktiviert werden. Dies ist eine Premium-Funktion für FSX für ONTAP, die eine zusätzliche Gebühr in Rechnung stellt. Weitere Informationen finden Sie link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/how-snaplock-works.html["So funktioniert SnapLock"^]in der Dokumentation zu Amazon FSX for NetApp ONTAP.
+
Durch die Aktivierung der Funktion „unveränderliche Dateien“ werden Dateien in diesem Volume dauerhaft in einen unveränderlichen WORM-Zustand (Write-Once-Read-Many) versetzt.

+
Aufbewahrungsmodi:: Sie können zwischen zwei Aufbewahrungsmodi wählen: _Enterprise_ oder _Compliance_.
+
--
*** Im _Enterprise_-Modus können unveränderliche Dateien oder SnapLock, Administratoren eine Datei während des Aufbewahrungszeitraums löschen.
*** Im _Compliance_-Modus kann eine WORM-Datei nicht vor Ablauf der Aufbewahrungsfrist gelöscht werden. Auf ähnliche Weise kann das unveränderliche Volume erst gelöscht werden, wenn die Aufbewahrungsfristen für alle Dateien innerhalb des Volume abgelaufen sind.


--
Aufbewahrungszeitraum:: Die Aufbewahrungsfrist hat zwei Einstellungen - _Retention Policy_ und _Retention Periods_. Die _Retention Policy_ definiert, wie lange Dateien in einem unveränderlichen WORM-Zustand aufbewahrt werden sollen. Sie können Ihre eigene Aufbewahrungsrichtlinie festlegen oder die Standardaufbewahrungsrichtlinie (nicht spezifiziert) verwenden, die 30 Jahre beträgt. Die minimalen und maximalen _Aufbewahrungsfristen_ definieren den zulässigen Zeitbereich für das Sperren von Dateien.
+
--
HINWEIS:: Selbst wenn die Aufbewahrungsfrist abgelaufen ist, können Sie keine WORM-Datei ändern. Sie können sie nur löschen oder einen neuen Aufbewahrungszeitraum festlegen, um den WORM-Schutz erneut zu aktivieren.


--
Automatisches Commit:: Sie haben die Möglichkeit, die Autocommit-Funktion zu aktivieren. Die Autocommit-Funktion beüberträgt eine Datei in den WORM-Zustand auf einem SnapLock Volume, wenn sich die Datei für die Dauer des Autocommit nicht geändert hat. Die Funktion Autocommit ist standardmäßig deaktiviert. Sie müssen sicherstellen, dass sich die Dateien, die Sie automatisch festschreiben möchten, auf einem SnapLock-Volume befinden.
Volume Append-Modus:: Vorhandene Daten in einer WORM-geschützten Datei können nicht geändert werden. Unveränderliche Dateien ermöglichen es Ihnen jedoch, mithilfe von WORM-anhängen-baren Dateien den Schutz bestehender Daten zu erhalten. So können Sie beispielsweise Protokolldateien generieren oder Audio- oder Videostreaming-Daten erhalten, während Sie Daten inkrementell auf sie schreiben. link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/worm-state.html#worm-state-append["Erfahren Sie mehr über den Volume-Append-Modus"^] In der Dokumentation zu Amazon FSX for NetApp ONTAP.
+
--
.Schritte für unveränderliche Dateien
... Aktivieren Sie *unveränderliche Dateien mit SnapLock*.
... Wählen Sie das Feld aus, um zuzustimmen und fortzufahren.
... Wählen Sie *Enable*.
... *Retention Mode*: Wählen Sie *Enterprise* oder *Compliance* Modus.
... *Aufbewahrungsfrist*:
+
**** Wählen Sie die Aufbewahrungsrichtlinie aus:
+
***** *Unspezifiziert*: Setzt die Aufbewahrungspolitik auf 30 Jahre.
***** *Zeitraum angeben*: Geben Sie die Anzahl der Sekunden, Minuten, Stunden, Tage, Monate oder Jahre ein, um Ihre eigene Aufbewahrungsrichtlinie festzulegen.


**** Wählen Sie die Mindest- und Höchstaufbewahrungszeiträume aus:
+
***** *Minimum*: Geben Sie die Anzahl der Sekunden, Minuten, Stunden, Tage, Monate oder Jahre ein, um die Mindestaufbewahrungsdauer festzulegen.
***** *Maximum*: Geben Sie die Anzahl der Sekunden, Minuten, Stunden, Tage, Monate oder Jahre ein, um die maximale Aufbewahrungsfrist festzulegen.




... *Autocommit*: Deaktivieren oder aktivieren Sie Autocommit. Wenn Sie die automatische Übertragung aktivieren, legen Sie den Zeitraum für die automatische Übertragung fest.
... *Volume Append-Modus*: Deaktivieren oder aktivieren. Ermöglicht das Hinzufügen neuer Inhalte zu WORM-Dateien.


--


.. *ARP/AI*: NetApp Autonomous Ransomware Protection mit AI (ARP/AI) ist standardmäßig aktiviert, wenn ein Link mit dem Dateisystem verknüpft ist. link:https://docs.netapp.com/us-en/workload-fsx-ontap/ransomware-protection.html["Erfahren Sie mehr über ARP/AI"]. Akzeptieren Sie die Aussage, um fortzufahren.
+
Wenn die Funktion nicht verfügbar ist, kann dies einen der folgenden Gründe haben:

+
*** Dem Dateisystem ist kein Link zugeordnet. link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["Erfahren Sie, wie Sie einen vorhandenen Link zuordnen oder einen neuen Link erstellen und zuordnen."]. Kehren Sie nach dem Verknüpfen zu diesem Vorgang zurück.
*** Volumes mit unveränderlichen Dateien und Volumes mit iSCSI- und NVMe-Protokollen werden für ARP/AI nicht unterstützt.
*** Das Dateisystem verfügt bereits über eine ARP/AI-Richtlinie.




. Geben Sie unter Erweiterte Konfiguration Folgendes an:
+
.. *Verbindungspfad*: Geben Sie den Speicherort im Namespace der Speicher-VM ein, an dem das Volume gemountet wird. Der Standard-Verbindungspfad ist `/<volume-name>`.
.. *Aggregatliste*: Nur für FlexGroup Volumes. Hinzufügen oder Entfernen von Aggregaten Die Mindestanzahl an Aggregaten ist eins.
.. *Anzahl der Komponenten*: Nur für FlexGroup-Volumes. Geben Sie die Anzahl der Bestandteile pro Aggregat ein. Pro Komponente sind 100 gib erforderlich.


. Wählen Sie *Erstellen*.


.Ergebnis
Die Workload Factory initiiert die Volume-Erstellung. Nach der Erstellung wird das neue Volume auf der Registerkarte „Volumes“ angezeigt.
