---
sidebar: sidebar 
permalink: create-snapshot.html 
keywords: create snapshot, snapshot 
summary: Erstellen Sie einen manuellen Snapshot eines FSx für ONTAP -Volumes in NetApp Workload Factory.  Snapshots sind zeitpunktbezogene Versionen des Inhalts Ihres Volumes. 
---
= Erstellen Sie einen manuellen Snapshot eines FSX für ONTAP-Volumes
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Erstellen Sie einen manuellen Snapshot eines FSx für ONTAP -Volumes in NetApp Workload Factory.  Snapshots sind zeitpunktbezogene Versionen des Inhalts Ihres Volumes.

Snapshots sind Ressourcen von Volumes und sofortige Erfassung von Daten, die nur für geänderte Daten Speicherplatz verbrauchen. Da sich die Daten im Laufe der Zeit ändern, belegen Snapshots in der Regel mit zunehmendem Alter mehr Speicherplatz.

FSX für ONTAP-Volumes verwenden Just-in-Time Copy-on-Write, sodass unveränderte Dateien in Snapshots keine Kapazität des Volumes beanspruchen.


NOTE: Snapshots sind keine Kopien Ihrer Daten. Wenn Sie Kopien Ihrer Daten erstellen möchten, sollten Sie FSX für ONTAP-Backups oder Volume-Replizierungsfunktionen in Erwägung ziehen.

.Bevor Sie beginnen
Sie müssen einen Link zuordnen, um einen manuellen Snapshot eines Volumes zu erstellen. link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["Erfahren Sie, wie Sie einen vorhandenen Link zuordnen oder einen neuen Link erstellen und zuordnen."]. Kehren Sie nach dem Verknüpfen zu diesem Vorgang zurück.

.Schritte
. Melden Sie sich mit einem der link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["Konsolenerfahrungen"^]an.
. Wählen Sie in der Kachel „Speicher“ die Option „Zum Speicher gehen“ aus.
. Wählen Sie im Speichermenü *FSx für ONTAP* aus.
. Wählen Sie in *FSx for ONTAP* das Aktionsmenü des Dateisystems aus, das das Volume enthält, für das ein Snapshot erstellt werden soll, und wählen Sie dann *Verwalten*.
. Wählen Sie in der Dateisystemübersicht die Registerkarte *Volumes* aus.
. Wählen Sie auf der Registerkarte *Volumes* das Aktionsmenü für das Volume aus, das mit Snapshots geschützt werden soll.
. Wählen Sie *Datenschutzaktionen* und dann *Snapshots verwalten*.
. Wählen Sie auf der Seite „Snapshots verwalten“ die Option „Snapshot erstellen“ aus.
. Führen Sie im Dialogfeld „Snapshot erstellen“ die folgenden Schritte aus:
+
.. Geben Sie im Feld *Snapshot-Name* einen Snapshot-Namen ein.
.. Wählen Sie optional ein Etikett aus oder erstellen Sie ein neues Etikett.
.. Legen Sie die *Aufbewahrungsfrist* als Anzahl von Stunden, Tagen, Monaten oder Jahren fest.
.. Optional: *Machen Sie diesen Snapshot unveränderlich*, um zu verhindern, dass der Snapshot während der Aufbewahrungsfrist gelöscht wird.
+
Akzeptieren Sie die Aussage zu unveränderlichen Snapshots.



. Wählen Sie *Erstellen*.

