---
sidebar: sidebar 
permalink: create-volume-from-snapshot.html 
keywords: create volume from snapshot, new volume 
summary: Erstellen Sie einen manuellen Snapshot eines FSX für ONTAP-Volumes in der BlueXP -Workload-Fabrik. Snapshots sind Point-in-Time-Versionen des Inhalts Ihres Volumes. 
---
= Erstellen Sie aus einem Snapshot ein neues FSX für ONTAP-Volume
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Erstellen Sie aus einem Snapshot in der BlueXP -Workload-Farm ein neues FSX für ONTAP-Volume, um Point-in-Time-Recovery zu ermöglichen.

.Über diese Aufgabe
Ein Snapshot ist ein schreibgeschütztes Abbild eines FSX für ONTAP Volumes, das zu einem Zeitpunkt erstellt wurde. Die Erstellung eines neuen Volumes aus einem Snapshot macht eine Kopie eines gesamten Volumes innerhalb von wenigen Sekunden unabhängig von der Volume-Größe. Die neu erstellte Kopie stellt ein neues Volume dar.

.Bevor Sie beginnen
Beachten Sie die folgenden Einschränkungen, bevor Sie ein Volume aus einem Snapshot erstellen:

* Änderungen an Berechtigungsmodellen: Wenn Sie diesen Vorgang zum Umschalten des Protokolltyps des Network-Attached Storage (NAS) verwenden, kann er auch das Berechtigungsmodell wechseln, das der Sicherheitstyp bereitstellt. Es kann zu Problemen mit Dateizugriffsberechtigungen kommen, die Sie nur manuell mit Administratorzugriff mithilfe der NAS-Client-Tools für die Berechtigungseinstellung beheben können.
* Erhöhter Datenträgerverbrauch: Nachdem Sie ein Volume aus einem Snapshot erstellt haben, haben Sie zwei unabhängige Volumes, und beide verbrauchen Kapazität vom Host-Dateisystem.


.Schritte
. Melden Sie sich mit einem der link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["Konsolenerfahrungen"^]an.
. Wählen Sie unter Speicher die Option *Gehe zu Lagerbestandsbestand* aus.
. Wählen Sie auf der Registerkarte *FSX for ONTAP* das drei-Punkt-Menü des Dateisystems mit dem Volume-Snapshot aus und wählen Sie dann *Verwalten*.
. Wählen Sie in der Dateisystemübersicht die Registerkarte *Volumes* aus.
. Wählen Sie auf der Registerkarte Volumes das drei-Punkt-Menü für das Volume aus, auf dem der Snapshot erstellt werden soll.
. Wählen Sie *Data Protection actions*, *Snapshots* und dann *Create a Volume from a Snapshot*.
. Geben Sie im Dialogfeld Volume aus einem Snapshot erstellen den Snapshot-Namen ein.
. Wählen Sie *Erstellen*.

