---
sidebar: sidebar 
permalink: create-volume-from-snapshot.html 
keywords: create volume from snapshot, new volume 
summary: Erstellen Sie einen manuellen Snapshot eines FSX für ONTAP-Volumes. Snapshots sind Point-in-Time-Versionen des Inhalts Ihres Volumes. 
---
= Erstellen Sie aus einem Snapshot ein neues FSX für ONTAP-Volume
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Erstellen Sie aus einem Snapshot ein neues FSX für ONTAP-Volume, um die zeitpunktgenaue Recovery zu ermöglichen.

.Über diese Aufgabe
Ein Snapshot ist ein schreibgeschütztes Abbild eines FSX für ONTAP Volumes, das zu einem Zeitpunkt erstellt wurde. Die Erstellung eines neuen Volumes aus einem Snapshot macht eine Kopie eines gesamten Volumes innerhalb von wenigen Sekunden unabhängig von der Volume-Größe. Die neu erstellte Kopie stellt ein neues Volume dar.

.Bevor Sie beginnen
Beachten Sie die folgenden Einschränkungen, bevor Sie ein Volume aus einem Snapshot erstellen:

* Änderungen an Berechtigungsmodellen: Wenn Sie diesen Vorgang zum Umschalten des Protokolltyps des Network-Attached Storage (NAS) verwenden, kann er auch das Berechtigungsmodell wechseln, das der Sicherheitstyp bereitstellt. Es kann zu Problemen mit Dateizugriffsberechtigungen kommen, die Sie nur manuell mit Administratorzugriff mithilfe der NAS-Client-Tools für die Berechtigungseinstellung beheben können.
* Erhöhter Datenträgerverbrauch: Nachdem Sie ein Volume aus einem Snapshot erstellt haben, haben Sie zwei unabhängige Volumes, und beide verbrauchen Kapazität vom Host-Dateisystem.


.Schritte
. Melden Sie sich bei der Workload Factory-Konsole an.
. Wählen Sie unter Speicher die Option *Gehe zu Lagerbestandsbestand* aus.
. Klicken Sie auf der Registerkarte *FSX for ONTAP* auf das Menü mit den drei Punkten des Dateisystems mit dem Volume-Snapshot und wählen Sie dann *Verwalten*.
. Wählen Sie in der Dateisystemübersicht die Registerkarte *Volumes* aus.
. Klicken Sie auf der Registerkarte Volumes auf das Menü drei Punkte für das Volume mit dem Snapshot, von dem Sie ein Volume erstellen möchten.
. Wählen Sie *Data Protection actions*, *Snapshots* und dann *Create a Volume from a Snapshot*.
. Geben Sie im Dialogfeld Volume aus einem Snapshot erstellen den Snapshot-Namen ein.
. Klicken Sie Auf *Erstellen*.

