---
sidebar: sidebar 
permalink: create-snapshot-policy.html 
keywords: create 
summary: Erstellen Sie eine benutzerdefinierte Snapshot-Richtlinie für eine Speicher-VM in der Workload Factory. 
---
= Erstellen einer Snapshot-Richtlinie für Speicher-VMs in der Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Erstellen Sie eine benutzerdefinierte Snapshot-Richtlinie für Speicher-VMs in der Workload Factory, um die Erstellung und Aufbewahrung von Snapshots zu verwalten.  Eine Snapshot-Richtlinie definiert, wie das System Snapshots für eine Speicher-VM erstellt.  Sie können eine Snapshot-Richtlinie für eine Speicher-VM in einem FSx for ONTAP -Dateisystem erstellen.  Sie können die Richtlinie auch für mehrere Speicher-VMs freigeben.

.Über diese Aufgabe
Sie können eine benutzerdefinierte Snapshot-Richtlinie erstellen, die sich von den drei integrierten Snapshot-Richtlinien für FSX für ONTAP unterscheidet:

* `default`
* `default-1weekly`
* `none`


Standardmäßig ist jedes Volume mit der Snapshot-Richtlinie des Dateisystems verknüpft `default` . Wir empfehlen, diese Richtlinie für die meisten Workloads zu verwenden.

Durch das Anpassen einer Richtlinie können Sie festlegen, wann Snapshots erstellt werden sollen, wie viele Kopien aufbewahrt werden sollen und wie sie benannt werden sollen.

.Bevor Sie beginnen
* Sobald eine Snapshot-Richtlinie erstellt wurde, kann ihre Zuordnung zu den Speicher-VM(s) nicht geändert werden, Sie können die Richtlinie jedoch immer hinzufügen oder aus Volumes entfernen.
* Beachten Sie Folgendes über die Snapshot-Kapazität, bevor Sie Snapshots verwenden:
+
** Bei den meisten Datensätzen reicht eine zusätzliche Kapazität von 20 % aus, um Snapshots für bis zu vier Wochen aufzubewahren. Je älter die Daten werden, desto wahrscheinlicher wird die Verwendung für Wiederherstellungen.
** Das Überschreiben aller Daten in einem Snapshot erfordert eine erhebliche Volume-Kapazität, was für die Bereitstellung von Volume-Kapazität von Bedeutung ist.


* Um eine benutzerdefinierte Snapshot-Richtlinie zu erstellen, müssen Sie einen Link zuordnen. link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["Erfahren Sie, wie Sie einen vorhandenen Link zuordnen oder einen neuen Link erstellen und zuordnen."]. Kehren Sie nach dem Verknüpfen zu diesem Vorgang zurück.


.Schritte
. Melden Sie sich mit einem der link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["Konsolenerfahrungen"^]an.
. Wählen Sie unter *Storage* *zum Lagerbestandsverzeichnis* gehen.
. Wählen Sie im Register *FSX for ONTAP* das drei-Punkt-Menü des Dateisystems mit dem Volume aus und wählen Sie dann *Verwalten*.
. Wählen Sie in der Dateisystemübersicht die Registerkarte *Storage VMs* aus.
. Wählen Sie auf der Registerkarte *Storage VMs* das drei-Punkt-Menü für das Volume aus, das mit geplanten Snapshots geschützt werden soll, dann *Advanced Actions* und dann *Manage Snapshot Policies*.
. Wählen Sie auf der Seite Snapshot Policy Management *Create Snapshot Policy* aus.
. Geben Sie im Feld *Snapshot Policy Name* einen Namen für die Snapshot Policy ein.
. Geben Sie optional eine Beschreibung für die Snapshot-Richtlinie ein.
. Wählen Sie unter *Policy schedule and copies* aus, wann Snapshots erstellt werden sollen. Zum Beispiel jede Minute oder jede Stunde.
+
Sie können mehr als eine Frequenz auswählen.

. Geben Sie unter *Anzahl der Kopien* die Anzahl der Kopien ein, die beibehalten werden sollen.
+
Die maximale Anzahl von Kopien beträgt 1,023.

. Optional: Geben Sie unter *Namenskonventionen* ein *Präfix* für die Richtlinie ein.
. *Retention Label* wird automatisch ausgefüllt.
+
Dieses Label bezieht sich auf das SnapMirror- oder Replikationslabel, mit dem nur angegebene Snapshots für die Replikation vom Quell- zum Zieldateisystem ausgewählt werden.

. Optional: Aktivieren Sie *unveränderliche Snapshots* für alle benötigten Zeitpläne, legen Sie die *Aufbewahrungsfrist* für jeden Zeitplan fest und akzeptieren Sie die Anweisung, um fortzufahren.
+
Wenn Sie unveränderliche Snapshots aktivieren, werden alle Snapshots in dieser Snapshot-Richtlinie gesperrt, um zu verhindern, dass die Snapshots während des Aufbewahrungszeitraums gelöscht werden.

. *Freigabe über Storage-VMs*: Standardmäßig aktiviert. Wenn diese Option aktiviert ist, wird die Snapshot-Richtlinie für alle Storage-VMs im File-System freigegeben. Deaktivieren Sie, um eine Snapshot-Richtlinie für eine einzelne Storage-VM zu erstellen.
. Wählen Sie *Erstellen*.

