---
sidebar: sidebar 
permalink: create-backup.html 
keywords: create backup, volume backup, back up a volume 
summary: Erstellen Sie außerhalb regelmäßig geplanter Sicherungen eine manuelle Sicherung eines Volumes in NetApp Workload Factory. 
---
= Erstellen Sie eine manuelle Sicherung eines Volumes in NetApp Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Erstellen Sie eine manuelle Sicherung eines Volumes außerhalb regelmäßig geplanter Sicherungen in NetApp Workload Factory.

.Über diese Aufgabe
FSX für ONTAP-Backups erfolgen pro Volume, sodass jedes Backup nur die Daten in einem bestimmten Volume enthält.

FSX für ONTAP-Backups sind inkrementell, was bedeutet, dass nur die Daten auf dem Volume, die sich nach Ihrem letzten Backup geändert haben, gespeichert werden. Dies minimiert die zur Erstellung des Backups benötigte Zeit und den für das Backup benötigten Storage-Bedarf. Dadurch sparen Sie Storage-Kosten, da Daten nicht dupliziert werden.

.Bevor Sie beginnen
Um Backups Ihrer Volumes zu erstellen, müssen sowohl das Volume als auch das Dateisystem über ausreichend SSD-Speicherkapazität verfügen, um den Backup-Snapshot zu speichern. Bei der Erstellung eines Backup-Snapshots kann die zusätzliche Speicherkapazität, die durch den Snapshot verbraucht wird, nicht dazu führen, dass das Volume SSD-Storage-Auslastung von über 98 % überschreitet. In diesem Fall schlägt die Sicherung fehl.

.Schritte
. Melden Sie sich mit einem der link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["Konsolenerfahrungen"^]an.
. Wählen Sie in der Kachel „Speicher“ die Option „Zum Speicher gehen“ aus.
. Wählen Sie im Speichermenü *FSx für ONTAP* aus.
. Wählen Sie in *FSx for ONTAP* das Aktionsmenü des Dateisystems mit dem Volume und wählen Sie dann *Verwalten*.
. Wählen Sie in der Dateisystemübersicht die Registerkarte *Volumes* aus.
. Wählen Sie auf der Registerkarte *Volumes* das Aktionsmenü für das zu sichernde Volume aus.
. Wählen Sie *Data Protection Actions*, *FSX for ONTAP Backup* und dann *Manual Backup*.
. Geben Sie im Dialogfeld Manuelle Sicherung einen Namen für das Backup ein.
. Wählen Sie *Backup*.

