---
sidebar: sidebar 
permalink: create-storage-vm.html 
keywords: create storage VM, create svm 
summary: 'Sie können eine FSx für ONTAP -Speicher-VM (SVM) erstellen, um Speicher- und Datendienste für Ihre Workloads in NetApp Workload Factory bereitzustellen.' 
---
= Erstellen Sie eine Storage-VM für ein FSX für ONTAP-Filesystem
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Erstellen Sie eine Storage-VM (SVM) für ein FSx for ONTAP Dateisystem, um virtuell auf Speicher- und Datendienste für Ihre Workloads in NetApp Workload Factory zuzugreifen.

.Über diese Aufgabe
Storage-VMs sind isolierte Dateiserver, mit denen Sie auf die Daten der einzelnen Workloads im Workload Factory Storage zugreifen können.  Jede SVM verfügt über eigene Administratoranmeldeinformationen und Endpunkte für die Verwaltung und den Zugriff auf Daten.

Wenn Sie mit SVMs auf Daten in FSX for ONTAP zugreifen, mounten Ihre Clients und Workstations über den Endpunkt (IP-Adresse) der SVM ein Volume, eine CIFS/SMB-Freigabe oder eine iSCSI-LUN, die von einer SVM gehostet wird.

.Bevor Sie beginnen
Überprüfen Sie die unterstützte Anzahl von Storage-VMs pro Dateisystem. link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/managing-svms.html#max-svms["Management von FSX für ONTAP Storage Virtual Machines"^]In der AWS-Dokumentation finden Sie Informationen zur maximalen Anzahl von SVMs pro Filesystem.



== Erstellen einer Storage-VM

Sie können eine Speicher-VM über die Workload Factory-Konsole erstellen.  Sie können auch die folgenden in der Codebox verfügbaren Tools verwenden: REST API, CloudFormation und Terraform. link:https://docs.netapp.com/us-en/workload-setup-admin/use-codebox.html#how-to-use-codebox["Erfahren Sie, wie Sie Codebox für die Automatisierung verwenden"^] .


NOTE: Bei der Verwendung von Terraform aus der Codebox werden der Code, den Sie kopieren oder herunterladen, ausgeblendet `fsxadmin` und `vsadmin` Passwörter. Sie müssen die Passwörter erneut eingeben, wenn Sie den Code ausführen.

.Schritte
. Melden Sie sich mit einem der link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["Konsolenerfahrungen"^]an.
. Wählen Sie in der Kachel „Speicher“ die Option „Zum Speicher gehen“ aus.
. Wählen Sie im Speichermenü *FSx für ONTAP* aus.
. Wählen Sie unter *FSx for ONTAP* das Aktionsmenü des Dateisystems aus, für das Sie eine Speicher-VM erstellen möchten, und wählen Sie *Speicher-VM erstellen*.
. Stellen Sie auf der Seite Storage VM unter Storage VM Configuration Folgendes bereit:
+
.. *Name*: Geben Sie einen Namen für die Speicher-VM ein.
.. *Speicher-VM-Anmeldeinformationen*: Geben Sie ein Passwort für den Benutzer dieser Speicher-VM ein `vsadmin` oder verwenden Sie die Benutzeranmeldeinformationen des Dateisystems `fsxadmin` .
.. *Sicherheitsstil des Root-Volumes*: Wählen Sie den Sicherheitstyp des Root-Volumes abhängig von der Art der Clients, die auf Ihre Daten zugreifen - UNIX (Linux-Clients), NTFS (Windows-Clients) oder gemischt.
.. *Tags*: Optional können Sie bis zu 50 Tags hinzufügen.


. Wählen Sie *Erstellen*.

