---
sidebar: sidebar 
permalink: create-snapshot.html 
keywords: create snapshot, snapshot 
summary: Erstellen Sie einen manuellen Snapshot eines FSX für ONTAP-Volumes in der BlueXP -Workload-Fabrik. Snapshots sind Point-in-Time-Versionen des Inhalts Ihres Volumes. 
---
= Erstellen Sie einen manuellen Snapshot eines FSX für ONTAP-Volumes
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Erstellen Sie einen manuellen Snapshot eines FSX für ONTAP-Volumes in der BlueXP -Workload-Fabrik. Snapshots sind Point-in-Time-Versionen des Inhalts Ihres Volumes.

Snapshots sind Ressourcen von Volumes und sofortige Erfassung von Daten, die nur für geänderte Daten Speicherplatz verbrauchen. Da sich die Daten im Laufe der Zeit ändern, belegen Snapshots in der Regel mit zunehmendem Alter mehr Speicherplatz.

FSX für ONTAP-Volumes verwenden Just-in-Time Copy-on-Write, sodass unveränderte Dateien in Snapshots keine Kapazität des Volumes beanspruchen.


NOTE: Snapshots sind keine Kopien Ihrer Daten. Wenn Sie Kopien Ihrer Daten erstellen möchten, sollten Sie FSX für ONTAP-Backups oder Volume-Replizierungsfunktionen in Erwägung ziehen.

.Bevor Sie beginnen
Sie müssen einen Link zuordnen, um einen manuellen Snapshot eines Volumes zu erstellen. link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["Erfahren Sie, wie Sie einen vorhandenen Link zuordnen oder einen neuen Link erstellen und zuordnen."]. Kehren Sie nach dem Verknüpfen zu diesem Vorgang zurück.

.Schritte
. Melden Sie sich mit einem der link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["Konsolenerfahrungen"^]an.
. Wählen Sie unter *Storage* *zum Lagerbestandsverzeichnis* gehen.
. Wählen Sie auf der Registerkarte *FSX für ONTAP* das drei-Punkt-Menü des Dateisystems aus, das das Volume enthält, für das Sie einen Snapshot erstellen möchten, und wählen Sie dann *Verwalten* aus.
. Wählen Sie in der Dateisystemübersicht die Registerkarte *Volumes* aus.
. Wählen Sie auf der Registerkarte *Volumes* das drei-Punkt-Menü für das Volume aus, das mit Snapshots geschützt werden soll.
. Wählen Sie *Data Protection actions*, *Snapshots* und dann *Create a Snapshot*.
. Geben Sie im Dialogfeld Snapshot erstellen einen Snapshot-Namen in das Feld *Snapshot-Name* ein.
. Optional: Machen Sie den Snapshot unveränderlich, um zu verhindern, dass der Snapshot während des Aufbewahrungszeitraums gelöscht wird.
+
.. Aktivieren Sie *unveränderliche Snapshots*.
.. Legen Sie die *Aufbewahrungsfrist* als Anzahl von Stunden, Tagen, Monaten oder Jahren fest.
.. Akzeptieren Sie die Aussage zu unveränderlichen Snapshots.


. Wählen Sie *Erstellen*.


.Ergebnis
Das Volume verfügt über eine Snapshot-Kopie.
