---
sidebar: sidebar 
permalink: create-snapshot.html 
keywords: create snapshot, snapshot 
summary: Erstellen Sie einen manuellen Snapshot eines FSX für ONTAP-Volumes. Snapshots sind Point-in-Time-Versionen des Inhalts Ihres Volumes. 
---
= Erstellen Sie einen manuellen Snapshot eines FSX für ONTAP-Volumes
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Erstellen Sie einen manuellen Snapshot eines FSX für ONTAP-Volumes. Snapshots sind Point-in-Time-Versionen des Inhalts Ihres Volumes.

Snapshots sind Ressourcen von Volumes und sofortige Erfassung von Daten, die nur für geänderte Daten Speicherplatz verbrauchen. Da sich die Daten im Laufe der Zeit ändern, belegen Snapshots in der Regel mit zunehmendem Alter mehr Speicherplatz.

FSX für ONTAP-Volumes verwenden Just-in-Time Copy-on-Write, sodass unveränderte Dateien in Snapshots keine Kapazität des Volumes beanspruchen.


NOTE: Snapshots sind keine Kopien Ihrer Daten. Wenn Sie Kopien Ihrer Daten erstellen möchten, sollten Sie FSX für ONTAP-Backups oder Volume-Replizierungsfunktionen in Erwägung ziehen.

.Bevor Sie beginnen
Sie müssen link:manage-links.html["Verknüpfen Sie eine Verknüpfung"] einen Snapshot erstellen. Wenn Sie noch keinen Link haben, link:create-link.html["Erstellen Sie eine Verknüpfung"]. Um einen Link im Dateisystem zu verknüpfen, klicken Sie unter *Kontoname* auf *Associate Link*. Sobald die Verknüpfung verknüpft ist, kehren Sie zu diesem Vorgang zurück.

.Schritte
. Melden Sie sich bei der Workload Factory-Konsole an.
. Wählen Sie unter *Storage* *zum Lagerbestandsverzeichnis* gehen.
. Klicken Sie auf der Registerkarte *FSX für ONTAP* auf das drei Punkte-Menü des Dateisystems mit dem Volume und wählen Sie dann *Verwalten*.
. Wählen Sie in der Dateisystemübersicht die Registerkarte *Volumes* aus.
. Wählen Sie auf der Registerkarte *Volumes* das Menü mit drei Punkten für das zu schützende Volume aus.
. Wählen Sie *Data Protection actions*, *Snapshots*, dann *Create Volume from a Snapshot*.
. Geben Sie im Dialogfeld Create Volume from a Snapshot im Feld *Snapshot Name* einen Snapshot-Namen ein.
. Klicken Sie Auf *Erstellen*.

