---
sidebar: sidebar 
permalink: delete-svm.html 
keywords: delete storage vm, delete svm, remove svm 
summary: 'Löschen Sie eine Storage-VM (SVM), die Sie nicht mehr benötigen, aus der FSX for ONTAP-Filesystem-Konfiguration.' 
---
= Löschen einer Storage-VM in NetApp Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Löschen Sie eine Storage-VM (SVM), die Sie nicht mehr benötigen, aus der FSX for ONTAP-Filesystem-Konfiguration.

.Bevor Sie beginnen
Überprüfen Sie Folgendes, bevor Sie eine Storage-VM löschen:

* Vergewissern Sie sich, dass keine Applikationen auf die Daten in der SVM zugreifen.
* Löschen Sie alle nicht-Root-Volumes, die mit der SVM verbunden sind.


.Schritte
. Melden Sie sich mit einem der link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["Konsolenerfahrungen"^]an.
. Wählen Sie in der Kachel „Speicher“ die Option „Zum Speicher gehen“ aus.
. Wählen Sie im Speichermenü *FSx für ONTAP* aus.
. Wählen Sie in *FSx for ONTAP* das Aktionsmenü des zu aktualisierenden Dateisystems und dann *Verwalten*.
. Wählen Sie in der Dateisystemübersicht die Registerkarte *Storage VMs* aus.
. Wählen Sie auf der Registerkarte „Storage-VMs“ das Aktionsmenü der Storage-VM aus, für die Sie Active Directory konfigurieren möchten.
. Wählen Sie *Speicher-VM löschen*.
. Geben Sie im Dialogfeld „Storage-VM löschen“ den Befehl „delete“ ein, um die Storage-VM zu löschen.
. Wählen Sie zur Bestätigung *Löschen*.

