---
sidebar: sidebar 
permalink: delete-volume.html 
keywords: delete volume, volume deletion 
summary: Sie können ein Volumen in Ihrem FSX für ONTAP-Dateisystem jederzeit löschen. Dieser Vorgang kann nicht rückgängig gemacht werden. 
---
= Löschen Sie ein Volume in der BlueXP -Workload-Fabrik
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Sie können ein Volumen in Ihrem FSX für ONTAP-Dateisystem jederzeit löschen. Dieser Vorgang kann nicht rückgängig gemacht werden.

.Bevor Sie beginnen
Beachten Sie Folgendes, bevor Sie ein Volume löschen:

* Replikationsbeziehungen: Sie müssen link:delete-replication.html["Löschen Sie alle vorhandenen Replikationsbeziehungen"] für dieses Volume vor dem Löschen des Volumes vorgehen, damit keine unterbrochenen Beziehungen erhalten bleiben.
* Lokale Schnappschüsse: Alle Snapshots, die mit diesem FSX für ONTAP-Dateisystem verbunden sind, werden dauerhaft gelöscht.
* FSX für ONTAP-Backup: FSX für ONTAP-Backup-Kopien werden bleiben und Sie können sie weiterhin verwenden.
* Unveränderliche Dateien: Volumes, die unveränderliche Dateien mit Unterstützung von SnapLock enthalten, können erst nach Ablauf der Aufbewahrungsfrist gelöscht werden.


.Schritte
. Melden Sie sich mit einem der link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["Konsolenerfahrungen"^]an.
. Wählen Sie unter Speicher die Option *Gehe zu Lagerbestandsbestand* aus.
. Wählen Sie auf der Registerkarte *FSX for ONTAP* das drei-Punkt-Menü des Dateisystems mit dem zu löschenden Volume aus und wählen Sie dann *Verwalten*.
. Wählen Sie in der Dateisystemübersicht die Registerkarte *Volumes* aus.
. Wählen Sie auf der Registerkarte Volumes das drei-Punkt-Menü des zu löschenden Volumes aus.
. Wählen Sie *Basic actions* und dann *Delete Volume*.
. Gehen Sie im Dialogfeld Volume löschen wie folgt vor:
+
.. Wählen Sie optional *Backup des Volumes*, um das Volume vor dem Löschen zu sichern.
+
Das Backup bleibt im Dateisystem, bis Sie es manuell löschen.

.. Wählen Sie *Weiter*.
.. Geben Sie „delete“ ein, um das Volume zu löschen.
.. Wählen Sie *Löschen*.



