---
sidebar: sidebar 
permalink: edit-svm-tags.html 
keywords: edit storage vm tags, vm tags, svm tags 
summary: Hinzufügen, Aktualisieren oder Entfernen von Storage-VM-Tags für eine Storage-VM jederzeit. 
---
= Bearbeiten Sie Storage-VM-Tags
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Mit Tags können Sie Ihre Ressourcen kategorisieren. Sie können Tags für eine Storage-VM jederzeit hinzufügen, bearbeiten und entfernen.

.Schritte
. Melden Sie sich bei der Workload Factory-Konsole an.
. Wählen Sie unter Speicher die Option *Gehe zu Lagerbestandsbestand* aus.
. Wählen Sie auf der Registerkarte *FSX for ONTAP* das drei Punkte-Menü des Dateisystems mit der zu aktualisierenden Speicher-VM aus und wählen Sie dann *Verwalten*.
. Wählen Sie in der Dateisystemübersicht die Registerkarte *Storage VMs* aus.
. Wählen Sie auf der Registerkarte Storage VMs das Menü mit den drei Punkten der Storage-VM aus, für die Sie Tags bearbeiten möchten.
. Wählen Sie *Storage VM Tags bearbeiten*.
. Auf der Seite Storage-VM-Tags bearbeiten können Sie Tags hinzufügen, bearbeiten oder entfernen.
+
Auf eine Storage-VM können Sie maximal 50 Tags anwenden.

. Klicken Sie Auf *Anwenden*.

