---
sidebar: sidebar 
permalink: edit-volume-tags.html 
keywords: volume tags, edit volume tags, edit tags 
summary: Mit Tags können Sie Ihre Ressourcen kategorisieren. Sie können Volume-Tags für FSX für ONTAP-Volumes jederzeit hinzufügen, bearbeiten und entfernen. 
---
= Bearbeiten Sie Volume-Tags
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Mit Tags können Sie Ihre Ressourcen kategorisieren. Sie können Volume-Tags für FSX für ONTAP-Volumes jederzeit hinzufügen, bearbeiten und entfernen.

.Schritte
. Melden Sie sich beim an link:https://console.workloads.netapp.com/["Workload Factory-Konsole"^]
. Wählen Sie unter Speicher die Option *Gehe zu Lagerbestandsbestand* aus.
. Wählen Sie auf der Registerkarte *FSX for ONTAP* das drei Punkte-Menü des Dateisystems mit dem zu aktualisierenden Volume aus und wählen Sie dann *Verwalten*.
. Wählen Sie in der Dateisystemübersicht die Registerkarte *Volumes* aus.
. Klicken Sie auf der Registerkarte Volumes auf das Menü drei Punkte für das Volume, für das Tags geändert werden sollen.
. Wählen Sie *Basic actions* und dann *Edit Volume Tags*.
. Fügen Sie auf der Seite Volume-Tags bearbeiten Tags hinzu, bearbeiten oder entfernen Sie Tags.
+
Die maximale Anzahl von Tags, die Sie auf ein Volume anwenden können, beträgt 50.

. Klicken Sie Auf *Anwenden*.

