---
sidebar: sidebar 
permalink: enable-auto-capacity-management.html 
keywords: auto capacity, automatic capacity management, file system capacity 
summary: Durch Aktivieren dieser Funktion kann Workload Factory einem FSx für ONTAP Dateisystem automatisch inkrementellen Speicher hinzufügen, wenn sich der Kapazitätsbedarf im Laufe der Zeit ändert. 
---
= Aktivieren Sie das automatische Kapazitätsmanagement für ein FSX für ONTAP-Filesystem
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Durch die Aktivierung der automatischen Kapazitätsverwaltung kann NetApp Workload Factory einem FSx für ONTAP Dateisystem automatisch inkrementellen Speicher hinzufügen, wenn sich der Kapazitätsbedarf im Laufe der Zeit ändert.  Darüber hinaus entfällt durch die Aktivierung dieser Funktion die Notwendigkeit, die Kapazität manuell zu überwachen, und das Risiko von Lese- und Schreibvorgängen von Anwendungsdaten mit negativen Auswirkungen wird verringert.

.Über diese Aufgabe
Ein Scan des FSX für ONTAP-Dateisystems findet alle 30 Minuten statt, um zu bestimmen, ob inkrementeller Storage hinzugefügt werden muss, und um verfügbare Volume-Inodes oder die maximale Anzahl an Dateien und Ordnern in einem Volume zu prüfen, sodass ihre Anzahl entsprechend den konfigurierten Schwellenwerten für das automatische Kapazitätsmanagement steigt.

Diese Funktion kann nur von einem Konto verwaltet werden.

Die maximale Menge an SSD-Speicherkapazität für alle FSX für ONTAP-Dateisysteme beträgt 524,288 gib. Informationen zur Anforderung einer Quotenerhöhung finden link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/limits.html["Kontingente"^] Sie in der Dokumentation zu AWS FSX for NetApp ONTAP.

.Bevor Sie beginnen
Beachten Sie Folgendes, bevor Sie beginnen:

* Sie müssen über Anmeldeinformationen mit Lese-/Schreibberechtigungen in Workload Factory verfügen, um diese Aufgabe abzuschließen.
* Um sicherzustellen, dass die Volume-Inodes zusammen mit der Speicherkapazität zunehmen, müssen Sie einen Link zuordnen. link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["Erfahren Sie, wie Sie einen vorhandenen Link zuordnen oder einen neuen Link erstellen und zuordnen."]. Kehren Sie nach dem Verknüpfen zu diesem Vorgang zurück.
* Sie sollten diese Funktion während der Datenmigration nicht aktivieren, da AWS zwischen SSD-Kapazitätserhöhungen eine Abkühlphase von mindestens sechs Stunden vorschreibt. Diese Einschränkung kann Anpassungen verzögern. Planen Sie daher entsprechend.


.Schritte
. Melden Sie sich mit einem der link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["Konsolenerfahrungen"^]an.
. Wählen Sie in der Kachel „Speicher“ die Option „Zum Speicher gehen“ aus.
. Wählen Sie im Speichermenü *FSx für ONTAP* aus.
. Wählen Sie unter *FSx for ONTAP* das Aktionsmenü des Dateisystems aus, für das Sie die automatische Kapazitätsverwaltung aktivieren möchten.
. Wählen Sie *Verwalten*.
. Wählen Sie unter Information das Bleistiftsymbol neben *Automatic Capacity Management*. Das Bleistiftsymbol erscheint neben dem Dropdown-Pfeil, wenn die Maus über die Zeile *Automatic Capacity Management* schwebt.
. Geben Sie im Dialogfeld *Automatic Capacity Management* Folgendes an:
+
.. *Zugangsdaten*: Wählen Sie aus dem Dropdown-Menü Zugangsdaten mit _Automate_ Berechtigungen aus.
.. Klicken Sie auf die Schaltfläche Aktivieren, um das automatische Kapazitätsmanagement * zu aktivieren.
+
Alternativ können Sie die Funktion deaktivieren. Wenn Sie die Kapazität des Dateisystems erhöhen müssen, müssen Sie zunächst die automatische Kapazitätsverwaltung deaktivieren.

.. *Schwellenwertsteigerung*: Geben Sie die maximale Größe für das FSX für ONTAP Dateisystem ein.
.. *Incremental Increase*: Geben Sie den Prozentsatz ein, um die Kapazität schrittweise zu erhöhen.
.. Optional: Aktivieren Sie die automatische Inodes-Verwaltung, um sicherzustellen, dass die Dateikapazität pro Volume erhöht wird, indem die Anzahl der Inodes (Dateien) bis zum zulässigen Grenzwert erhöht wird.


. Wählen Sie *Anwenden*.


.Ergebnis
Ein Scan des Filesystems erfolgt alle 30 Minuten, um zu ermitteln, ob das Filesystem zusätzliche Kapazität benötigt.
