---
sidebar: sidebar 
permalink: enable-snapshots-long-term.html 
keywords: snapshot long-term retention, enable long-term retention 
summary: Ändern Sie den Replikationszeitplan des Quell-Volumes in einer Replikationsbeziehung. 
---
= Aktivieren und bearbeiten Sie Snapshots für die langfristige Aufbewahrung
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Mit Hilfe von Snapshots zur langfristigen Aufbewahrung können Sie spezifische Snapshots für langfristige Disaster Recovery replizieren.

Dank der langfristigen Aufbewahrung können Business-Services auch bei einem vollständigen Standortausfall weiterlaufen und Applikationen mithilfe einer sekundären Kopie einen transparenten Failover unterstützen.

Die gleichen Schritte gelten für die Aktivierung und Bearbeitung von Snapshots für die langfristige Aufbewahrung.

.Schritte
. Melden Sie sich bei der Workload Factory-Konsole an.
. Wählen Sie unter Speicher die Option *Gehe zu Lagerbestandsbestand* aus.
. Klicken Sie auf der Registerkarte *FSX für ONTAP* auf das Menü mit drei Punkten des zu aktualisierenden Dateisystems und wählen Sie dann *Verwalten*.
. Wählen Sie in der Dateisystemübersicht die Registerkarte *Replikationsbeziehungen* aus.
. Klicken Sie auf der Registerkarte Replikationsbeziehungen auf das Menü drei Punkte des Zeitplans für die Replikationsbeziehung, der geändert werden soll.
. Wählen Sie *langfristige Aufbewahrung bearbeiten*.
. Aktivieren oder deaktivieren Sie im Dialogfeld „langfristige Aufbewahrung bearbeiten“ Snapshots für die langfristige Aufbewahrung.
. Wenn Sie Snapshots für die langfristige Aufbewahrung deaktivieren möchten, klicken Sie auf *Anwenden*, um diesen Vorgang abzuschließen.
. Wenn Sie Snapshots für die langfristige Aufbewahrung aktivieren, wählen Sie zwischen der Auswahl einer vorhandenen Richtlinie oder dem Erstellen einer neuen Richtlinie.
+
.. Wählen Sie für eine vorhandene Richtlinie eine vorhandene Richtlinie aus dem Dropdown-Menü aus.
.. Um eine neue Richtlinie zu erstellen, geben Sie Folgendes an:
+
... *Richtlinienname*: Geben Sie einen Richtliniennamen ein.
... *Snapshot-Richtlinien*: Wählen Sie eine oder mehrere Snapshot-Richtlinien aus.
... *Zu behaltende Kopien*: Geben Sie die Anzahl der Snapshot-Kopien ein, die auf dem Zieldateisystem aufbewahrt werden sollen.




. Klicken Sie Auf *Anwenden*.

