---
sidebar: sidebar 
permalink: explore-savings.html 
keywords: cost, savings, compare costs, EBS, EFS, FSx for Windows file servers FSx for ONTAP 
summary: 'Entdecken Sie Einsparungen bei Ihren Storage-Workloads – bei EBS-Storage (Amazon Elastic Block Store), Elastic File System (EFS) und FSX für Windows-Dateiserver im Vergleich zu AWS FSX für NetApp ONTAP.' 
---
= Informieren Sie sich über Einsparungen im FSX für ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Erkunden Sie die Einsparmöglichkeiten bei Ihren Storage-Workloads, die Amazon Elastic Block Store (EBS), Elastic File System (EFS) und FSX für Windows File Server gegen FSX für NetApp ONTAP verwenden.

Workload Factory verfügt über einen integrierten Rechner zur Storage-Einsparung, mit dem Sie Ihre Amazon Storage-Umgebungen mit FSX für ONTAP vergleichen können. Sie profitieren von Einsparungen, die mit oder ohne Ihre AWS Zugangsdaten erzielt und die Konfigurationseinstellungen für Ihre Storage-Umgebung angepasst werden können. Wenn Sie AWS Zugangsdaten bereitstellen, können Sie beispielsweise eine oder mehrere Instanzen von Amazon Elastic Block Store auswählen und Workload Factory den Vergleich automatisch durchführen lassen. Ob manuell oder automatisch, der Rechner ermittelt, welcher Storage-Service die niedrigsten Kosten für Ihren Speicherbedarf bietet.

Stellt der Storage-Rechner fest, dass FSX für ONTAP der kostengünstigste Speicher ist, können Sie FSX für ONTAP-Konfigurationen erstellen oder speichern und mit der Codebox Infrastruktur-als-Code-Vorlagen erstellen, unabhängig von den Berechtigungen, die Sie Workload Factory gewähren.



== Berechnungsoptionen

Für den Vergleich der Kosten zwischen Ihren Systemen und FSX for ONTAP stehen zwei Rechner-Optionen zur Verfügung – Anpassung und automatische Erkennung für Ihre Amazon Storage-Umgebungen.

Einsparungen durch Anpassung: Sie stellen die Konfigurationseinstellungen für eine Storage-Umgebung bereit, einschließlich Anwendungsfall, Region, Anzahl von Volumes oder File-Systemen, Storage-Menge, Snapshot-Häufigkeit, geänderter Menge pro Snapshot, bereitgestellter IOPS, Durchsatz und mehr.

Einsparungsmöglichkeiten bei erkannten Storage-Umgebungen: Workload Factory verknüpft Ihre vorhandenen AWS Storage-Umgebungen und stellt den Rechner für automatischen Vergleich mit den Details zur Verfügung. Für die Verwendung des automatischen Modus müssen Sie die Berechtigung Automatisieren erteilen. Sie können den Anwendungsfall ändern, aber alle anderen Details werden automatisch in der Berechnung ermittelt.



== Entdecken Sie Einsparungen durch Anpassung

Führen Sie die Schritte unter der Registerkarte für Ihre Speicherauswahl aus.

[role="tabbed-block"]
====
.Amazon Elastic Block Store (EBS)
--
.Schritte
. Melden Sie sich beim an link:https://console.workloads.netapp.com/["Workload Factory-Konsole"^]
. Wählen Sie unter Speicher *Einsparungen erkunden* und dann *Amazon Elastic Block Store (EBS)* aus.
. Geben Sie im Rechner für Storage-Einsparungen folgende Informationen an:
+
.. *Anwendungsfall*: Erforderlich. Wählen Sie im Dropdown-Menü einen Anwendungsfall aus. Der ausgewählte Anwendungsfall legt die Eigenschaften des Filesystems FSX für ONTAP für den Vergleich fest.
.. *Region*: Optional. Wählen Sie im Dropdown-Menü die Region für Ihre EBS-Konfiguration aus.
.. *Wählen Sie EBS Volume-Typ*: Optional. Wählen Sie den EBS Volume-Typ aus, der für Ihre Konfiguration verwendet wird.
.. *Anzahl der Volumen*: Optional. Geben Sie die Anzahl der Volumes in Ihrer EBS-Konfiguration ein.
.. *Speichermenge pro Volumen (tib)*: Optional. Geben Sie die Storage-Menge pro Volume in tib ein.
.. *Snapshot-Frequenz*: Optional. Wählen Sie die Snapshot-Frequenz für Ihre EBS-Konfiguration aus.
.. *Betrag pro Snapshot geändert (gib)*: Optional. Nur für Snapshot-Speicher. Geben Sie den pro Snapshot geänderten Betrag in gib ein.
.. *Bereitgestellte IOPS pro Volume*: Optional. Für gp3-, io1- und io2-Volumen. Geben Sie die bereitgestellten IOPS pro Volume ein.
.. *Durchsatz (MiB/s)*: Optional. Nur für gp3-Volumes. Geben Sie den Durchsatz in MiB/s pro Volume ein.




--
.Amazon FSX für Windows File Server
--
.Schritte
. Melden Sie sich beim an link:https://console.workloads.netapp.com/["Workload Factory-Konsole"^]
. Wählen Sie unter Speicher * Einsparungen erkunden * und dann * Amazon FSX für Windows File Server *.
. Geben Sie im Rechner für Storage-Einsparungen folgende Informationen an:
+
.. *Anwendungsfall*: Erforderlich. Wählen Sie im Dropdown-Menü einen Anwendungsfall aus. Der ausgewählte Anwendungsfall legt die Eigenschaften des Filesystems FSX für ONTAP für den Vergleich fest.
.. *Region*: Optional. Wählen Sie im Dropdown-Menü die Region für Ihre FSX for Windows File Server-Konfiguration aus.
.. *Deployment-Typ*: Optional. Wählen Sie *einzelne Verfügbarkeitszone* oder *mehrere Verfügbarkeitszonen*.
.. *Speichertyp*: Der SSD-Speichertyp ist standardmäßig ausgewählt.
.. *Speicherkapazität (tib)*: Optional. Geben Sie die Speicherkapazität für die Konfiguration ein.
.. *Deduplizierungseinsparungen (%)*: Optional. Geben Sie den Prozentsatz der zu erwartenden Kapazitätseinsparungen durch die Deduplizierung ein.
.. *Snapshot-Frequenz*: Optional. Wählen Sie die Snapshot-Frequenz für Ihre Konfiguration aus.
.. *Betrag pro Snapshot geändert (gib)*: Optional. Nur für Snapshot-Speicher. Geben Sie den pro Snapshot geänderten Betrag in gib ein.
.. *Bereitgestellte SSD-IOPS*: Optional. Geben Sie die bereitgestellten SSD-IOPS ein.
.. *Durchsatz (MiB/s)*: Optional. Geben Sie den Durchsatz in MiB/s. ein




--
.Amazon Elastic File System (EFS)
--
.Schritte
. Melden Sie sich beim an link:https://console.workloads.netapp.com/["Workload Factory-Konsole"^]
. Wählen Sie unter Speicher *Einsparungen erkunden* und dann *Amazon Elastic File System (EFS)* aus.
. Geben Sie im Rechner für Storage-Einsparungen folgende Informationen an:
+
.. *Anwendungsfall*: Erforderlich. Wählen Sie im Dropdown-Menü einen Anwendungsfall aus. Der ausgewählte Anwendungsfall legt die Eigenschaften des Filesystems FSX für ONTAP für den Vergleich fest.
.. *Region*: Optional. Wählen Sie im Dropdown-Menü die Region für Ihre FSX for Windows File Server-Konfiguration aus.
.. *Dateisystemtyp*: Optional. Wählen Sie *Regional* oder *One Zone*.
.. *Speicherkapazität (tib)*: Optional. Geben Sie die Speicherkapazität der EFS-Konfiguration ein.
.. *Daten, auf die häufig zugegriffen wird (%)*: Optional. Geben Sie den Prozentsatz der Daten ein, auf die häufig zugegriffen wird.
.. *Durchsatzmodus*: Optional. Wählen Sie *bereitgestellter Durchsatz* oder *Elastischer Durchsatz*.
.. *Durchsatz (MiB/s)*: Optional. Geben Sie den Durchsatz in MiB/s. ein




--
====
Nachdem Sie Details zur Konfiguration des Speichersystems angegeben haben, überprüfen Sie die Berechnungen und Empfehlungen auf der Seite.

Scrollen Sie zusätzlich nach unten auf der Seite zu *PDF exportieren* oder *Berechnungen anzeigen*.

Um zu FSX für ONTAP zu wechseln, folgen Sie den Anweisungen zu <<Implementieren von FSX für ONTAP-Dateisysteme,Implementieren von FSX für ONTAP-Dateisysteme>>.



== Entdecken Sie die Einsparungen bei erkannten Speicherumgebungen

.Bevor Sie beginnen
Wenn Workload Factory in Ihrem AWS-Konto Amazon Elastic Block Store (EBS), Elastic File System (EFS) und FSX für Windows File Server-Storage-Umgebungen erkennt, müssen Sie link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["Erteilen _Automatisieren_ Berechtigungen"^] Ihr AWS-Konto angeben.


NOTE: Diese Rechneroption unterstützt keine Berechnungen für EBS-Snapshots und FSX für Windows File Server-Schattenkopien. Wenn Sie die Einsparungen durch die Anpassung untersuchen, können Sie Snapshot-Details zu EBS und FSX für Windows File Server anbieten.

Führen Sie die Schritte unter der Registerkarte für Ihre Speicherauswahl aus.

[role="tabbed-block"]
====
.Amazon Elastic Block Store (EBS)
--
.Schritte
. Melden Sie sich beim an link:https://console.workloads.netapp.com/["Workload Factory-Konsole"^]
. Wählen Sie unter Speicher die Option *Gehe zu Lagerbestandsbestand* aus.
. Wählen Sie im Storage Inventory die Registerkarte *Elastic Block Store (EBS)* aus.
. Wählen Sie die Instanz(en) aus, die mit FSX für ONTAP verglichen werden soll, und klicken Sie auf *Einsparungen erkunden*.
. Der Rechner für Storage-Einsparungen wird angezeigt. Die folgenden Merkmale des Speichersystems werden basierend auf den ausgewählten Instanzen vorausgefüllt:
+
.. *Anwendungsfall*: Der Anwendungsfall für Ihre Konfiguration. Sie können den Anwendungsfall bei Bedarf ändern.
.. *Ausgewählte Volumes*: Die Anzahl der Volumes in der EBS Konfiguration
.. *Gesamtspeichermenge (tib)*: Die Speichermenge pro Volume in tib
.. *Insgesamt bereitgestellte IOPS*: Für gp3-, io1- und io2-Volumes
.. *Gesamtdurchsatz (MiB/s)*: Nur für gp3-Volumes




--
.Amazon FSX für Windows File Server
--
.Schritte
. Melden Sie sich beim an link:https://console.workloads.netapp.com/["Workload Factory-Konsole"^]
. Wählen Sie unter Speicher die Option *Gehe zu Lagerbestandsbestand* aus.
. Wählen Sie im Speicher-Inventar die Registerkarte * FSX für Windows-Dateiserver* aus.
. Wählen Sie die Instanz(en) aus, die mit FSX für ONTAP verglichen werden soll, und klicken Sie auf *Einsparungen erkunden*.
. Der Rechner für Storage-Einsparungen wird angezeigt. Die folgenden Merkmale des Speichersystems werden basierend auf dem Bereitstellungstyp der ausgewählten Instanz(en) vorausgefüllt:
+
.. *Anwendungsfall*: Der Anwendungsfall für Ihre Konfiguration. Sie können den Anwendungsfall bei Bedarf ändern.
.. *Ausgewählte Dateisysteme
.. *Gesamtspeichermenge (tib)*
.. *Bereitgestellte SSD-IOPS*
.. *Durchsatz (MiB/s)*




--
.Amazon Elastic File System (EFS)
--
.Schritte
. Melden Sie sich beim an link:https://console.workloads.netapp.com/["Workload Factory-Konsole"^]
. Wählen Sie unter Speicher die Option *Gehe zu Lagerbestandsbestand* aus.
. Wählen Sie in der Lagerbestandsliste die Registerkarte *Elastic File System (EFS)* aus.
. Wählen Sie die Instanz(en) aus, die mit FSX für ONTAP verglichen werden soll, und klicken Sie auf *Einsparungen erkunden*.
. Der Rechner für Storage-Einsparungen wird angezeigt. Die folgenden Merkmale des Speichersystems werden basierend auf den ausgewählten Instanzen vorausgefüllt:
+
.. *Anwendungsfall*: Der Anwendungsfall für Ihre Konfiguration. Sie können den Anwendungsfall bei Bedarf ändern.
.. *Gesamte Dateisysteme*
.. *Gesamtspeichermenge (tib)*
.. *Gesamtbereitgestellter Durchsatz (MiB/s)*
.. *Gesamtelastischer Durchsatz - Lesen (gib)*
.. *Gesamtelastischer Durchsatz – Schreiben (gib)*




--
====
Nachdem Sie Details zur Konfiguration des Speichersystems angegeben haben, überprüfen Sie die Berechnungen und Empfehlungen auf der Seite.

Scrollen Sie zusätzlich nach unten auf der Seite zu *PDF exportieren* oder *Berechnungen anzeigen*.



== Implementieren von FSX für ONTAP-Dateisysteme

Wenn Sie zu FSX für ONTAP wechseln möchten, um Kosteneinsparungen zu erzielen, klicken Sie auf *Erstellen*, um das Dateisystem direkt aus dem Assistenten zum Erstellen eines FSX für ONTAP-Dateisystems zu erstellen, oder klicken Sie auf *Speichern*, um die empfohlenen Konfigurationen für später zu speichern.

Bereitstellungsmethoden:: Im _Automate_-Modus können Sie das Dateisystem FSX für ONTAP direkt aus Workload Factory bereitstellen. Sie können den Inhalt auch aus dem Codebox-Fenster kopieren und das System mit einer der Codebox-Methoden bereitstellen.
+
--
Im _BASIC_-Modus können Sie den Inhalt aus dem Codebox-Fenster kopieren und das Dateisystem FSX for ONTAP mit einer der Codebox-Methoden bereitstellen.

--

