---
sidebar: sidebar 
permalink: improve-configurations.html 
keywords: implement best practices, well-architected file system, Amazon FSx for NetApp ONTAP, FSx for ONTAP 
summary: Die BlueXP  Workload-Farm für Datenbanken scannt Microsoft SQL Server-Konfigurationen und bietet Ihnen Einblicke und Empfehlungen, um Ihre betrieblichen Abläufe zu optimieren. 
---
= Sorgfältig konzipierte Filesystem-Konfigurationen implementieren
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Nutzen Sie die Erkenntnisse und Empfehlungen der Konfigurationsanalyse und implementieren Sie Best Practices für Ihre FSx for ONTAP Dateisysteme mithilfe der Workload Factory. Sie können den Status der ordnungsgemäßen Architektur problemlos überprüfen, sich über Probleme mit Ihren Konfigurationen informieren und Maßnahmen ergreifen, um die Architektur von Systemen zu verbessern, die nicht hinsichtlich Zuverlässigkeit, Sicherheit, Effizienz, Leistung und Kosten optimiert sind.

link:configuration-analysis.html["Erfahren Sie mehr über die Konfigurationsanalyse und den Status einer guten Architektur in der Workload Factory."]

.Über diese Aufgabe
Workload Factory analysiert täglich die Konfigurationen der Amazon FSx for NetApp ONTAP Dateisysteme. Die tägliche Analyse liefert den Status der ordnungsgemäßen Architektur sowie Einblicke und Empfehlungen mit Optionen zur automatischen Behebung von Konfigurationsproblemen, damit Ihr Dateisystem Best Practices entspricht.

Sie haben die Möglichkeit, die Empfehlungen für Konfigurationsprobleme mit Ihren Dateisystemen zu überprüfen und die Probleme aus dem Speicherinventar in der Workload Factory-Konsole zu beheben.

Was analysiert wird:: Die Workload-Farm analysiert den gut konzipierten Status der folgenden Konfigurationen für die File-Systeme FSX for ONTAP:
+
--
* Schwellenwert für SSD-Kapazität
* Daten-Tiering
* Geplante lokale Snapshots
* FSx für ONTAP-Backups
* Remote-Datenreplizierung
* Storage-Effizienz
* Automatisches Kapazitätsmanagement


--


.Bevor Sie beginnen
* Sie müssen über Anmeldeinformationen mit Nur-Lese- oder Lese-/Schreibberechtigung verfügen. link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["Erfahren Sie, wie Sie in Ihrem AWS-Konto Berechtigungen erteilen"^].
* Überprüfen Sie jede Empfehlung sorgfältig, bevor Sie eine Einstellung oder Konfiguration korrigieren.



NOTE: Die Problembehebung kann zu Ausfallzeiten von Instanzen oder Serviceunterbrechungen führen. Überprüfen Sie die Empfehlung sorgfältig, bevor Sie ein Konfigurationsproblem beheben.

.Schritte
. Melden Sie sich mit einem der link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["Konsolenerfahrungen"^]an.
. Wählen Sie in der Kachel Datenbanken *Gehe zu Speicherbestand* aus.
. Navigieren Sie auf der Registerkarte *FSX für ONTAP* zur Spalte *gut gestaltter Status* und wählen Sie die Probleme aus, die das Dateisystem beheben soll.
. Filtern Sie im gut konzipierten Dashboard für das Filesystem Konfigurationsprobleme nach Kategorien, Unterkategorien, Status, Schweregrad und Tags.
. Wählen Sie den Dropdown-Pfeil aus, um die Empfehlung für eine beliebige Konfiguration anzuzeigen. Überprüfen Sie die Empfehlung sorgfältig.
+
Die Empfehlung erläutert Best Practices und potenzielle Fallstricke bei nicht optimierten Konfigurationen.

. Wählen Sie *Fix*.
+
Wenn *View and fix* eine Option ist, wählen Sie die betroffenen Volumes aus, die repariert werden sollen.

. Sehen Sie sich die im Dialogfeld angezeigten Zusammenfassungs- und Aktionselemente an, um zu erfahren, was passieren wird, wenn Sie das Problem beheben möchten. Einige Vorgänge können zu Instanzausfällen oder Serviceunterbrechungen führen.
. Wählen Sie *Weiter*, um das Konfigurationsproblem zu beheben.


.Ergebnis
Der Prozess zur Behebung des Problems wird eingeleitet. Wählen Sie das Menü „Kontoeinstellungen“ und dann „Tracker“ aus, um den Status des Vorgangs anzuzeigen.
