---
sidebar: sidebar 
permalink: improve-configurations.html 
keywords: implement best practices, well-architected file system, Amazon FSx for NetApp ONTAP, FSx for ONTAP 
summary: Workload Factory durchsucht Amazon FSx for NetApp ONTAP -Konfigurationen und liefert Erkenntnisse und Empfehlungen, die Ihnen dabei helfen, betriebliche Höchstleistungen zu erzielen. 
---
= Sorgfältig konzipierte Filesystem-Konfigurationen implementieren
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Nutzen Sie die Erkenntnisse und Empfehlungen der Konfigurationsanalyse und nutzen Sie Workload Factory, um Best Practices für Ihre FSx for ONTAP Dateisysteme zu implementieren. Sie können den Status der ordnungsgemäßen Architektur problemlos überprüfen, sich über Probleme mit Ihren Konfigurationen informieren und Maßnahmen ergreifen, um die Architektur aller Systeme zu verbessern, die nicht hinsichtlich Zuverlässigkeit, Sicherheit, Effizienz, Leistung und Kosten optimiert sind.

Sie können die Analyse bestimmter Speicherkonfigurationen, die nicht auf Ihre Speicherumgebung zutreffen, auch ablehnen, um unnötige Warnungen und ungenaue Optimierungsergebnisse zu vermeiden.

link:configuration-analysis.html["Erfahren Sie mehr über die Konfigurationsanalyse und den Status „Well-Architected“ in Workload Factory."]

.Über diese Aufgabe
Workload Factory analysiert täglich die Konfigurationen der Amazon FSx for NetApp ONTAP Dateisysteme. Die tägliche Analyse liefert den Status der ordnungsgemäßen Architektur sowie Einblicke und Empfehlungen mit Optionen zur automatischen Behebung von Konfigurationsproblemen, damit Ihr Dateisystem Best Practices entspricht.

Durch die Link-Konnektivität kann Workload Factory nach Problemen mit Leistung, Datenschutz und Konfigurationen suchen. link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["Stellen Sie über einen Link eine Verbindung zu einem FSx for ONTAP -Dateisystem her"] für die umfassendste Analyse Ihrer Dateisystemressourcen.

Sie haben die Möglichkeit, die Empfehlungen für Konfigurationsprobleme mit Ihren Dateisystemen zu überprüfen und die Probleme vom Speicher aus in der Workload Factory-Konsole zu beheben.

Da die Anforderungen an Speicherkonfigurationen unterschiedlich sind, können Sie die Analyse bestimmter Konfigurationen, die nicht auf Ihre Speicherumgebung zutreffen, verwerfen.  Dadurch vermeiden Sie unnötige Warnmeldungen und ungenaue Optimierungsergebnisse.  Wenn eine bestimmte Konfigurationsanalyse verworfen wird, wird die Konfiguration nicht in die Gesamtpunktzahl der Optimierung einbezogen.

.Was analysiert wird
Die Workload-Farm analysiert den gut konzipierten Status der folgenden Konfigurationen für die File-Systeme FSX for ONTAP:

* Zuverlässigkeit: SSD-Kapazitätsschwelle, geplante lokale Snapshots, FSx für ONTAP Backups, Remote-Datenreplikation und Datenzuverlässigkeit für die langfristige Aufbewahrung
* Sicherheit: NetApp Autonomous Ransomware Protection mit KI (ARP/AI) und Schutz vor unberechtigtem Zugriff auf Volumes
* Operative Exzellenz: automatisches Kapazitätsmanagement, Schwellenwert für die Auslastung der Datenvolumenkapazität und nahezu vollständige Auslastung des Datenvolumens
* Kostenoptimierung: Speichereffizienz und Daten-Tiering




== Beheben eines Konfigurationsproblems

Sie können Konfigurationsprobleme für ein FSx for ONTAP Dateisystem oder für ausgewählte Volumes in einem Dateisystem beheben.  Sie können eine oder mehrere zu reparierende Konfigurationen auswählen.

.Bevor Sie beginnen
* Du musstlink:link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["Berechtigungen für Operationen und Behebung gewähren"^] in Ihrem AWS-Konto.
* Der Behebungsprozess kann zu Instanzausfallzeiten oder Dienstunterbrechungen führen. Stellen Sie sicher, dass Sie jede Empfehlung sorgfältig prüfen, bevor Sie sich für die Behebung eines Konfigurationsproblems entscheiden.
* link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["Stellen Sie über einen Link eine Verbindung zu einem FSx for ONTAP -Dateisystem her"]für die umfassendste Analyse Ihrer Dateisystemressourcen.


.Schritte
. Melden Sie sich mit einem der link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["Konsolenerfahrungen"^]an.
. Wählen Sie in der Kachel „Speicher“ die Option „Zum Speicher gehen“ aus.
. Wählen Sie im Speichermenü *FSx für ONTAP* aus.
. Wählen Sie in *FSx for ONTAP* das Aktionsmenü des zu aktualisierenden Dateisystems und dann *Verwalten*.
. Navigieren Sie von der FSx for ONTAP Dateisystemübersicht zur Registerkarte *Gut konzipierter Status*.
. Filtern Sie Konfigurationsprobleme optional nach Kategorien, Unterkategorien, Status, Schweregrad und Tags.
. Wählen Sie für jede Konfiguration *Empfehlung anzeigen*.  Lesen Sie die Empfehlung sorgfältig durch.
+
Die Empfehlung erläutert Best Practices und potenzielle Fallstricke bei nicht optimierten Konfigurationen.

. Wählen Sie *Fix*.
+
Wenn *View and fix* eine Option ist, wählen Sie die betroffenen Volumes aus, die repariert werden sollen.

. Sehen Sie sich die im Dialogfeld angezeigten Zusammenfassungs- und Aktionselemente an, um zu erfahren, was passieren wird, wenn Sie das Problem beheben möchten. Einige Vorgänge können zu Instanzausfällen oder Serviceunterbrechungen führen.
. Wählen Sie *Weiter*, um das Konfigurationsproblem zu beheben.


.Ergebnis
Der Prozess zur Behebung des Problems wird eingeleitet. Wählen Sie das Menü „Kontoeinstellungen“ und dann „Tracker“ aus, um den Status des Vorgangs anzuzeigen.



== Verwerfen einer Konfigurationsanalyse

Verwerfen, um eine Konfigurationsanalyse für ein FSx for ONTAP Dateisystem oder für ausgewählte Volumes in einem Dateisystem auf unbestimmte Zeit zu stoppen.  Sie können die Analyse bei Bedarf neu starten.

[role="tabbed-block"]
====
.Eine Konfigurationsanalyse für ein Dateisystem verwerfen
--
Verwerfen, um eine Konfigurationsanalyse für ein FSx for ONTAP Dateisystem auf unbestimmte Zeit zu stoppen.  Sie können die Analyse bei Bedarf neu starten.

.Schritte
. Melden Sie sich mit einem der link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["Konsolenerfahrungen"^]an.
. Wählen Sie in der Kachel „Speicher“ die Option „Zum Speicher gehen“ aus.
. Wählen Sie im Speichermenü *FSx für ONTAP* aus.
. Wählen Sie in *FSx for ONTAP* das Aktionsmenü des Dateisystems und dann *Verwalten*.
. Navigieren Sie von der FSx for ONTAP Dateisystemübersicht zur Registerkarte *Gut konzipierter Status*.
. Identifizieren Sie unter *Konfigurationen* die Konfiguration, die Sie verwerfen möchten, und wählen Sie *Verwerfen* aus.
. Wählen Sie *Ablehnen*, um die Analyse für die Konfiguration zu beenden.


--
.Verwerfen einer Konfigurationsanalyse für ein Volume
--
.Schritte
. Melden Sie sich mit einem der link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["Konsolenerfahrungen"^]an.
. Wählen Sie in der Kachel „Speicher“ die Option „Zum Speicher gehen“ aus.
. Wählen Sie im Speichermenü *FSx für ONTAP* aus.
. Wählen Sie in *FSx for ONTAP* das Aktionsmenü des Dateisystems und dann *Verwalten*.
. Navigieren Sie von der FSx for ONTAP Dateisystemübersicht zur Registerkarte *Gut konzipierter Status*.
. Identifizieren Sie unter *Konfigurationen* die Konfiguration, die für ausgewählte Volumes verworfen werden soll, und wählen Sie *Anzeigen und reparieren* aus.
. Identifizieren Sie die Volumes, die aus der Konfigurationsanalyse ausgeschlossen werden sollen.
+
** Für ein Volume: Wählen Sie das Aktionsmenü und dann *Volume schließen*.
** Für mehrere Volumes: Wählen Sie die Volumes aus und wählen Sie dann neben „Massenaktion“ die Option „Verwerfen“.


. Wählen Sie *Ablehnen*, um die Analyse für die Konfiguration zu beenden.
. Wählen Sie im Dialogfeld „Volumes verwerfen“ zur Bestätigung *Verwerfen* aus.


--
====
.Ergebnis
Die Konfigurationsanalyse wird für das Dateisystem oder ausgewählte Volumes gestoppt.

Sie können die Analyse jederzeit wieder aktivieren.  Die Konfiguration wird nicht mehr in die Gesamtpunktzahl der Optimierung einbezogen.



== Eine verworfene Konfigurationsanalyse reaktivieren

Sie können eine abgebrochene Konfigurationsanalyse jederzeit wieder aktivieren.  Sie können eine oder mehrere Konfigurationen zur Reaktivierung auswählen.

[role="tabbed-block"]
====
.Reaktivieren einer Konfigurationsanalyse für ein Dateisystem
--
.Schritte
. Melden Sie sich mit einem der link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["Konsolenerfahrungen"^]an.
. Wählen Sie in der Kachel „Speicher“ die Option „Zum Speicher gehen“ aus.
. Wählen Sie im Speichermenü *FSx für ONTAP* aus.
. Wählen Sie in *FSx for ONTAP* das Aktionsmenü des Dateisystems und dann *Verwalten*.
. Navigieren Sie von der FSx for ONTAP Dateisystemübersicht zur Registerkarte *Gut konzipierter Status*.
. Wählen Sie neben *Konfigurationen* die Option *Abgelehnte Konfigurationen* aus.
. Identifizieren Sie die Konfiguration, die Sie reaktivieren möchten, und wählen Sie *Reaktivieren*.


--
.Reaktivieren einer Konfigurationsanalyse für ein Volume
--
.Schritte
. Melden Sie sich mit einem der link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["Konsolenerfahrungen"^]an.
. Wählen Sie in der Kachel „Speicher“ die Option „Zum Speicher gehen“ aus.
. Wählen Sie im Speichermenü *FSx für ONTAP* aus.
. Wählen Sie in *FSx for ONTAP* das Aktionsmenü des Dateisystems und dann *Verwalten*.
. Navigieren Sie von der FSx for ONTAP Dateisystemübersicht zur Registerkarte *Gut konzipierter Status*.
. Identifizieren Sie unter *Konfigurationen* die Konfiguration, die für ausgewählte Volumes reaktiviert werden soll, und wählen Sie *Anzeigen und reparieren* aus.
. Identifizieren Sie die Volumes, die anhand der Konfigurationsanalyse reaktiviert werden sollen.
+
** Für ein Volume: Wählen Sie das Aktionsmenü und dann *Volume reaktivieren*.
** Für mehrere Volumes: Wählen Sie die Volumes aus und wählen Sie dann neben Massenaktion die Option *Reaktivieren*.




--
====
.Ergebnis
Die Konfigurationsanalyse wird wieder aktiviert.  Täglich erfolgt eine neue Analyse.
