---
sidebar: sidebar 
permalink: increase-file-system-capacity.html 
keywords: adjust capacity, elastic file system capacity, increase file system capacity, increase FSx capacity, decrease file system capacity, decrease FSx capacity 
summary: Passen Sie die SSD-Speicherkapazität eines FSx for ONTAP -Dateisystems manuell an, um die Anforderungen Ihrer projektbasierten Workloads mit unterschiedlichen aktiven Arbeitssätzen zu erfüllen. 
---
= Passen Sie die Dateisystemkapazität in der Workload Factory an
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Passen Sie die Speicherkapazität des Solid-State-Laufwerks (SSD) eines FSx for ONTAP Dateisystems manuell an, um die Anforderungen Ihrer projektbasierten Workloads mit unterschiedlichen aktiven Arbeitssätzen zu erfüllen.

Erhöhen Sie die SSD-Speicherkapazität eines FSx for ONTAP -Dateisystems, wenn die Menge der verwendeten SSD-Speicherkapazität einen von Ihnen angegebenen Schwellenwert überschreitet, oder verringern Sie die SSD-Speicherkapazität, wenn Arbeitssätze inaktiv sind, um die Kosteneffizienz zu verbessern.

Alternativ können Sie link:enable-auto-capacity-management.html["Aktivieren Sie die automatische Kapazitätsverwaltungsfunktion"]mit so Workload Factory die Dateisystemkapazität für Sie verwalten.

.Über diese Aufgabe
Mit der elastischen Dateisystemkapazität können Sie die Kapazität Ihrer Dateisysteme dynamisch an die Anforderungen Ihrer Arbeitslasten anpassen.

Das Anpassen der Dateisystemkapazität wirkt sich auf die IOPS Ihres FSx for ONTAP Dateisystems aus.

Wenn Sie automatischlink:provision-iops.html["Bereitstellung von IOPS"] Bei einem Dateisystem erhöhen oder verringern sich die IOPS um 3 IOPS, wenn die SSD-Kapazität um 1 GiB erhöht oder verringert wird.

Wenn Sie link:provision-iops.html["Bereitstellung von IOPS"] manuell arbeiten, müssen Sie möglicherweise die IOPS-Zuweisung erhöhen, um die höhere Kapazität des Filesystems zu unterstützen.

Weitere Informationen zu SSD-Storage-Kapazitätsbeschränkungen finden Sie link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/limits.html["Kontingente"^] in der Dokumentation zu AWS FSX für NetApp ONTAP.

.Bevor Sie beginnen
Um die Kapazität eines Dateisystems anzupassen, müssen Sie zunächstlink:enable-auto-capacity-management.html["Deaktivieren Sie das automatische Kapazitätsmanagement"] .

.Schritte
. Melden Sie sich mit einem der link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["Konsolenerfahrungen"^]an.
. Wählen Sie unter Speicher die Option *Gehe zu Lagerbestandsbestand* aus.
. Wählen Sie im Dashboard *SSD-Kapazität anpassen*.
. Wählen Sie das Dateisystem aus, für das Sie die Kapazität anpassen möchten, und wählen Sie dann *Weiter*.
+
*Einsparpotenzial* ist die Empfehlung zur Kapazitätsreduzierung.

. Geben Sie im Dialogfeld „SSD-Kapazität anpassen“ eine Zahl für „Bereitgestellte Kapazität“ ein.
. Wählen Sie die Einheit für die bereitgestellte Kapazität aus.
. Wählen Sie *Anwenden*.

