---
sidebar: sidebar 
permalink: increase-volume-capacity.html 
keywords: increase capacity, volume capacity 
summary: Erhöhen Sie die Volume-Kapazität eines Volumes in NetApp Workload Factory jederzeit manuell. 
---
= Erhöhen Sie die Volume-Kapazität in NetApp Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Erhöhen Sie die Volume-Kapazität eines Volumes jederzeit manuell in NetApp Workload Factory.

Optional können Sielink:edit-volume-autogrow.html["Aktivieren Sie die Autogrow Funktion"] damit Workload Factory die Volume-Kapazität für Sie verwalten kann.

.Über diese Aufgabe
Bei einer iSCSI-LUN erhöht dieser Vorgang die Größe der Host-LUN. Nachdem die Kapazität erhöht wurde, befolgen Sie das Verfahren Ihres Host-Betriebssystems, um die neue Größe der LUN zu ermitteln und das Dateisystem der LUN zu erweitern.

.Bevor Sie beginnen
Um die Volumenkapazität zu erhöhen, müssen Sie einen Link zuordnen. link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["Erfahren Sie, wie Sie einen vorhandenen Link zuordnen oder einen neuen Link erstellen und zuordnen."]. Kehren Sie nach dem Verknüpfen zu diesem Vorgang zurück.

.Schritte
. Melden Sie sich mit einem der link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["Konsolenerfahrungen"^]an.
. Wählen Sie in der Kachel „Speicher“ die Option „Zum Speicher gehen“ aus.
. Wählen Sie im Speichermenü *FSx für ONTAP* aus.
. Wählen Sie in *FSx for ONTAP* das Aktionsmenü des Dateisystems mit dem zu aktualisierenden Volume und wählen Sie dann *Verwalten*.
. Wählen Sie in der Dateisystemübersicht die Registerkarte *Volumes* aus.
. Wählen Sie auf der Registerkarte „Volumes“ das Aktionsmenü des Volumes aus, für das Sie die Kapazität erhöhen möchten.
. Wählen Sie *Basic actions* und dann *Erhöhen Sie die Volumenkapazität*.
. Geben Sie im Dialogfeld „Kapazität erhöhen“ Folgendes an:
+
.. Wählen Sie eine größere Größe.
.. Tauschen Sie das Gerät bei Bedarf aus.


. Wählen Sie *Erhöhen*, um die Änderung anzuwenden.

