---
sidebar: sidebar 
permalink: known-limitations.html 
keywords: limitations, fsx, ontap 
summary: Bekannte Einschränkungen identifizieren Plattformen, Geräte oder Funktionen, die von dieser Version des Produkts nicht unterstützt werden oder nicht korrekt mit dem Produkt zusammenarbeiten. 
---
= Bekannte Einschränkungen von Amazon FSX for NetApp ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Bekannte Einschränkungen identifizieren Plattformen, Geräte oder Funktionen, die von dieser Version des Produkts nicht unterstützt werden oder nicht korrekt mit dem Produkt zusammenarbeiten. Lesen Sie diese Einschränkungen sorgfältig durch.



== Für erweiterte ONTAP-Vorgänge ist eine Verbindung erforderlich

Für einige Vorgänge wie die Replikation in der werkseitigen Benutzeroberfläche des Workloads ist ein Link erforderlich.



== Einschränkungen bei HA-Paaren

* Dieser Vorgang kann etwa 30 Minuten dauern.
* Durch das Hinzufügen von HA-Paaren sind folgende Vorgänge beschränkt: Mehr HA-Paare hinzufügen, IOPS-Ressourcen bereitstellen, die SSD-Kapazität erhöhen und die Durchsatzkapazität aktualisieren.




== Unterstützung für Durchsatzkapazität in Regionen



=== Vertikal skalierbare Implementierungen

Scale-up-Konfigurationen werden in allen Regionen bis zu 2 Gbit/s unterstützt. Die folgenden Regionen unterstützen eine maximale Durchsatzkapazität von bis zu 4 Gbit/s für Scale-up-Bereitstellungen: Region US East (Ohio), Region US East (N. Virginia), Region US West (Oregon) und Europa (Irland).



=== Horizontal skalierbare Implementierungen

Die folgenden Regionen unterstützen eine maximale Durchsatzkapazität von bis zu 3 und 6 Gbit/s für Scale-out-Implementierungen: US East (N. Virginia), US East (Ohio), US West (Oregon), Europe (Ireland) und Asia Pacific (Sydney).



== Kapazitätsmanagement

* Die Volume Autogrow-Funktion wird derzeit für das iSCSI-Protokoll nicht unterstützt.
* Wenn die automatische Kapazitätsverwaltungsfunktion ausgeführt wird, ist eine manuelle Kapazitätserhöhung nicht zulässig.
* Das Deaktivieren der automatischen Kapazitätsverwaltungsfunktion ist nur mit denselben Berechtigungen möglich, die zur Aktivierung verwendet wurden.




== Storage-VMs

Die Anzahl der Storage-VMs ist pro SKU begrenzt. In der Workload-Fabrik wird nicht unterstützt, Storage-VMs über die Begrenzung hinaus zu erstellen.^1^

link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/managing-svms.html#max-svms["Management von FSX für ONTAP Storage Virtual Machines"^]In der AWS-Dokumentation finden Sie Informationen zur maximalen Anzahl von SVMs pro Filesystem.



== ISCSI-Protokoll unterstützt

* Das iSCSI-Protokoll ist nur für FlexVol-Volumes verfügbar. ^1^
* Es kann nur eine einzelne LUN pro Volume konfiguriert werden.




== Datensicherung

* Snapshots können nicht gelöscht werden.
* Wenn Sie ein Dateisystem replizieren, verwenden alle Volumes im Dateisystem dieselbe Replikationsrichtlinie.
* Bei Replikationsbeziehungen mit langfristiger Aufbewahrung ist nur der letzte Snapshot für die Wiederherstellung verfügbar.
* Die folgenden Funktionen werden bei unveränderlichen Snapshots nicht unterstützt:
+
** Konsistenzgruppen
** FabricPool
** FlexCache Volumes
** SMTape
** SnapMirror Active Sync
** SnapMirror-Richtlinie, die den Parameter -schedule verwendet
** SnapMirror Synchronous
** SVM-Datenmobilität (verwendet für die Migration oder Verschiebung einer SVM von einem Quell-Cluster zu einem Ziel-Cluster)






== Rechner für Storage-Einsparungen

Der Rechner für Storage-Einsparungen berechnet die Kosteneinsparungen für die folgenden Konfigurationen nicht:

* FSX für Windows File Server: HDD Storage-Typ
* Elastic Block Store (EBS): st1-, sc1- und Standard-Volume-Typen
* Elastic File System (EFS): Bursting-Durchsatzmodus




== System Manager

System Manager unterstützt keine Links für FSX for ONTAP-Konnektivität.

Hinweis:

. Gilt für Amazon FSX for NetApp ONTAP

