---
sidebar: sidebar 
permalink: learn-fsx-ontap.html 
keywords: Amazon FSx for NetApp ONTAP, FSx, storage, aws 
summary: Amazon FSx for NetApp ONTAP ist ein vollständig verwalteter Service, der es Kunden ermöglicht, Dateisysteme als Speicher-Backend für Ihre Workloads innerhalb von Workload Factory zu starten und auszuführen. 
---
= Erfahren Sie mehr über Amazon FSx for NetApp ONTAP in NetApp Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Amazon FSx for NetApp ONTAP ist ein vollständig verwalteter, Cloud-basierter Datenspeicherdienst, der erweiterte Datenverwaltungsfunktionen und hochgradig skalierbare Leistung bietet.  Mit FSx für ONTAP können Sie Dateisysteme als Speicher-Backend für alle Ihre Workloads innerhalb der NetApp Workload Factory erstellen und verwalten.

FSX für ONTAP bietet dieselben Funktionen, Performance und Managementfunktionen, die NetApp Kunden heute vor Ort nutzen. Außerdem bietet sie die Einfachheit, Agilität, Sicherheit und Skalierbarkeit eines nativen AWS Service.

FSx für ONTAP ist die _Storage_-Komponente in Workload Factory.



== Funktionen

FSX für ONTAP bietet folgende Funktionen:

* *Vollständig verwalteter Dienst*: Bietet einen vollständig verwalteten Dienst, der in die Workload Factory-Konsole integriert ist.
* *Hohe Verfügbarkeit*: Bietet Hochverfügbarkeit für jedes FSX für ONTAP-Dateisystem, unterstützt einzelne und mehrere Verfügbarkeitszonen-Bereitstellungen.
* *Automatisierte Snapshots*: Sichert Daten mit automatisierten, effizienten Snapshots, die nahezu sofortige, platzsparende und schreibgeschützte Point-in-Time-Kopien des Dateisystems oder der Volumes sind.
* *Volume-Replikation*: Bietet Disaster Recovery mit regionsübergreifender Replikation über Amazon Web Services.
* *Effiziente Backups*: Fügt eine zusätzliche Schutzschicht mit einer Kopie der Daten in einer anderen Region für Notfälle hinzu.
* *Fast Cloning*: Beschleunigt die Applikationsentwicklung durch schnelles Klonen.
* * Multi-Protokoll-Unterstützung*: Unterstützt Network File System (NFS), Server Message Block (SMB) und Internet Small Computer Systems Interface (iSCSI) Protokolle.
* *Hoher Durchsatz*: Bietet hohe Durchsatz-Performance, um niedrige Latenzen für Workloads zu gewährleisten, die auf FSX for ONTAP-Dateisystemen ausgeführt werden.
* *In-Memory-Cache und NVMe-Cache*: Umfasst einen einzigartigen in-Memory-Cache und NVMe-Cache, der die Performance häufig genutzter Daten steigert.
* *Hunderttausende IOPS*: Stellt hunderttausende IOPS mit SSD-Festplatten bereit, um sicherzustellen, dass Ihre Speicher und Workloads rechtzeitig Ergebnisse erhalten.
* *Thin Provisioning*: Ermöglicht die Bereitstellung von Kapazitäten im Voraus und spart so lange Kosten, bis mehr Kapazität benötigt wird.
* *Datendeduplizierung und -Komprimierung*: Entfernt doppelte Daten und komprimiert Daten, um die Menge an physischem Storage zu reduzieren, der für FSX für ONTAP-Dateisysteme erforderlich ist, was zu Kosteneinsparungen führt.
* *Data Tiering*: Reduziert die Speicherkosten, indem weniger häufig verwendete Daten vom primären SSD-Storage-Tier mit hoher Performance auf die Storage-Tier mit dem sekundären Kapazitäts-Pool verschoben werden.




== Zusätzliche Funktionen in Workload Factory

* *Storage-Kostenvergleich*: Vergleicht die Storage-Kosten für Windows File Server mit FSX für ONTAP mit Amazon Elastic Block Store (EBS), Elastic File System (EFS) und FSX für Windows File Server. Über den Rechner erfahren Sie, wie FSX für ONTAP Storage-Konfigurationen potenzielle Einsparungen ermöglichen und Ihren Wechsel zu FSX für ONTAP Storage planen.
* *Workload Factory Benutzeroberfläche*: Bietet _Quick create_ und _Advanced create_ Bereitstellungsmodus Optionen. Schnelle Erstellung: Best Practices für Ihre Storage-Konfigurationen für AWS, NetApp und Branchenstandards
* *Codebox*: Bietet Entwicklern einen Code-Viewer für FSX für ONTAP-Operationen, Codevorlagen für Kopieren und Herunterladen sowie einen Automatisierungsskatalog für die Wiederverwendung von Code.




== Tools zur Verwendung von NetApp Workload Factory

Sie können NetApp Workload Factory mit den folgenden Tools verwenden:

* *Workload Factory-Konsole*: Die Workload Factory-Konsole bietet eine visuelle, ganzheitliche Ansicht Ihrer Anwendungen und Projekte.
* * NetApp Konsole*: Die NetApp Konsole bietet eine hybride Benutzeroberfläche, sodass Sie Workload Factory zusammen mit anderen NetApp -Datendiensten verwenden können.
* *Fragen Sie mich*: Verwenden Sie den KI-Assistenten „Fragen Sie mich“, um Fragen zu stellen und mehr über Workload Factory zu erfahren, ohne die Workload Factory-Konsole zu verlassen. Greifen Sie über das Hilfemenü von Workload Factory auf „Fragen Sie mich“ zu.
* *CloudShell CLI*: Workload Factory enthält eine CloudShell CLI zum Verwalten und Betreiben von AWS- und NetApp -Umgebungen über Konten hinweg von einer einzigen, browserbasierten CLI aus. Greifen Sie über die obere Leiste der Workload Factory-Konsole auf CloudShell zu.
* *REST-API*: Verwenden Sie die Workload Factory REST-APIs, um Ihre FSx für ONTAP Dateisysteme und andere AWS-Ressourcen bereitzustellen und zu verwalten.
* *CloudFormation*: Verwenden Sie AWS CloudFormation-Code, um die Aktionen auszuführen, die Sie in der Workload Factory-Konsole definiert haben, um AWS- und Drittanbieterressourcen aus dem CloudFormation-Stack in Ihrem AWS-Konto zu modellieren, bereitzustellen und zu verwalten.
* *Terraform NetApp Workload Factory-Anbieter*: Verwenden Sie Terraform, um in der Workload Factory-Konsole generierte Infrastruktur-Workflows zu erstellen und zu verwalten.




== Kosten

AWS verwaltet Ihr FSx for ONTAP -Konto, nicht Workload Factory. Weitere Informationen finden Sie unter link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html#pricing-for-fsx-ontap["Preise für Amazon FSX für NetApp ONTAP"^] .



== Regionen

Workload Factory wird in allen kommerziellen Regionen unterstützt, in denen FSx für ONTAP unterstützt wird.link:https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/["Unterstützte Amazon Regionen anzeigen."^]

Die folgenden AWS-Regionen werden nicht unterstützt:

* Regionen Chinas
* GovCloud (USA)-Regionen
* Geheime Cloud
* Streng geheime Cloud




== Hilfe wird abgerufen

Amazon FSX für NetApp ONTAP ist eine AWS-First-Party-Lösung. Wenn Sie Fragen oder Probleme des technischen Supports im Zusammenhang mit Ihrem FSX für ONTAP-Filesystem, Ihrer Infrastruktur oder jeder Lösung, die diesen Service verwendet, verwenden Sie das Support-Center in Ihrer AWS-Managementkonsole, um einen Support-Fall für AWS zu eröffnen. Wählen Sie den Service „FSX for ONTAP“ und die entsprechende Kategorie aus. Geben Sie die verbleibenden Informationen an, die zur Erstellung Ihres AWS-Supportfalls erforderlich sind.

Allgemeine Fragen zu Workload Factory oder Workload Factory-Anwendungen und -Diensten finden Sie unterlink:get-help.html["Hilfe zu FSx for ONTAP für Workload Factory erhalten"] .
