---
sidebar: sidebar 
permalink: learn-fsx-ontap.html 
keywords: Amazon FSx for NetApp ONTAP, FSx, storage, aws 
summary: Amazon FSX for NetApp ONTAP ist ein vollständig gemanagter Service, mit dem Kunden Filesysteme als Storage-Backend für Ihre Workloads innerhalb der Workload-Farm starten und ausführen können. 
---
= Erfahren Sie mehr über Amazon FSX für NetApp ONTAP in der BlueXP  Workload-Fabrik
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Amazon FSX for NetApp ONTAP ist ein vollständig gemanagter, Cloud-basierter Storage-Service, der erweiterte Datenmanagementfunktionen und hochskalierbare Performance bietet. FSX für ONTAP ermöglicht Ihnen, Filesysteme als Storage-Back-End für alle Ihre Workloads innerhalb der BlueXP  Workload-Fabrik zu erstellen und zu managen.

FSX für ONTAP bietet dieselben Funktionen, Performance und Managementfunktionen, die NetApp Kunden heute vor Ort nutzen. Außerdem bietet sie die Einfachheit, Agilität, Sicherheit und Skalierbarkeit eines nativen AWS Service.

FSX für ONTAP ist die _Storage_ Komponente in der Workload Factory.



== Funktionen

FSX für ONTAP bietet folgende Funktionen:

* *Fully-Managed Service*: Bietet einen vollständig gemanagten Service, der in die Workload Factory Konsole integriert ist.
* *Hohe Verfügbarkeit*: Bietet Hochverfügbarkeit für jedes FSX für ONTAP-Dateisystem, unterstützt einzelne und mehrere Verfügbarkeitszonen-Bereitstellungen.
* *Automatisierte Snapshots*: Sichert Daten mit automatisierten, effizienten Snapshots, die nahezu sofortige, platzsparende und schreibgeschützte Point-in-Time-Kopien des Dateisystems oder der Volumes sind.
* *Volume-Replikation*: Bietet Disaster Recovery mit regionsübergreifender Replikation über Amazon Web Services.
* *Effiziente Backups*: Fügt eine zusätzliche Schutzschicht mit einer Kopie der Daten in einer anderen Region für Notfälle hinzu.
* *Fast Cloning*: Beschleunigt die Applikationsentwicklung durch schnelles Klonen.
* * Multi-Protokoll-Unterstützung*: Unterstützt Network File System (NFS), Server Message Block (SMB) und Internet Small Computer Systems Interface (iSCSI) Protokolle.
* *Hoher Durchsatz*: Bietet hohe Durchsatz-Performance, um niedrige Latenzen für Workloads zu gewährleisten, die auf FSX for ONTAP-Dateisystemen ausgeführt werden.
* *In-Memory-Cache und NVMe-Cache*: Umfasst einen einzigartigen in-Memory-Cache und NVMe-Cache, der die Performance häufig genutzter Daten steigert.
* *Hunderttausende IOPS*: Stellt hunderttausende IOPS mit SSD-Festplatten bereit, um sicherzustellen, dass Ihre Speicher und Workloads rechtzeitig Ergebnisse erhalten.
* *Thin Provisioning*: Ermöglicht die Bereitstellung von Kapazitäten im Voraus und spart so lange Kosten, bis mehr Kapazität benötigt wird.
* *Datendeduplizierung und -Komprimierung*: Entfernt doppelte Daten und komprimiert Daten, um die Menge an physischem Storage zu reduzieren, der für FSX für ONTAP-Dateisysteme erforderlich ist, was zu Kosteneinsparungen führt.
* *Data Tiering*: Reduziert die Speicherkosten, indem weniger häufig verwendete Daten vom primären SSD-Storage-Tier mit hoher Performance auf die Storage-Tier mit dem sekundären Kapazitäts-Pool verschoben werden.




== Zusätzliche Funktionen in Workload Factory

* *Storage-Kostenvergleich*: Vergleicht die Storage-Kosten für Windows File Server mit FSX für ONTAP mit Amazon Elastic Block Store (EBS), Elastic File System (EFS) und FSX für Windows File Server. Über den Rechner erfahren Sie, wie FSX für ONTAP Storage-Konfigurationen potenzielle Einsparungen ermöglichen und Ihren Wechsel zu FSX für ONTAP Storage planen.
* *Workload Factory Benutzeroberfläche*: Bietet _Quick create_ und _Advanced create_ Bereitstellungsmodus Optionen. Schnelle Erstellung: Best Practices für Ihre Storage-Konfigurationen für AWS, NetApp und Branchenstandards
* *Codebox*: Bietet Entwicklern einen Code-Viewer für FSX für ONTAP-Operationen, Codevorlagen für Kopieren und Herunterladen sowie einen Automatisierungsskatalog für die Wiederverwendung von Code.




== Tools zur Verwendung der Workload Factory

Sie können die BlueXP -Workload-Fabrik mit den folgenden Tools verwenden:

* *Workload Factory Konsole*: Die Workload Factory Konsole bietet einen visuellen, ganzheitlichen Blick auf Ihre Anwendungen und Projekte.
* *BlueXP -Konsole*: Die BlueXP -Konsole bietet eine Hybrid-Interface-Erfahrung, so dass Sie BlueXP  Workload Factory zusammen mit anderen BlueXP -Diensten nutzen können.
* *Fragen Sie mich*: Verwenden Sie den Ask Me AI-Assistenten, um Fragen zu stellen und mehr über Workload Factory zu erfahren, ohne die Workload Factory Web UI zu verlassen. Rufen Sie mich im Menü Arbeitsbelastung Werkshilfe auf.
* *CloudShell CLI*: Workload Factory enthält eine CloudShell CLI zum Verwalten und Betreiben von AWS- und NetApp-Umgebungen über Konten hinweg über eine einzige browserbasierte CLI. Greifen Sie über die oberste Leiste der Workload-Factory-Konsole auf CloudShell zu.
* *REST-API*: Verwenden Sie die REST-APIs für die Workload Factory, um Ihre FSX for ONTAP-Dateisysteme und andere AWS-Ressourcen bereitzustellen und zu managen.
* *CloudFormation*: Verwenden Sie AWS CloudFormation-Code für die Durchführung der Aktionen, die Sie in der Workload-Factory-Konsole definiert haben, um AWS- und Drittanbieterressourcen vom CloudFormation-Stack in Ihrem AWS-Konto zu modellieren, bereitzustellen und zu managen.
* *Terraform BlueXP -Workload-Factory-Provider*: Verwenden Sie Terraform, um Infrastruktur-Workflows zu erstellen und zu managen, die in der Workload Factory-Konsole generiert werden.




== Kosten

AWS unterhält Ihr FSX für ONTAP-Konto, nicht für die Workload-Fabrik. Siehe link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html#pricing-for-fsx-ontap["Preise für Amazon FSX für NetApp ONTAP"^].



== Regionen

Workload Factory wird in allen kommerziellen Regionen unterstützt, in denen FSx für ONTAP unterstützt wird.link:https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/["Unterstützte Amazon Regionen anzeigen."^]

Die folgenden AWS-Regionen werden nicht unterstützt:

* Regionen Chinas
* GovCloud (USA)-Regionen
* Geheime Cloud
* Streng geheime Cloud




== Hilfe wird abgerufen

Amazon FSX für NetApp ONTAP ist eine AWS-First-Party-Lösung. Wenn Sie Fragen oder Probleme des technischen Supports im Zusammenhang mit Ihrem FSX für ONTAP-Filesystem, Ihrer Infrastruktur oder jeder Lösung, die diesen Service verwendet, verwenden Sie das Support-Center in Ihrer AWS-Managementkonsole, um einen Support-Fall für AWS zu eröffnen. Wählen Sie den Service „FSX for ONTAP“ und die entsprechende Kategorie aus. Geben Sie die verbleibenden Informationen an, die zur Erstellung Ihres AWS-Supportfalls erforderlich sind.

Allgemeine Fragen zu den Anwendungen und Dienstleistungen der Arbeitslast-Fabrik oder der Arbeitslast-Fabrik finden Sie unter link:get-help.html["Holen Sie sich Hilfe zu FSX für ONTAP für die Workload-Fabrik"].
