---
sidebar: sidebar 
permalink: links-overview.html 
keywords: links, accounts, lambda 
summary: Ein Workload Factory-Link erstellt eine Vertrauensbeziehung und Konnektivität zwischen einem Workload Factory-Konto und einem oder mehreren FSx for ONTAP Dateisystemen. 
---
= Erfahren Sie mehr über NetApp Workload Factory-Links
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Ein NetApp Workload Factory-Link erstellt eine Vertrauensbeziehung und Konnektivität zwischen einem Workload Factory-Konto und einem oder mehreren FSx for ONTAP -Dateisystemen.  Auf diese Weise können Sie bestimmte Dateisystemfunktionen direkt über die ONTAP REST-API-Aufrufe überwachen und verwalten, die über die Amazon FSx for ONTAP -API nicht verfügbar sind.

Sie benötigen keinen Link, um mit Workload Factory zu beginnen, aber in einigen Fällen müssen Sie einen Link erstellen, um alle Funktionen und Workload-Funktionen von Workload Factory freizuschalten.



== Warum Links von Vorteil sind

Links sind von Vorteil, da sie es Workload Factory ermöglichen, Vorgänge auszuführen, die über die Amazon FSx for ONTAP -API nicht nativ verfügbar sind.  Links ermöglichen erweiterte ONTAP Funktionen und -Automatisierungen, die die Verwaltung von FSx für ONTAP Dateisysteme verbessern.

Hier sind einige Vorteile der Verwendung von Links:

* Über die Verknüpfung kann die NetApp Konsole ONTAP -Befehle direkt an Ihr FSx für ONTAP Dateisystem senden und so erweiterte ONTAP Funktionen bereitstellen, die über das hinausgehen, was AWS nativ bietet.
* Links nutzen AWS Lambda, um Code als Reaktion auf Ereignisse auszuführen. Dieser serverlose Ansatz beseitigt die Abhängigkeit von einer in Ihrer VPC ausgeführten Instanz.




== Wie Links funktionieren

Links nutzen AWS Lambda Lambda führt Code als Reaktion auf Ereignisse aus und verwaltet automatisch die für diesen Code erforderlichen Rechenressourcen. Die von Ihnen erstellten Links sind Teil Ihres NetApp Kontos und mit einem AWS Konto verknüpft.

Nachdem Sie einen Link erstellt haben, können Sie ihn mit einem oder mehreren FSx for ONTAP -Dateisystemen verknüpfen. Jedes Dateisystem kann nur einem Link im selben NetApp-Konto zugeordnet werden. Wenn Sie mehrere NetApp-Konten haben, kann ein einziges Dateisystem mit zusätzlichen Links unter verschiedenen NetApp-Konten verknüpft werden.

Sie erstellen und verknüpfen Links aus der Speicherarbeitslast in Workload Factory.

Sie können Links mithilfe von Anmeldeinformationen authentifizieren, die im Anmeldeinformationsdienst von Workload Factory gespeichert sind, oder mithilfe Ihrer Anmeldeinformationen, die im AWS Secrets Manager gespeichert sind.  Die Workload Factory unterstützt keine Änderung des Authentifizierungsmodus.



== Kosten

Für jede von Lambda durchgeführte Transaktion fallen Gebühren an.  Da Lambda als Proxy zwischen den beiden Systemen fungiert, fallen Gebühren an, wenn Lambda eine Anfrage an die ONTAP REST API auf einem Dateisystem sendet und wenn es die Antwort zurück an Workload Factory sendet.

link:https://aws.amazon.com/lambda/pricing/["Informieren Sie sich über die Kosten bei der Nutzung von AWS Lambda"^]



== Wenn ein Link erforderlich ist

Workload Factory benötigt einen Link, um bestimmte Informationen anzuzeigen und bestimmte Aufgaben auszuführen.  Wenn Sie versuchen, einen Vorgang auszuführen, der einen Link erfordert, und Sie keinen Link mit dem FSx for ONTAP Dateisystem verknüpft haben, benachrichtigt Sie Workload Factory, dass für den Vorgang ein Link erforderlich ist.

Zu den Funktionen, für die ein Link erforderlich ist, gehören:

* Gut strukturierter Status der FSx for ONTAP Dateisystemkonfigurationen für proaktive Wartung, Zuverlässigkeit und Kosten-Leistungs-Optimierung
* ONTAP EMS Ereignisüberwachung und Alarmierung
* Autonomer Ransomware-Schutz (ARP/AI) von NetApp
* Verbesserte ganzheitliche Kapazitätsbeobachtung über FSx für ONTAP Dateisysteme
* Datenreplikation, Verwaltung und Überwachung von Volume- und Storage-VMs
* Bereitstellung und Verwaltung von SMB/CIFS-Freigaben und NFS-Exportrichtlinien
* Verwaltung von iSCSI-Volumes auf einem FSX für ONTAP-Dateisystem
* Erstellen und Verwalten von Snapshot-Richtlinien für benutzerdefinierte Schutz-SLAs
* Verbesserungen der Inode-Verwaltung für automatisches Kapazitätsmanagement
* Automatisches Volumenwachstum für elastische Skalierung
* Erstellen und Verwalten von Klonen für sofortiges, direktes Klonen von Daten
* Anzeige zusätzlicher Metriken direkt aus ONTAP , wie z. B. die ONTAP Version


Erfahren Sie, wie man link:create-link.html["Verbinden Sie einen Link mit einem FSx für ONTAP Dateisystem"].
