---
sidebar: sidebar 
permalink: links-overview.html 
keywords: links, accounts, lambda 
summary: Eine Workload-Factory-Verbindung erzeugt eine Vertrauensbeziehung und eine Verbindung zwischen einem Workload-Factory-Konto und einem oder mehreren FSX für ONTAP-Dateisystemen. 
---
= Weitere Informationen zu den BlueXP -Workload-Werkseinstellungen
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Ein werkseitiger BlueXP -Workload-Link erzeugt eine Vertrauensbeziehung und eine Verbindung zwischen einem werkseitigen Workload-Konto und einem oder mehreren FSX für ONTAP-Dateisystemen. So können Sie bestimmte Filesystem-Funktionen direkt über die ONTAP-REST-API-Aufrufe überwachen und managen, die über die Amazon FSX for ONTAP-API nicht verfügbar sind.

Sie benötigen keinen Link, um mit der Workload Factory zu beginnen, aber in einigen Fällen müssen Sie einen Link erstellen, um alle Workload Factory-Funktionen und Workload-Funktionen freizuschalten.



== Wie Links funktionieren

Links nutzen AWS Lambda Lambda führt Code als Reaktion auf Ereignisse aus und verwaltet automatisch die für diesen Code erforderlichen Rechenressourcen. Die von Ihnen erstellten Links sind Teil Ihres NetApp Kontos und mit einem AWS Konto verknüpft.

Nachdem Sie einen Link erstellt haben, können Sie ihn einem oder mehreren FSX for ONTAP-Dateisystemen zuordnen. Jedes Dateisystem kann nur einem Link im selben NetApp-Konto zugeordnet werden. Wenn Sie mehrere NetApp-Konten haben, kann ein einziges Dateisystem mit zusätzlichen Links unter verschiedenen NetApp-Konten verknüpft werden.

Sie erstellen Links auf den FSX für ONTAP-Dateisystemseiten in Workload Factory. link:create-link.html["Erfahren Sie, wie Sie Verknüpfungen erstellen"] Genaue Informationen.



== Kosten

Jede Transaktion, die Lambda durchführt, ist kostenpflichtig. Da Lambda als Proxy zwischen den beiden Systemen fungiert, wird eine Gebühr erhoben, wenn Lambda eine Anforderung an die ONTAP-REST-API auf einem Dateisystem sendet und die Antwort zurück an die Workload Factory sendet.

link:https://aws.amazon.com/lambda/pricing/["Informieren Sie sich über die Kosten bei der Nutzung von AWS Lambda"^]



== Wenn ein Link erforderlich ist

Workload Factory erfordert einen Link, um einige Informationen anzuzeigen und einige Aufgaben auszuführen. Wenn Sie versuchen, einen Vorgang auszuführen, der einen Link erfordert, und Sie keinen Link mit dem Dateisystem FSX für ONTAP verknüpft haben, wird eine Meldung angezeigt, dass der Vorgang einen Link erfordert. Sie können zu diesem Zeitpunkt einen neuen Link hinzufügen oder das FSX for ONTAP-Dateisystem einem vorhandenen Link zuweisen, damit Sie den Vorgang durchführen können.

Zu den Funktionen, für die ein Link erforderlich ist, gehören:

* Anzeigen der Version von ONTAP, die auf einem FSX für ONTAP-Dateisystem installiert ist
* Verwaltung von iSCSI-Volumes auf einem FSX für ONTAP-Dateisystem
* Autogrow-Funktion für Volumes
* Erstellung und Management von Snapshot-Richtlinien
* Konfiguration der Replikationsbeziehungen
* Volume-Replizierung zwischen FSX für ONTAP-Filesystemen
* Konfiguration der Backup-Beziehung
* Erstellen von Volume-Daten-Backups in Cloud-Storage
* Volume-Klone in einem FSX für ONTAP Filesystem
* Anzeige zusätzlicher Metriken direkt aus ONTAP (Standardkennzahlen werden von Amazon CloudWatch erfasst)
* Management von NFS-Exportrichtlinien
* Management von CIFS-Freigaben

