---
sidebar: sidebar 
permalink: manage-snapshot-policy.html 
keywords: manage snapshot policy, change snapshot policy, snapshot policies, snapshot schedule, update 
summary: Verwalten Sie Snapshot-Richtlinien für FSx for ONTAP -Volumes in Workload Factory.  Eine Snapshot-Richtlinie definiert, wie das System Snapshots für ein Volume erstellt. 
---
= Verwalten von Snapshot-Richtlinien
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Verwalten Sie Snapshot-Richtlinien für FSx for ONTAP -Volumes in Workload Factory.  Eine Snapshot-Richtlinie definiert, wie das System Snapshots für ein Volume erstellt.

.Über diese Aufgabe
Snapshot-Managementvorgänge wie das Zuweisen, Ändern und Löschen von Snapshot-Richtlinien für Volumes in einem Filesystem von FSX für ONTAP werden auf der Storage-VM-Ebene gemanagt. Snapshot-Richtlinien können für eine einzelne Storage-VM oder für alle Storage-VMs freigegeben werden.

Für einige Verwaltungsaufgaben müssen Sie einen Link mit dem FSx for ONTAP Dateisystem verknüpfen. link:https://docs.netapp.com/us-en/workload-fsx-ontap/links-overview.html["Informationen zu Workload Factory-Links"] .

Standardmäßig ist jedes Volume mit der Snapshot-Richtlinie des Dateisystems verknüpft `default` . Wir empfehlen, diese Richtlinie für die meisten Workloads zu verwenden.



== Ändern Sie eine Snapshot-Richtlinie

Sie können den Namen der Snapshot-Richtlinie, den Zeitplan und die Anzahl der beizubehaltenden Kopien ändern sowie unveränderliche Snapshots aktivieren oder deaktivieren. Die Richtlinienfreigabe für Storage-VMs kann nicht aktiviert oder deaktiviert werden. Diese Option ist nur während der Erstellung der Snapshot-Richtlinie verfügbar.

.Bevor Sie beginnen
Um vorhandene Snapshot-Richtlinien anzuzeigen, müssen Sie einen Link zuordnen. link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["Erfahren Sie, wie Sie einen vorhandenen Link zuordnen oder einen neuen Link erstellen und zuordnen."]. Kehren Sie nach dem Verknüpfen zu diesem Vorgang zurück.

.Schritte
. Melden Sie sich mit einem der link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["Konsolenerfahrungen"^]an.
. Wählen Sie unter *Speicher* die Option *Zum Speicher gehen*.
. Wählen Sie auf der Registerkarte *FSx for ONTAP* das Aktionsmenü des Dateisystems und dann *Verwalten*.
. Wählen Sie in der Dateisystemübersicht die Registerkarte *Storage VMs* aus.
. Wählen Sie auf der Registerkarte *Storage-VMs* das Aktionsmenü für die Storage-VM aus, die das mit geplanten Snapshots zu schützende Volume enthält, dann *Erweiterte Aktionen* und dann *Snapshot-Richtlinien verwalten*.
. Wählen Sie auf der Seite „Snapshot-Richtlinienverwaltung“ das Aktionsmenü für die zu ändernde Snapshot-Richtlinie aus und wählen Sie dann *Bearbeiten*.
. Nehmen Sie im Dialogfeld Snapshot-Richtlinie bearbeiten die erforderlichen Änderungen an der Snapshot-Richtlinie vor.
. Wählen Sie *Anwenden*.


.Ergebnis
Die Snapshot-Richtlinie wird aktualisiert.



== Aktivieren Sie unveränderliche Snapshots

Sperren Sie Snapshots, um zu verhindern, dass sie während des Aufbewahrungszeitraums gelöscht werden.

.Bevor Sie beginnen
Sie müssen einen Link zuordnen, um unveränderliche Snapshots zu aktivieren. link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["Erfahren Sie, wie Sie einen vorhandenen Link zuordnen oder einen neuen Link erstellen und zuordnen."]. Kehren Sie nach dem Verknüpfen zu diesem Vorgang zurück.

.Schritte
. Melden Sie sich mit einem der link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["Konsolenerfahrungen"^]an.
. Wählen Sie unter *Speicher* die Option *Zum Speicher gehen*.
. Wählen Sie auf der Registerkarte *FSx for ONTAP* das Aktionsmenü des Dateisystems aus, das das Volume enthält, für das Snapshots gesperrt werden sollen, und wählen Sie dann *Verwalten*.
. Wählen Sie in der Dateisystemübersicht die Registerkarte *Volumes* aus.
. Wählen Sie auf der Registerkarte *Volumes* das Aktionsmenü für das zu schützende Volume aus.
. Wählen Sie *Data Protection actions*, *Snapshots*, dann *make a Snapshot unveränderlich*.
. Gehen Sie im Dialogfeld Snapshot unveränderlich erstellen wie folgt vor:
+
.. *Snapshot-Name*: Wählen Sie den zu sperrenden Snapshot aus.
.. Legen Sie die *Aufbewahrungsfrist* in Stunden, Tagen, Monaten oder Jahren fest.
.. Akzeptieren Sie die Aussage.


. Wählen Sie *Anwenden*.


.Ergebnis
Der Volume-Snapshot ist jetzt gesperrt.



== Weisen Sie einem Volume eine Snapshot-Richtlinie zu

Sie können einem einzelnen Volume eine Snapshot-Richtlinie zuweisen, um geplante Snapshots für das Volume zu erstellen.

.Bevor Sie beginnen
Sie müssen einen Link zuordnen, um eine Snapshot-Richtlinie zuzuweisen. link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["Erfahren Sie, wie Sie einen vorhandenen Link zuordnen oder einen neuen Link erstellen und zuordnen."]. Kehren Sie nach dem Verknüpfen zu diesem Vorgang zurück.

.Schritte
. Melden Sie sich mit einem der link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["Konsolenerfahrungen"^]an.
. Wählen Sie unter *Speicher* die Option *Zum Speicher gehen*.
. Wählen Sie auf der Registerkarte *FSx for ONTAP* das Aktionsmenü des Dateisystems aus, das das Volume enthält, dem Sie eine Snapshot-Richtlinie zuweisen möchten, und wählen Sie dann *Verwalten*.
. Wählen Sie in der Dateisystemübersicht die Registerkarte *Storage VMs* aus.
. Wählen Sie auf der Registerkarte *Storage-VMs* das Aktionsmenü für die Storage-VM aus, die das mit geplanten Snapshots zu schützende Volume enthält, dann *Erweiterte Aktionen* und dann *Snapshot-Richtlinien verwalten*.
. Wählen Sie auf der Seite „Snapshot-Richtlinienverwaltung“ das Aktionsmenü der Snapshot-Richtlinie und dann *Richtlinie dem Volume zuweisen* aus.
. Wählen Sie im Dialogfeld Snapshot-Richtlinie zuweisen eine Snapshot-Richtlinie aus, die dem Volume zugewiesen werden soll, und überprüfen Sie den Richtlinienzeitplan.
+
Wenn die Richtlinie unveränderliche Snapshots enthält und Sie diese verwenden möchten, akzeptieren Sie die Anweisung.

. Wählen Sie *Zuweisen*.


.Ergebnis
Die Snapshot-Richtlinie ist dem Volume zugewiesen.



== Entfernen einer Snapshot-Richtlinie aus einem Volume

Entfernen Sie eine Snapshot-Richtlinie aus einem Volume, da Sie keine Snapshots des Volumes mehr möchten oder eine Snapshot-Richtlinie löschen möchten, die mehreren Volumes zugewiesen ist. <<Löschen einer Snapshot-Richtlinie,Löschen einer Snapshot-Richtlinie>>Wenn diesem Volume mehr als ein Volume zugewiesen ist, müssen Sie es manuell aus allen Volumes entfernen.

.Bevor Sie beginnen
Sie müssen einen Link zuordnen, um eine Snapshot-Richtlinie zu entfernen. link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["Erfahren Sie, wie Sie einen vorhandenen Link zuordnen oder einen neuen Link erstellen und zuordnen."]. Kehren Sie nach dem Verknüpfen zu diesem Vorgang zurück.

.Schritte
. Melden Sie sich mit einem der link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["Konsolenerfahrungen"^]an.
. Wählen Sie unter *Speicher* die Option *Zum Speicher gehen*.
. Wählen Sie auf der Registerkarte *FSx for ONTAP* das Aktionsmenü des Dateisystems aus, das das Volume enthält, dem Sie eine Snapshot-Richtlinie zuweisen möchten, und wählen Sie dann *Verwalten*.
. Wählen Sie in der Dateisystemübersicht die Registerkarte *Storage VMs* aus.
. Wählen Sie auf der Registerkarte *Storage-VMs* das Aktionsmenü für die Storage-VM aus, die das mit geplanten Snapshots zu schützende Volume enthält, dann *Erweiterte Aktionen* und dann *Snapshot-Richtlinien verwalten*.
. Wählen Sie auf der Seite „Snapshot-Richtlinienverwaltung“ das Aktionsmenü der Snapshot-Richtlinie und dann *Richtlinie dem Volume zuweisen* aus.
. Wählen Sie im Dialogfeld Snapshot-Richtlinie zuweisen die Option *Keine* aus, um die Snapshot-Richtlinie zu entfernen.
. Wählen Sie *Zuweisen*.


.Ergebnis
Die Snapshot-Richtlinie wird aus dem Volume entfernt.



== Löschen einer Snapshot-Richtlinie

Löschen Sie eine Snapshot-Richtlinie, wenn sie nicht mehr benötigt wird.

Wenn eine Snapshot-Richtlinie mehr als einem Volume zugewiesen ist, müssen Sie manuell <<Entfernen einer Snapshot-Richtlinie aus einem Volume,Entfernen Sie sie>> von allen Volumes aus die Snapshot-Richtlinie löschen. Alternativ können Sie <<Weisen Sie einem Volume eine Snapshot-Richtlinie zu,Weisen Sie eine andere Snapshot-Richtlinie zu>>auf die Volumes klicken.

.Schritte
. Melden Sie sich mit einem der link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["Konsolenerfahrungen"^]an.
. Wählen Sie unter *Speicher* die Option *Zum Speicher gehen*.
. Wählen Sie im Speichermenü *FSx für ONTAP* aus.
. Wählen Sie in *FSx for ONTAP* das Aktionsmenü des Dateisystems mit dem Volume und wählen Sie dann *Verwalten*.
. Wählen Sie in der Dateisystemübersicht die Registerkarte *Storage VMs* aus.
. Wählen Sie auf der Registerkarte *Storage-VMs* das Aktionsmenü der Storage-VM mit der zu löschenden Snapshot-Richtlinie, dann *Erweiterte Aktionen* und dann *Snapshot-Richtlinien verwalten*.
. Wählen Sie auf der Seite „Snapshot-Richtlinienverwaltung“ das Aktionsmenü für die zu löschende Snapshot-Richtlinie aus und wählen Sie dann *Löschen*.
. Wählen Sie im Dialogfeld Löschen *Löschen*, um die Richtlinie zu löschen.

