---
sidebar: sidebar 
permalink: manage-cifs-share.html 
keywords: cifs, CIFS, cifs share, change cifs share, update cifs share, modify cifs share 
summary: Ändern Sie die CIFS-Freigabe für ein Volume in der BlueXP -Workload-Fabrik, die den SMB/CIFS-Protokolltyp verwendet. 
---
= Verwalten Sie die CIFS-Freigabe für ein Volume in der BlueXP  Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Beim Management der CIFS-Freigabe eines Volumes in der BlueXP  Workload Factory müssen die Benutzer und Gruppen ermittelt werden, denen Zugriff gewährt werden soll, sowie die Art des Zugriffs, den sie gewähren können.

.Bevor Sie beginnen
Legen Sie die Benutzer oder Gruppen fest, denen Zugriff gewährt werden soll, und legen Sie fest, welche Art von Zugriff ihnen gewährt werden soll.

.Schritte
. Melden Sie sich mit einem der link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["Konsolenerfahrungen"^]an.
. Wählen Sie unter Speicher die Option *Gehe zu Lagerbestandsbestand* aus.
. Wählen Sie im Register *FSX for ONTAP* das drei-Punkt-Menü des Dateisystems mit dem zu aktualisierenden Volume aus und wählen Sie dann *Verwalten*.
. Wählen Sie in der Dateisystemübersicht die Registerkarte *Volumes* aus.
. Wählen Sie auf der Registerkarte Volumes das drei-Punkt-Menü des Volumes aus, für das Sie die SMB-Freigabe ändern möchten.
. Wählen Sie *Erweiterte Aktionen* und dann *CIFS-Freigabe bearbeiten*.
. Geben Sie auf der Seite „CIFS-Freigabe bearbeiten“ Folgendes ein:
+
.. *Name*: Geben Sie den Namen der CIFS-Freigabe ein.
.. *Berechtigungen*: Wählen Sie Vollzugriff, Lesen/Schreiben, Lesen oder keinen Zugriff und geben Sie dann die Benutzer oder Gruppen getrennt durch ein Semikolon ( ; ) ein. Bei Benutzern oder Gruppen wird zwischen Groß- und Kleinschreibung unterschieden, und die Domäne des Benutzers muss im Format „Domain\username“ enthalten sein.


. Wählen Sie Übernehmen.
+
Änderungen können dazu führen, dass aktuelle Benutzer oder Gruppen den Zugriff auf die CIFS-Freigabe verlieren.

. Wählen Sie *Weiter*, um die Änderungen zu speichern.


.Ergebnis
Änderungen an der CIFS-Freigabe werden übernommen.
