---
sidebar: sidebar 
permalink: manage-snapshot-policy.html 
keywords: manage snapshot policy, change snapshot policy, snapshot policies, snapshot schedule, update 
summary: Managen von Snapshot-Richtlinien für FSX für ONTAP-Volumes in der BlueXP -Workload-Fabrik. Eine Snapshot-Richtlinie definiert, wie das System Snapshots für ein Volume erstellt. 
---
= Verwalten von Snapshot-Richtlinien
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Managen von Snapshot-Richtlinien für FSX für ONTAP-Volumes in der BlueXP -Workload-Fabrik. Eine Snapshot-Richtlinie definiert, wie das System Snapshots für ein Volume erstellt.

.Über diese Aufgabe
Snapshot-Managementvorgänge wie das Zuweisen, Ändern und Löschen von Snapshot-Richtlinien für Volumes in einem Filesystem von FSX für ONTAP werden auf der Storage-VM-Ebene gemanagt. Snapshot-Richtlinien können für eine einzelne Storage-VM oder für alle Storage-VMs freigegeben werden.

Einige Managementaufgaben erfordern Sie link:manage-links.html["Verknüpfen Sie eine Verknüpfung"]zum FSX für ONTAP-Dateisystem. Wenn Sie noch keinen Link haben, link:create-link.html["Erstellen Sie eine Verknüpfung"].

Standardmäßig ist jedes Volume mit der Snapshot-Richtlinie des Dateisystems verknüpft `default` . Wir empfehlen, diese Richtlinie für die meisten Workloads zu verwenden.



== Ändern Sie eine Snapshot-Richtlinie

Sie können den Namen der Snapshot-Richtlinie, den Zeitplan und die Anzahl der beizubehaltenden Kopien ändern sowie unveränderliche Snapshots aktivieren oder deaktivieren. Die Richtlinienfreigabe für Storage-VMs kann nicht aktiviert oder deaktiviert werden. Diese Option ist nur während der Erstellung der Snapshot-Richtlinie verfügbar.

.Bevor Sie beginnen
Um vorhandene Snapshot-Richtlinien anzuzeigen, müssen Sie eine Verknüpfung zuordnen. Um einen Link zu verknüpfen, wählen Sie unter *Kontoname* *Associate Link*. Kehren Sie dann zu diesem Vorgang zurück.

.Schritte
. Melden Sie sich mit einem der link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["Konsolenerfahrungen"^]an.
. Wählen Sie unter *Storage* *zum Lagerbestandsverzeichnis* gehen.
. Wählen Sie im Register *FSX for ONTAP* das drei-Punkt-Menü des Dateisystems aus und wählen Sie dann *Verwalten*.
. Wählen Sie in der Dateisystemübersicht die Registerkarte *Storage VMs* aus.
. Wählen Sie auf der Registerkarte *Storage VMs* das drei-Punkt-Menü für die Speicher-VM, die das Volume enthält, das mit geplanten Snapshots geschützt werden soll, dann *Advanced Actions* und dann *Manage Snapshot Policies*.
. Wählen Sie auf der Seite Snapshot Policy Management das drei-Punkt-Menü für die zu ändernde Snapshot Policy aus und wählen Sie dann *Edit*.
. Nehmen Sie im Dialogfeld Snapshot-Richtlinie bearbeiten die erforderlichen Änderungen an der Snapshot-Richtlinie vor.
. Wählen Sie *Anwenden*.


.Ergebnis
Die Snapshot-Richtlinie wird aktualisiert.



== Aktivieren Sie unveränderliche Snapshots

Sperren Sie Snapshots, um zu verhindern, dass sie während des Aufbewahrungszeitraums gelöscht werden.

.Bevor Sie beginnen
Sie müssen link:manage-links.html["Verknüpfen Sie eine Verknüpfung"]unveränderliche Snapshots aktivieren. Wenn Sie noch keinen Link haben, link:create-link.html["Erstellen Sie eine Verknüpfung"]. Um einen Link im Dateisystem zu verknüpfen, wählen Sie unter *Kontoname* *Associate Link* aus. Sobald die Verknüpfung verknüpft ist, kehren Sie zu diesem Vorgang zurück.

.Schritte
. Melden Sie sich mit einem der link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["Konsolenerfahrungen"^]an.
. Wählen Sie unter *Storage* *zum Lagerbestandsverzeichnis* gehen.
. Wählen Sie auf der Registerkarte *FSX für ONTAP* das drei-Punkt-Menü des Dateisystems aus, das das Volume enthält, für das Snapshots gesperrt werden sollen, und wählen Sie dann *Verwalten* aus.
. Wählen Sie in der Dateisystemübersicht die Registerkarte *Volumes* aus.
. Wählen Sie auf der Registerkarte *Volumes* das drei-Punkt-Menü für das zu schützende Volume aus.
. Wählen Sie *Data Protection actions*, *Snapshots*, dann *make a Snapshot unveränderlich*.
. Gehen Sie im Dialogfeld Snapshot unveränderlich erstellen wie folgt vor:
+
.. *Snapshot-Name*: Wählen Sie den zu sperrenden Snapshot aus.
.. Legen Sie die *Aufbewahrungsfrist* in Stunden, Tagen, Monaten oder Jahren fest.
.. Akzeptieren Sie die Aussage.


. Wählen Sie *Anwenden*.


.Ergebnis
Der Volume-Snapshot ist jetzt gesperrt.



== Weisen Sie einem Volume eine Snapshot-Richtlinie zu

Sie können einem einzelnen Volume eine Snapshot-Richtlinie zuweisen, um geplante Snapshots für das Volume zu erstellen.

.Bevor Sie beginnen
Sie müssen link:manage-links.html["Verknüpfen Sie eine Verknüpfung"]eine Snapshot-Richtlinie zuweisen. Wenn Sie noch keinen Link haben, link:create-link.html["Erstellen Sie eine Verknüpfung"]. Um einen Link im Dateisystem zu verknüpfen, wählen Sie unter *Kontoname* *Associate Link* aus. Kehren Sie nach dem Verknüpfen zu diesem Vorgang zurück.

.Schritte
. Melden Sie sich mit einem der link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["Konsolenerfahrungen"^]an.
. Wählen Sie unter *Storage* *zum Lagerbestandsverzeichnis* gehen.
. Wählen Sie auf der Registerkarte *FSX for ONTAP* das drei-Punkt-Menü des Dateisystems aus, das das Volume enthält, dem eine Snapshot-Richtlinie zugewiesen werden soll, und wählen Sie dann *Verwalten* aus.
. Wählen Sie in der Dateisystemübersicht die Registerkarte *Storage VMs* aus.
. Wählen Sie auf der Registerkarte *Storage VMs* das drei-Punkt-Menü für die Speicher-VM, die das Volume enthält, das mit geplanten Snapshots geschützt werden soll, dann *Advanced Actions* und dann *Manage Snapshot Policies*.
. Wählen Sie auf der Seite Snapshot Policy Management das drei-Punkt-Menü der Snapshot Policy aus und wählen Sie dann *Assign Policy to Volume* aus.
. Wählen Sie im Dialogfeld Snapshot-Richtlinie zuweisen eine Snapshot-Richtlinie aus, die dem Volume zugewiesen werden soll, und überprüfen Sie den Richtlinienzeitplan.
+
Wenn die Richtlinie unveränderliche Snapshots enthält und Sie diese verwenden möchten, akzeptieren Sie die Anweisung.

. Wählen Sie *Zuweisen*.


.Ergebnis
Die Snapshot-Richtlinie ist dem Volume zugewiesen.



== Entfernen einer Snapshot-Richtlinie aus einem Volume

Entfernen Sie eine Snapshot-Richtlinie aus einem Volume, da Sie keine Snapshots des Volumes mehr möchten oder eine Snapshot-Richtlinie löschen möchten, die mehreren Volumes zugewiesen ist. <<Löschen einer Snapshot-Richtlinie,Löschen einer Snapshot-Richtlinie>>Wenn diesem Volume mehr als ein Volume zugewiesen ist, müssen Sie es manuell aus allen Volumes entfernen.

.Bevor Sie beginnen
Sie müssen link:manage-links.html["Verknüpfen Sie eine Verknüpfung"]eine Snapshot-Richtlinie entfernen. Wenn Sie noch keinen Link haben, link:create-link.html["Erstellen Sie eine Verknüpfung"]. Um einen Link im Dateisystem zu verknüpfen, wählen Sie unter *Kontoname* *Associate Link* aus. Kehren Sie nach dem Verknüpfen zu diesem Vorgang zurück.

.Schritte
. Melden Sie sich mit einem der link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["Konsolenerfahrungen"^]an.
. Wählen Sie unter *Storage* *zum Lagerbestandsverzeichnis* gehen.
. Wählen Sie auf der Registerkarte *FSX for ONTAP* das drei-Punkt-Menü des Dateisystems aus, das das Volume enthält, dem eine Snapshot-Richtlinie zugewiesen werden soll, und wählen Sie dann *Verwalten* aus.
. Wählen Sie in der Dateisystemübersicht die Registerkarte *Storage VMs* aus.
. Wählen Sie auf der Registerkarte *Storage VMs* das drei-Punkt-Menü für die Speicher-VM, die das Volume enthält, das mit geplanten Snapshots geschützt werden soll, dann *Advanced Actions* und dann *Manage Snapshot Policies*.
. Wählen Sie auf der Seite Snapshot Policy Management das drei-Punkt-Menü der Snapshot Policy aus und wählen Sie dann *Assign Policy to Volume* aus.
. Wählen Sie im Dialogfeld Snapshot-Richtlinie zuweisen die Option *Keine* aus, um die Snapshot-Richtlinie zu entfernen.
. Wählen Sie *Zuweisen*.


.Ergebnis
Die Snapshot-Richtlinie wird aus dem Volume entfernt.



== Löschen einer Snapshot-Richtlinie

Löschen Sie eine Snapshot-Richtlinie, wenn sie nicht mehr benötigt wird.

Wenn eine Snapshot-Richtlinie mehr als einem Volume zugewiesen ist, müssen Sie manuell <<Entfernen einer Snapshot-Richtlinie aus einem Volume,Entfernen Sie sie>> von allen Volumes aus die Snapshot-Richtlinie löschen. Alternativ können Sie <<Weisen Sie einem Volume eine Snapshot-Richtlinie zu,Weisen Sie eine andere Snapshot-Richtlinie zu>>auf die Volumes klicken.

.Schritte
. Melden Sie sich mit einem der link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["Konsolenerfahrungen"^]an.
. Wählen Sie unter *Storage* *zum Lagerbestandsverzeichnis* gehen.
. Wählen Sie im Register *FSX for ONTAP* das drei-Punkt-Menü des Dateisystems mit dem Volume aus und wählen Sie dann *Verwalten*.
. Wählen Sie in der Dateisystemübersicht die Registerkarte *Storage VMs* aus.
. Wählen Sie auf der Registerkarte *Storage VMs* das drei-Punkt-Menü der Speicher-VM mit der zu löschenden Snapshot-Richtlinie, dann *Advanced Actions* und dann *Manage Snapshot Policies*.
. Wählen Sie auf der Seite Snapshot Policy Management das drei-Punkt-Menü aus, das die Snapshot Policy löschen soll, und wählen Sie dann *Delete* aus.
. Wählen Sie im Dialogfeld Löschen *Löschen*, um die Richtlinie zu löschen.


.Ergebnis
Die Snapshot-Richtlinie wird gelöscht.
