---
sidebar: sidebar 
permalink: manage-cifs-share.html 
keywords: cifs, smb, SMB/CIFS, cifs share, change, update, modify, delete, create 
summary: Die Verwaltung der SMB/CIFS-Freigabe eines Volumes in der Workload Factory umfasst das Erstellen, Bestimmen des Benutzer- und Gruppenzugriffs und das Löschen. 
---
= Verwalten der SMB/CIFS-Freigabe für ein Volume in der Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Die Verwaltung der SMB/CIFS-Freigabe eines Volumes in der Workload Factory umfasst die Erstellung von SMB/CIFS-Freigaben, die Bestimmung der Benutzer und Gruppen, denen Zugriff gewährt werden soll, und der ihnen zu erteilenden Berechtigungsstufe sowie das Löschen von SMB/CIFS-Freigaben.

.Bevor Sie beginnen
Bevor Sie beginnen, gehen Sie wie folgt vor:

* Um SMB/CIFS-Freigaben zu verwalten, müssen Sie einen Link zuordnen. link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["Erfahren Sie, wie Sie einen vorhandenen Link zuordnen oder einen neuen Link erstellen und zuordnen."] .  Kehren Sie nach der Verknüpfung zu diesem Vorgang zurück.
* Legen Sie die Benutzer oder Gruppen fest, denen Zugriff gewährt werden soll, und legen Sie die Berechtigungsstufe fest.




== Erstellen einer SMB/CIFS-Freigabe für ein Volume

Befolgen Sie die Schritte zum Erstellen einer SMB/CIFS-Freigabe für ein Volume.

.Schritte
. Melden Sie sich mit einem der link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["Konsolenerfahrungen"^]an.
. Wählen Sie unter Speicher die Option *Gehe zu Lagerbestandsbestand* aus.
. Wählen Sie im Register *FSX for ONTAP* das drei-Punkt-Menü des Dateisystems mit dem zu aktualisierenden Volume aus und wählen Sie dann *Verwalten*.
. Wählen Sie in der Dateisystemübersicht die Registerkarte *Volumes* aus.
. Wählen Sie auf der Registerkarte Volumes das drei-Punkt-Menü des Volumes aus, für das Sie die SMB-Freigabe ändern möchten.
. Wählen Sie *Erweiterte Aktionen* und dann *SMB/CIFS-Freigaben verwalten*.
. Wählen Sie auf der Seite „SMB/CIFS-Freigaben verwalten“ die Option *SMB/CIFS-Freigabe erstellen* aus.
. Geben Sie im Dialogfeld „SMB/CIFS-Freigabe erstellen“ Folgendes ein:
+
.. *Name*: Geben Sie den Namen der SMB/CIFS-Freigabe ein.
.. *Pfad*: Definieren Sie den Pfad entweder mit dem Standard-Volume-Namen oder stellen Sie eine Freigabe für ein internes Verzeichnis bereit.
+
Gültige Pfadeingaben für den Datenträgernamen, beispielsweise „Avocado“, sind wie folgt:

+
*** /Avocado
*** /avocado/ordner
*** /avocado/Ordner/Unterordner
*** /avocado/dateiname
+
Gültige Pfadangaben für den Freigabenamen, beispielsweise „Server“, sind wie folgt:

*** \\Server
*** \\Server\Projekte
*** \\Server\Projekte\Gemeinsame Ressourcen


.. *Berechtigungen*: Wählen Sie Vollzugriff, Lesen/Schreiben, Lesen oder keinen Zugriff und geben Sie dann die Benutzer oder Gruppen getrennt durch ein Semikolon ( ; ) ein. Bei Benutzern oder Gruppen wird zwischen Groß- und Kleinschreibung unterschieden, und die Domäne des Benutzers muss im Format „Domain\username“ enthalten sein.


. Wählen Sie *Erstellen*.




== Ändern einer SMB/CIFS-Freigabe für ein Volume

Befolgen Sie die Schritte, um die SMB/CIFS-Freigabeeinstellungen für ein Volume zu ändern.

.Schritte
. Melden Sie sich mit einem der link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["Konsolenerfahrungen"^]an.
. Wählen Sie unter Speicher die Option *Gehe zu Lagerbestandsbestand* aus.
. Wählen Sie im Register *FSX for ONTAP* das drei-Punkt-Menü des Dateisystems mit dem zu aktualisierenden Volume aus und wählen Sie dann *Verwalten*.
. Wählen Sie in der Dateisystemübersicht die Registerkarte *Volumes* aus.
. Wählen Sie auf der Registerkarte Volumes das drei-Punkt-Menü des Volumes aus, für das Sie die SMB-Freigabe ändern möchten.
. Wählen Sie *Erweiterte Aktionen* und dann *SMB/CIFS-Freigaben verwalten*.
. Wählen Sie auf der Seite „SMB/CIFS-Freigaben verwalten“ die Option „Anzeigen und bearbeiten“ aus.
. Ändern Sie die SMB/CIFS-Zugriffsberechtigungen oder die Benutzer oder Gruppen, denen Berechtigungen erteilt werden sollen.
+
Änderungen können dazu führen, dass aktuelle Benutzer oder Gruppen den Zugriff auf die SMB/CIFS-Freigabe verlieren.

. Wählen Sie *Übernehmen*, um die Änderungen zu speichern.




== Löschen einer SMB/CIFS-Freigabe für ein Volume

Befolgen Sie die Schritte zum Löschen einer SMB/CIFS-Freigabe für ein Volume.

.Schritte
. Melden Sie sich mit einem der link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["Konsolenerfahrungen"^]an.
. Wählen Sie unter Speicher die Option *Gehe zu Lagerbestandsbestand* aus.
. Wählen Sie im Register *FSX for ONTAP* das drei-Punkt-Menü des Dateisystems mit dem zu aktualisierenden Volume aus und wählen Sie dann *Verwalten*.
. Wählen Sie in der Dateisystemübersicht die Registerkarte *Volumes* aus.
. Wählen Sie auf der Registerkarte Volumes das drei-Punkt-Menü des Volumes aus, für das Sie die SMB-Freigabe ändern möchten.
. Wählen Sie *Erweiterte Aktionen* und dann *SMB/CIFS-Freigaben verwalten*.
. Wählen Sie auf der Seite „SMB/CIFS-Freigaben verwalten“ das Drei-Punkte-Menü der SMB/CIFS-Freigabe und dann *Löschen* aus.
+
Durch das Löschen der SMB/CIFS-Freigabe ist sie für alle Benutzer, die sie mounten möchten, nicht mehr verfügbar und nicht mehr zugänglich.

. Wählen Sie im Dialogfeld „SMB/CIFS-Freigabe löschen“ *Löschen* aus, um den Löschvorgang zu bestätigen.

