---
sidebar: sidebar 
permalink: manage-volume-tags.html 
keywords: volume tags, edit volume tags, edit tags 
summary: Mit Tags können Sie Ihre Ressourcen kategorisieren. Sie können Volume-Tags für FSX für ONTAP-Volumes jederzeit hinzufügen, bearbeiten und entfernen. 
---
= Managen Sie Volume-Tags in der BlueXP  Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Mit Tags können Sie Ihre Ressourcen kategorisieren. Sie können Volume-Tags für FSX für ONTAP Volumes in der BlueXP  Workload-Fabrik jederzeit hinzufügen, bearbeiten und entfernen.

.Schritte
. Melden Sie sich mit einem der link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["Konsolenerfahrungen"^]an.
. Wählen Sie unter Speicher die Option *Gehe zu Lagerbestandsbestand* aus.
. Wählen Sie im Register *FSX for ONTAP* das drei-Punkt-Menü des Dateisystems mit dem zu aktualisierenden Volume aus und wählen Sie dann *Verwalten*.
. Wählen Sie in der Dateisystemübersicht die Registerkarte *Volumes* aus.
. Wählen Sie auf der Registerkarte Volumes das drei-Punkt-Menü für das Volume aus, für das Tags geändert werden sollen.
. Wählen Sie *Basic actions* und dann *Edit Volume Tags*.
. Fügen Sie auf der Seite Volume-Tags bearbeiten Tags hinzu, bearbeiten oder entfernen Sie Tags.
+
Die maximale Anzahl von Tags, die Sie auf ein Volume anwenden können, beträgt 50.

. Wählen Sie *Anwenden*.

