---
sidebar: sidebar 
permalink: manage-svm-tags.html 
keywords: edit storage vm tags, vm tags, svm tags 
summary: Hinzufügen, Aktualisieren oder Entfernen von Storage-VM-Tags für eine Storage-VM jederzeit. 
---
= Verwalten von Storage-VM-Tags in NetApp Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Tags können Ihnen dabei helfen, Ihre Ressourcen zu kategorisieren.  Sie können in NetApp Workload Factory jederzeit Tags für eine Storage-VM hinzufügen, bearbeiten und entfernen.

.Schritte
. Melden Sie sich mit einem der link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["Konsolenerfahrungen"^]an.
. Wählen Sie in der Kachel „Speicher“ die Option „Zum Speicher gehen“ aus.
. Wählen Sie im Speichermenü *FSx für ONTAP* aus.
. Wählen Sie unter *FSx for ONTAP* das Aktionsmenü des Dateisystems mit der zu aktualisierenden Speicher-VM und wählen Sie dann *Verwalten*.
. Wählen Sie in der Dateisystemübersicht die Registerkarte *Storage VMs* aus.
. Wählen Sie auf der Registerkarte „Storage-VMs“ das Aktionsmenü der Storage-VM aus, für die Sie Tags bearbeiten möchten.
. Wählen Sie *Storage VM Tags bearbeiten*.
. Auf der Seite Storage-VM-Tags bearbeiten können Sie Tags hinzufügen, bearbeiten oder entfernen.
+
Auf eine Storage-VM können Sie maximal 50 Tags anwenden.

. Wählen Sie *Anwenden*.

