---
sidebar: sidebar 
permalink: manage-cifs-share.html 
keywords: cifs, CIFS, cifs share, change cifs share, update cifs share, modify cifs share 
summary: Ändern Sie die CIFS-Freigabe für ein Volume in der BlueXP -Workload-Fabrik, die den SMB/CIFS-Protokolltyp verwendet. 
---
= Verwalten Sie die CIFS-Freigabe für ein Volume in der BlueXP  Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Beim Management der CIFS-Freigabe eines Volumes in der BlueXP  Workload Factory müssen die Benutzer und Gruppen ermittelt werden, denen Zugriff gewährt werden soll, sowie die Art des Zugriffs, den sie gewähren können.

.Bevor Sie beginnen
Legen Sie die Benutzer oder Gruppen fest, denen Zugriff gewährt werden soll, und legen Sie fest, welche Art von Zugriff ihnen gewährt werden soll.

.Schritte
. Melden Sie sich mit einem der link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["Konsolenerfahrungen"^]an.
. Wählen Sie unter Speicher die Option *Gehe zu Lagerbestandsbestand* aus.
. Wählen Sie im Register *FSX for ONTAP* das drei-Punkt-Menü des Dateisystems mit dem zu aktualisierenden Volume aus und wählen Sie dann *Verwalten*.
. Wählen Sie in der Dateisystemübersicht die Registerkarte *Volumes* aus.
. Wählen Sie auf der Registerkarte Volumes das drei-Punkt-Menü des Volumes aus, für das Sie die SMB-Freigabe ändern möchten.
. Wählen Sie *Erweiterte Aktionen* und dann *CIFS-Freigabe bearbeiten*.
. Geben Sie auf der Seite „CIFS-Freigabe bearbeiten“ Folgendes ein:
+
.. *Benutzer oder Gruppen*: Geben Sie gültige Benutzer und Gruppen ein. Trennen Sie jeden Eintrag durch einen Semikolon „;“.
.. *Berechtigungen*: Wählen Sie *volle Kontrolle*, *Lesen/Schreiben*, *Lesen* oder *kein Zugriff*.


. Wählen Sie *Anwenden*.

