---
sidebar: sidebar 
permalink: pause-resume-replication.html 
keywords: pause replication, quiesce replication, resume replication 
summary: Halten Sie eine Replikationsbeziehung an und setzen Sie sie wieder ein, damit das Ziel-Volume das Quell-Volume wird. 
---
= Anhalten und Fortsetzen einer Replikationsbeziehung in NetApp Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Halten Sie eine Replikationsbeziehung an, um geplante Replikationsaktualisierungen vom Quell-Volume auf das Ziel-Volume zu stoppen. Das Ziel-Volume wechselt von schreibgeschützt zu Lese-/Schreibzugriff. Beide Volumes verwenden weiterhin den letzten Replizierungs-Snapshot als neue Basis für eine spätere Neusynchronisierung.

.Über diese Aufgabe
Wenn sie angehalten wird, besteht die Replikationsbeziehung zwischen Quell- und Zielvolume weiterhin. Die Datentransfers werden angehalten, und die Volumes werden unabhängig. Um die Übertragung von Änderungen vom Quell-Volume zum Ziel-Volume wieder zu aktivieren, setzen Sie die Replikation fort.

Wenn Sie eine Replikation fortsetzen, werden alle Änderungen am Zielvolume rückgängig gemacht und NetApp Workload Factory aktiviert die Replikation erneut.  Das Zielvolume wechselt vom Lese-/Schreibzugriff zum schreibgeschützten Zugriff und empfängt im geplanten Replikationsintervall wieder Updates vom Quellvolume.  Wenn Sie eine Replikationsbeziehung wieder aufnehmen, wird das Zielvolume auf den letzten anfänglichen Replikations-Snapshot zurückgesetzt. An diesem Punkt beginnt der Volume-Replikationsprozess von vorne.

.Bevor Sie beginnen
Wenn Sie anhalten, während eine Übertragung ausgeführt wird, wird die Übertragung nicht beeinträchtigt, und die Beziehung wird „Quiescing“, bis die Übertragung abgeschlossen ist. Wenn die aktuelle Übertragung abbricht, handelt es sich jetzt um eine zukünftige Übertragung und wird nicht neu gestartet.



== Anhalten einer Replikationsbeziehung

.Schritte
. Melden Sie sich mit einem der link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["Konsolenerfahrungen"^]an.
. Wählen Sie in der Kachel „Speicher“ die Option „Zum Speicher gehen“ aus.
. Wählen Sie im Speichermenü *FSx für ONTAP* aus.
. Wählen Sie in *FSx for ONTAP* das Aktionsmenü des zu aktualisierenden Dateisystems und dann *Verwalten*.
. Wählen Sie in der Dateisystemübersicht die Registerkarte *Replikationsbeziehungen* aus.
. Wählen Sie auf der Registerkarte „Replikationsbeziehungen“ das Aktionsmenü der Replikationsbeziehung aus, die angehalten werden soll.
. Wählen Sie *Pause (Quiesce)*.
. Wählen Sie im Dialogfeld *Quiesce-Beziehung* *Quiesce* aus.


.Ergebnis
Die Beziehung hält an und ihr Status wird als „angehalten“ angezeigt.



== Nehmen Sie eine angehaltene Replikationsbeziehung wieder auf

Wenn Sie eine Replikationsbeziehung wiederaufnehmen, werden alle Änderungen am Zielvolume gelöscht, während die Replikation angehalten wurde.


NOTE: Alle Daten, die zwischen der letzten Datenreplikation und der Deaktivierung des Quell-Volumes auf das ursprüngliche Quell-Volume geschrieben wurden, bleiben nicht erhalten.

.Schritte
. Melden Sie sich mit einem der link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["Konsolenerfahrungen"^]an.
. Wählen Sie in der Kachel „Speicher“ die Option „Zum Speicher gehen“ aus.
. Wählen Sie im Speichermenü *FSx für ONTAP* aus.
. Wählen Sie in *FSx for ONTAP* das Aktionsmenü des zu aktualisierenden Dateisystems und dann *Verwalten*.
. Wählen Sie in der Dateisystemübersicht die Registerkarte *Replikationsbeziehungen* aus.
. Wählen Sie auf der Registerkarte „Replikationsbeziehungen“ das Aktionsmenü der Replikationsbeziehung aus, die Sie fortsetzen möchten.
. Wählen Sie *Fortsetzen*.
. Wählen Sie im Dialogfeld Beziehung fortsetzen die Option *Fortsetzen* aus.


.Ergebnis
Die Beziehung wird fortgesetzt und ihr Status wird als „repliziert“ angezeigt.
