---
settings:
  name: Amazon FSx for NetApp ONTAP
  internal:
    pdf_enabled: true
    termcheck_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  release_notes_autogen:
    release_notes_repo: workload-relnotes
  langs: de-de,us-en,es-es,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Amazon FSX für NetApp ONTAP Dokumentation
    url: "/index.html"
  - title: Versionshinweise
    entries:
    - title: Was ist neu
      url: "/whats-new.html"
    - title: Bekannte Einschränkungen
      url: "/known-limitations.html"
  - title: Los geht's
    entries:
    - title: Weitere Informationen zu Amazon FSX für NetApp ONTAP
      url: "/learn-fsx-ontap.html"
    - title: Schnellstart
      url: "/quick-start.html"
  - title: Verwenden Sie Amazon FSX für NetApp ONTAP
    entries:
    - title: Einsparungen entdecken
      url: "/explore-savings.html"
    - title: Speicherressourcen erstellen
      entries:
      - title: Erstellen Sie ein FSX für ONTAP-Dateisystem
        url: "/create-file-system.html"
      - title: Erstellen einer Storage-VM
        url: "/create-storage-vm.html"
      - title: Erstellen eines Volumes
        url: "/create-volume.html"
      - title: Erstellen Sie eine Initiatorgruppe
        url: "/create-igroup.html"
      - title: Erstellen Sie ein Blockgerät
        url: "/create-block-device.html"
    - title: Mehr über Links erfahren
      url: "/links-overview.html"
    - title: Ermitteln und Anzeigen von Cache-Volumes
      url: "/discover-cache-volumes.html"
    - title: Zugriff auf Ihre Daten
      url: "/access-data.html"
  - title: Sichern Sie Ihre Daten
    entries:
    - title: Datensicherung im Überblick
      url: "/data-protection-overview.html"
    - title: Snapshots bieten Schutz für Daten.
      entries:
      - title: Snapshots bieten Schutz für Daten.
        url: "/use-snapshots.html"
      - title: Verwalten von Snapshot-Richtlinien
        url: "/manage-snapshot-policy.html"
      - title: Verwalten von Snapshots
        url: "/manage-snapshots.html"
    - title: Verwenden Sie Backups im Objektspeicher
      url: "/use-backups.html"
    - title: Replikation zum Schutz von Daten verwenden
      entries:
      - title: Datenreplizierung
        url: "/create-replication.html"
      - title: Replizieren von On-Premises ONTAP Daten auf FSx für ONTAP
        url: "/use-onprem-data.html"
      - title: Replizieren einer Storage-VM in ein anderes Dateisystem
        url: "/replicate-svm-to-file-system.html"
      - title: Replikationsverzögerungen verfolgen
        url: "/track-replication-delays.html"
      - title: Replikationsbeziehungen verwalten
        url: "/manage-replication.html"
    - title: Autonomer Ransomware-Schutz für Daten
      url: "/ransomware-protection.html"
    - title: Klonen Sie ein Volume
      url: "/clone-volume.html"
    - title: Erstellen Sie einen Cyber-Tresor zum Schutz Ihrer Daten
      url: "/create-cyber-vault.html"
  - title: FSx für ONTAP in Workload Factory verwalten
    entries:
    - title: Analysiere FSx auf ONTAP EMS-Ereignisse
      url: "/analyze-events.html"
    - title: Implementieren von Best Practices für Dateisysteme
      entries:
      - title: Konfigurationsanalyse für FSX für ONTAP
        url: "/configuration-analysis.html"
      - title: Sorgfältig konzipierte Filesystem-Konfigurationen implementieren
        url: "/improve-configurations.html"
    - title: FSx hinsichtlich ONTAP Kosten verfolgen und analysieren
      url: "/track-costs.html"
    - title: Volumes verwalten
      entries:
      - title: Volumenkapazität verwalten
        url: "/manage-volume-capacity.html"
      - title: Volume-Latenzschwellenwerte festlegen
        url: "/set-volume-latency-thresholds.html"
      - title: Volume-Einstellungen verwalten
        url: "/manage-volume-settings.html"
      - title: Cache-Volumes verwalten
        url: "/manage-cache-volumes.html"
      - title: Tiering-Richtlinie ändern
        url: "/change-tiering-policy.html"
      - title: Management der NFS-Exportrichtlinien
        url: "/manage-nfs-export-policy.html"
      - title: Verwalten von SMB/CIFS-Freigaben
        url: "/manage-cifs-share.html"
      - title: S3-Zugriffspunkte verwalten
        entries:
        - title: S3-Zugriffspunkte erstellen und anhängen
          url: "/create-s3-access-points.html"
        - title: S3-Zugangspunkte bearbeiten
          url: "/edit-s3-access-points.html"
        - title: Einrichtung der Journaltabelleninfrastruktur
          url: "/setup-journal-table.html"
        - title: Details zu S3-Zugangspunkten anzeigen
          url: "/view-s3-details.html"
        - title: S3-Zugangspunkte löschen
          url: "/delete-s3-access-points.html"
      - title: Teilen Sie ein geklontes Volume auf
        url: "/split-cloned-volume.html"
      - title: Löschen Sie ein Volume
        url: "/delete-volume.html"
    - title: Blockspeicher verwalten
      entries:
      - title: Blockspeicher verwalten
        url: "/manage-block-storage.html"
      - title: Tags auf Blockgeräte anwenden
        url: "/apply-block-device-tags.html"
    - title: Dateisysteme verwalten
      entries:
      - title: Passen Sie die Dateisystemkapazität an
        url: "/adjust-file-system-capacity.html"
      - title: Dateisystemeinstellungen verwalten
        url: "/manage-file-system-settings.html"
      - title: Stellen Sie IOPS für ein Filesystem bereit
        url: "/provision-iops.html"
      - title: Löschen eines Dateisystems
        url: "/delete-file-system.html"
    - title: Storage-VMs verwalten
      entries:
      - title: Speicher-VM-Einstellungen verwalten
        url: "/manage-svm-settings.html"
      - title: Löschen einer Speicher-VM
        url: "/delete-svm.html"
    - title: Überwachen Sie den Betrieb mit Tracker
      url: "/monitor-operations.html"
  - title: Referenz
    entries:
    - title: Performance für FSX für ONTAP
      url: "/performance-reference.html"
    - title: Sicherheit für FSX für ONTAP
      url: "/security-reference.html"
  - title: Wissen und Support
    entries:
    - title: Für den Support anmelden
      url: "/support-registration.html"
    - title: Holen Sie sich Hilfe
      url: "/get-help.html"
  - title: Rechtliche Hinweise
    url: "/legal-notices.html"
product-family:
  name: NetApp Workload Factory
  repo: workload-family
