---
sidebar: sidebar 
permalink: provision-iops.html 
keywords: iops, SSD, provision, allocate 
summary: Automatische Provisionierung oder manuelle Bereitstellung von SSD-IOPS für ein FSX für ONTAP Filesystem. 
---
= Stellen Sie SSD-IOPS für ein FSX für ONTAP-Filesystem bereit
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Stellen Sie SSD-IOPS für ein FSx für ONTAP Dateisystem in NetApp Workload Factory automatisch oder manuell bereit.

.Über diese Aufgabe
Sie können die automatische SSD-IOPS-Bereitstellung für ein FSX-Dateisystem aktivieren oder IOPS manuell bereitstellen.

Die automatisch bereitgestellten IOPS werden als drei IOPS pro GiB berechnet.

Wenn Sie IOPS manuell bereitstellen, müssen Sie eventuell vorher die IOPS erhöhenlink:increase-file-system-capacity.html["Erweiterung der Dateisystemkapazität"].

Weitere Informationen zu IOPS-Limits finden Sie link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/limits.html["Kontingente"^] in der Dokumentation zu AWS FSX für NetApp ONTAP.

.Schritte
. Melden Sie sich mit einem der link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["Konsolenerfahrungen"^]an.
. Wählen Sie in der Kachel „Speicher“ die Option „Zum Speicher gehen“ aus.
. Wählen Sie im Speichermenü *FSx für ONTAP* aus.
. Wählen Sie unter *FSx for ONTAP* das Aktionsmenü des Dateisystems aus, für das IOPS bereitgestellt werden sollen, und wählen Sie dann *Verwalten*.
. Wählen Sie unter Information das Bleistiftsymbol aus, das neben dem Dropdown-Pfeil erscheint, wenn die Maus über die Zeile *IOPS Allocation* schwebt.
. Wählen Sie im Dialogfeld bereitgestellte IOPS *automatisch* oder *vom Benutzer bereitgestellt* aus.
. Wenn Sie *User provisioned* auswählen, geben Sie den gewünschten *IOPS-Wert* ein.
. Wählen Sie *Anwenden*.

