---
sidebar: sidebar 
permalink: rebalance-volume.html 
keywords: rebalance capacity, volume capacity, redistribute capacity 
summary: Überprüfen und balancieren Sie die Kapazität eines Volumes aus, um Ungleichgewichte zu vermeiden, die sich im Laufe der Zeit entwickeln. 
---
= Überprüfung und Neuausrichtung der Kapazität eines Volumes
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Prüfen Sie die Balance der FlexGroup Volume-Kapazität und gleichen Sie die Volume-Kapazität aus, um Dateien gleichmäßig auf alle Komponenten zu verteilen, damit alle Nodes am Workload eines einzelnen Flex Group Volumes teilnehmen.

.Über diese Aufgabe
Die FlexGroup-Volume-Kapazität ist in einem Scale-out-FSX für ONTAP-Filesystem mit zwei oder mehr HA-Paaren über eine Reihe von Komponenten verteilt. Jede Komponente ist ein Container, der die maximale einzelne Dateigröße vorgibt. FSX for ONTAP verteilt Dateien gleichmäßig über alle Komponenten, sodass alle Nodes am Workload eines einzelnen FlexGroup Volumes teilnehmen.

Wenn die Komponenten nicht gleichmäßig über alle Nodes verteilt werden, sinkt die Volume-Performance von FlexGroup.

Die Überprüfung des Gleichgewichts der FlexGroup Volume-Kapazität schließt die Bewertung des aktuellen Layouts der Komponenten ein. Wenn Sie die Kapazität des Volumes neu verteilen, entwickelt BlueXP  Workload Factory ein neues Komponenten-Layout mit einer geraden Anzahl an Komponenten, um die Daten gleichmäßig über alle HA-Paare zu verteilen. Der Service führt den Ausgleichsplan durch, der wiederum die Lese- und Schreibvorgänge verbessert.

Wenn sich aufgrund des Hinzufügens neuer Dateien und des Dateiwachstums Ungleichgewichte im Laufe der Zeit entwickeln, wird die Kapazität durch eine Ausbalancierung eines Volumes neu verteilt. Nachdem Sie den Neuausgleich manuell starten, wählen wir die Dateien aus und verschieben sie automatisch und unterbrechungsfrei. Volume-Transfervorgänge verbrauchen Filesystem-Ressourcen.


NOTE: Rebalancing wird nur für FlexGroup Volumes unterstützt, nicht jedoch für iSCSI- oder NVMe FlexGroup-Volumes.



== Überprüfen Sie den Ausgleich eines FlexGroup Volumes

Prüfen Sie den Ausgleich eines aktiven FlexGroup Volumes.

.Bevor Sie beginnen
* FlexGroup Volume Balance ist nur für FSX for ONTAP-Filesysteme mit einer Scale-out-Implementierung mit mindestens zwei HA-Paaren verfügbar.
* Der Volumenstil muss ein FlexGroup-Volume sein.
* Um den Saldo eines FlexGroup-Volumes zu überprüfen, müssen Sie link:manage-links.html["Verknüpfen Sie eine Verknüpfung"]. Wenn Sie noch keinen Link haben, link:create-link.html["Erstellen Sie eine Verknüpfung"]. Um einen Link im Dateisystem zu verknüpfen, wählen Sie unter *Kontoname* *Associate Link* aus. Kehren Sie nach dem Verknüpfen zu diesem Vorgang zurück.


.Schritte
. Melden Sie sich mit einem der link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["Konsolenerfahrungen"^]an.
. Wählen Sie unter *Storage* *zum Lagerbestandsverzeichnis* gehen.
. Wählen Sie auf der Registerkarte *FSX für ONTAP* das drei-Punkt-Menü des Dateisystems aus, das das Volume zum Ausgleich enthält, und wählen Sie dann *Verwalten*.
. Wählen Sie in der Dateisystemübersicht die Registerkarte *Volumes* aus.
. Wählen Sie auf der Registerkarte Volumes oben in der Tabelle *FlexGroup-Balance prüfen* aus.
. Überprüfen Sie im FlexGroup Balance-Fenster den Ausgleichstatus aller FlexGroup Volumes im FSX für ONTAP File-System.
+
Wenn ein FlexGroup-Volume unausgeglichen ist, beachten Sie <<Neuausrichtung eines FlexGroup Volumes,Neuausrichtung>>.





== Neuausrichtung eines FlexGroup Volumes

Gleichen Sie ein oder mehrere Volumes aus, die keinen Lastausgleich vornehmen. Daten werden zum Ausgleich des FlexGroup Volumes auf Mitglied-Volumes verteilt. Abhängig vom bevorzugten Datenverteilungs-Layout kann der Ausgleichsoperation FlexGroup Member Volumes hinzufügen und die Größe bereitgestellter Volumes erhöhen.


NOTE: Ein werkseitiger Workload-Administrator kann die Ausbalancierung während des Vorgangs stoppen.

.Bevor Sie beginnen
* <<Überprüfen Sie den Ausgleich eines FlexGroup Volumes,Überprüfen Sie den Ausgleich eines FlexGroup Volumes>> Vor der Ausbalancierung von Volumes.
* Um ein Volume neu auszurichten, müssen Sie link:manage-links.html["Verknüpfen Sie eine Verknüpfung"]. Wenn Sie noch keinen Link haben, link:create-link.html["Erstellen Sie eine Verknüpfung"]. Um einen Link im Dateisystem zu verknüpfen, wählen Sie unter *Kontoname* *Associate Link* aus. Kehren Sie nach dem Verknüpfen zu diesem Vorgang zurück.
* Beachten Sie, dass bestehende Snapshots auf Volumes, die Sie ausgleichen, teilweise werden und nicht zur Wiederherstellung von Volume-Daten verwendet werden können. Neue Snapshots nach der Ausbalancierung können jedoch zur Wiederherstellung von Volume-Daten verwendet werden.


.Schritte
. Melden Sie sich mit einem der link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["Konsolenerfahrungen"^]an.
. Wählen Sie unter *Storage* *zum Lagerbestandsverzeichnis* gehen.
. Wählen Sie auf der Registerkarte *FSX für ONTAP* das drei-Punkt-Menü des Dateisystems aus, das das Volume zum Ausgleich enthält, und wählen Sie dann *Verwalten*.
. Wählen Sie in der Dateisystemübersicht die Registerkarte *Volumes* aus.
. Wählen Sie auf der Registerkarte Volumes oben in der Tabelle *FlexGroup-Balance prüfen* aus.
. Wählen Sie im Fenster FlexGroup Balance *Rebalance* aus, um ein oder mehrere unausgeglichene Volumes auszugleichen.
. Wählen Sie im Assistenten für die Neuverteilung das bevorzugte Datenverteilungslayout aus.
+
** *Performance-optimiert* (empfohlen): Erhöht die Anzahl der FlexGroup Member Volumes und die bereitgestellte Größe des Volumes. Befolgt die NetApp Best Practice.
** *Restricted*: Unterstützt Volumes in einer Replikationsbeziehung. Die Anzahl der FlexGroup-Mitgliedsvolumes und die Größe der bereitgestellten Volumes bleibt gleich. Wird standardmäßig ausgewählt, wenn alle ausgewählten Volumes an einer Replikationsbeziehung teilnehmen.
** *Manuell*: Wählen Sie die gewünschte Anzahl von FlexGroup Member Volumes pro HA-Paar. Je nach Ihrer Auswahl kann sich die Anzahl der FlexGroup Member Volumes und die bereitgestellte Größe des Volumes erhöhen.


. *Drosselung*: Optional. Standardmäßig deaktiviert. Aktivieren Sie die Drosselung, um die Bandbreite einer Volume-Verschiebung auf dem Dateisystem zu begrenzen und den Datenverkehr der ausgehenden Volume-Replikation zu verlangsamen.
+
Geben Sie den Drosselungswert in MB/s. ein

. Wählen Sie eine Layoutvergleichsansicht aus und wählen Sie dann *Weiter*.
+
** Vergleich des Volume-Layouts
** FSX für ONTAP-Layout-Vergleich


. Laden Sie optional eine Liste der Volume-Verschiebungen vor dem Rebalancing herunter.
. Wählen Sie * Neuausgleich*.


.Ergebnis
Je nachdem, wie viele FlexGroup Member Volumes zu der FlexGroup hinzugefügt werden, erfolgt die Verschiebung eines einzelnen FlexGroup Volume-Mitglieds gleichzeitig. Wenn der Vorgang abgeschlossen ist, wird das Dateisystem auf den ursprünglichen Wert zurückgedrosselt.
