---
sidebar: sidebar 
permalink: replicate-svm-to-file-system.html 
keywords:  
summary: Das Replizieren einer Storage-VM in ein anderes FSX für ONTAP-Filesystem bietet bei einem Datenverlust eine schützende Schicht für den Datenzugriff. 
---
= Replizieren einer Storage-VM in ein anderes FSX für ONTAP-Dateisystem
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Das Replizieren einer Speicher-VM auf ein anderes FSx für ONTAP Dateisystem in NetApp Workload Factory bietet eine Schutzebene für den Datenzugriff im Falle eines Datenverlusts.  Dieser Vorgang repliziert alle Volumes in einer Speicher-VM auf ein anderes FSx für ONTAP Dateisystem.

.Bevor Sie beginnen
Um eine Speicher-VM auf ein anderes FSx for ONTAP-Dateisystem zu replizieren, müssen Sie einen Link zuordnen. link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["Erfahren Sie, wie Sie einen vorhandenen Link zuordnen oder einen neuen Link erstellen und zuordnen."]. Kehren Sie nach dem Verknüpfen zu diesem Vorgang zurück.

.Schritte
. Melden Sie sich mit einem der link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["Konsolenerfahrungen"^]an.
. Wählen Sie in der Kachel „Speicher“ die Option „Zum Speicher gehen“ aus.
. Wählen Sie im Speichermenü *FSx für ONTAP* aus.
. Wählen Sie unter *FSx for ONTAP* das Aktionsmenü des Dateisystems mit der zu replizierenden Speicher-VM und wählen Sie dann *Verwalten*.
. Wählen Sie in der Dateisystemübersicht unter „Speicher-VMs“ die Option „Verwalten“.
. Wählen Sie im Bildschirm „Speicher-VMs verwalten“ das Aktionsmenü der Speicher-VM aus, für die eine SVM repliziert werden soll, und wählen Sie dann *Erweiterte Aktionen* > *Speicher-VM replizieren*.
. Geben Sie auf der Seite Daten replizieren unter Replikationsziel Folgendes an:
+
.. * FSX für ONTAP Dateisystem*: Wählen Sie Anmeldeinformationen, Region und FSX für ONTAP Dateisystem Namen für das Ziel FSX für ONTAP Dateisystem.
.. *Name der Speicher-VM*: Wählen Sie die Speicher-VM aus dem Dropdown-Menü aus.
.. *Volumenname*: Der Name des Zielvolume wird automatisch im folgenden Format generiert `{OriginalVolumeName}_copy`.
.. *Tiering Policy*: Wählen Sie die Tiering Policy für die auf dem Ziel-Volume gespeicherten Daten.
+
_Auto_ ist die Standard-Tiering-Richtlinie beim Erstellen eines Volumes mithilfe der Workload Factory FSx for ONTAP -Benutzeroberfläche.  Weitere Informationen zu Volume-Tiering-Richtlinien finden Sie unterlink:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/volume-storage-capacity.html#data-tiering-policy["Speicherkapazität für Volumes"^] in der AWS FSx für NetApp ONTAP -Dokumentation.

.. *Max. Übertragungsrate*: Wählen Sie *Limited* und geben Sie die maximale Übertragungsgrenze in MB/s. ein Alternativ wählen Sie *Unlimited*.
+
Ohne Einschränkung kann die Netzwerk- und Applikations-Performance abnehmen. Alternativ empfehlen wir eine unbegrenzte Übertragungsrate für die Dateisysteme FSX for ONTAP für kritische Workloads, zum Beispiel solche, die primär für die Disaster Recovery genutzt werden.



. Geben Sie unter Replikationseinstellungen Folgendes an:
+
.. *Replikationsintervall*: Wählen Sie die Häufigkeit, mit der Snapshots vom Quell-Volume auf das Ziel-Volume übertragen werden.
.. *Langfristige Aufbewahrung*: Optional können Snapshots für die langfristige Aufbewahrung aktiviert werden.
+
Wenn Sie die langfristige Aufbewahrung aktivieren, wählen Sie eine vorhandene Richtlinie aus, oder erstellen Sie eine neue Richtlinie, um die zu replizierenden Snapshots und die Anzahl der beizubehaltenden Snapshots zu definieren.

+
... Wählen Sie für *vorhandene Richtlinie auswählen* eine vorhandene Richtlinie aus dem Dropdown-Menü aus.
... Geben Sie für *Create a New Policy* Folgendes an:
+
.... *Richtlinienname*: Geben Sie einen Richtliniennamen ein.
.... *Snapshot-Richtlinien*: Wählen Sie in der Tabelle die Snapshot-Policy-Häufigkeit und die Anzahl der zu haltenden Kopien aus. Sie können mehrere Snapshot-Richtlinien auswählen.






. Wählen Sie *Erstellen*.


.Ergebnis
Alle Volumes innerhalb der Storage-VM werden auf das Ziel-Filesystem repliziert.
