---
sidebar: sidebar 
permalink: reset-svm-password.html 
keywords: reset storage vm password, reset svm password 
summary: Setzen Sie bei Bedarf das Passwort für eine Storage-VM in der BlueXP -Workload-Fabrik zurück. 
---
= Setzt das Passwort für die Storage-VM in der BlueXP  Workload-Fabrik zurück
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Setzen Sie bei Bedarf das Passwort für eine Storage-VM in der BlueXP -Workload-Fabrik zurück.

.Schritte
. Melden Sie sich mit einem der link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["Konsolenerfahrungen"^]an.
. Wählen Sie unter Speicher die Option *Gehe zu Lagerbestandsbestand* aus.
. Wählen Sie auf der Registerkarte *FSX für ONTAP* das drei-Punkt-Menü des FSX für ONTAP-Dateisystems mit der zu aktualisierenden Speicher-VM aus und wählen Sie dann *Verwalten*.
. Wählen Sie auf der Registerkarte Übersicht des Dateisystems die Registerkarte *Storage VMs* aus.
. Wählen Sie auf der Registerkarte Storage VMs das drei-Punkt-Menü der Storage-VM aus, um das Passwort für zurückzusetzen.
. Wählen Sie *Passwort zurücksetzen*.
. Geben Sie im Dialogfeld Kennwort zurücksetzen Folgendes ein:
+
.. *Neues Passwort*: Geben Sie ein neues Passwort für die Speicher-VM ein.
.. *Passwort bestätigen*: Geben Sie das neue Passwort zur Bestätigung erneut ein.


. Wählen Sie *Anwenden*.

