---
sidebar: sidebar 
permalink: reset-svm-password.html 
keywords: reset storage vm password, reset svm password 
summary: Setzen Sie bei Bedarf das Kennwort für eine Speicher-VM in NetApp Workload Factory zurück. 
---
= Setzen Sie das Speicher-VM-Passwort in NetApp Workload Factory zurück
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Setzen Sie bei Bedarf das Kennwort für eine Speicher-VM in NetApp Workload Factory zurück.

.Schritte
. Melden Sie sich mit einem der link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["Konsolenerfahrungen"^]an.
. Wählen Sie unter „Speicher“ die Option „Zum Speicher gehen“ aus.
. Wählen Sie im Speichermenü *FSx für ONTAP* aus.
. Wählen Sie unter *FSx for ONTAP* das Aktionsmenü des FSx for ONTAP -Dateisystems mit der zu aktualisierenden Speicher-VM und wählen Sie dann *Verwalten*.
. Wählen Sie auf der Registerkarte Übersicht des Dateisystems die Registerkarte *Storage VMs* aus.
. Wählen Sie auf der Registerkarte „Storage-VMs“ das Aktionsmenü der Storage-VM aus, für die Sie das Kennwort zurücksetzen möchten.
. Wählen Sie *Passwort zurücksetzen*.
. Geben Sie im Dialogfeld Kennwort zurücksetzen Folgendes ein:
+
.. *Neues Passwort*: Geben Sie ein neues Passwort für die Speicher-VM ein.
.. *Passwort bestätigen*: Geben Sie das neue Passwort zur Bestätigung erneut ein.


. Wählen Sie *Anwenden*.

