---
sidebar: sidebar 
permalink: restore-volume-from-snapshot.html 
keywords: restore volume, snapshot 
summary: Stellen Sie ein FSX für ONTAP-Volume von einem Snapshot wieder her, wenn das Volume gelöschte oder beschädigte Dateien enthält. 
---
= Stellen Sie ein Volume aus einem Snapshot in der BlueXP -Workload-Fabrik wieder her
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
In der BlueXP  Workload Factory können Sie ein FSX für ONTAP-Volume aus einem Snapshot wiederherstellen, wenn das Volume gelöschte oder beschädigte Dateien enthält.

.Über diese Aufgabe
Mit diesem Vorgang werden Daten aus einem Snapshot auf einem neuen Volume wiederhergestellt.

.Bevor Sie beginnen
Sie können ein Volume nur aus einem Snapshot wiederherstellen, wenn Sie über eine vorhandene Snapshot-Kopie des Volumes verfügen.

Stellen Sie sicher, dass Sie über genügend Kapazität verfügen, um diesen Vorgang abzuschließen.

.Schritte
. Melden Sie sich mit einem der link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["Konsolenerfahrungen"^]an.
. Wählen Sie unter *Storage* *zum Lagerbestandsverzeichnis* gehen.
. Wählen Sie im Register *FSX for ONTAP* das drei-Punkt-Menü des Dateisystems mit dem Volume aus und wählen Sie dann *Verwalten*.
. Wählen Sie in der Dateisystemübersicht die Registerkarte *Volumes* aus.
. Wählen Sie auf der Registerkarte *Volumes* das drei-Punkt-Menü für das Volume aus, das von einem Snapshot wiederhergestellt werden soll.
. Wählen Sie *Data Protection actions*, *Snapshots* und dann *Restore Volume from a Snapshot*.
. Wählen Sie im Dialogfeld Wiederherstellungsdatenträger aus einem Snapshot im Feld *Snapshot-Name* den wiederherzustellenden Snapshot aus dem Dropdown-Menü aus.
. Geben Sie im Feld *restored Volume Name* einen eindeutigen Namen für das wiederherzustellende Volume ein.
. Wählen Sie *Wiederherstellen*.

