---
sidebar: sidebar 
permalink: restore-from-backup.html 
keywords: restore backup, new volume, volume restoration, backup 
summary: Stellen Sie ein Volume aus einem Backup in einem beliebigen FSX für ONTAP-Dateisystem in Ihrem AWS-Konto wieder her. 
---
= Stellen Sie ein Volume aus einem Backup in der BlueXP  Workload Factory wieder her
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
In der BlueXP -Workload-Fabrik können Sie ein Volume aus einem Backup auf einem beliebigen FSX für ONTAP-Dateisystem in Ihrem AWS-Konto wiederherstellen.

.Schritte
. Melden Sie sich mit einem der link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["Konsolenerfahrungen"^]an.
. Wählen Sie unter Speicher die Option *Gehe zu Lagerbestandsbestand* aus.
. Wählen Sie im Register *FSX for ONTAP* das drei-Punkt-Menü des Dateisystems mit dem Volume aus und wählen Sie dann *Verwalten*.
. Wählen Sie in der Dateisystemübersicht die Registerkarte *Volumes* aus.
. Wählen Sie auf der Registerkarte *Volumes* das drei-Punkt-Menü für das Volume aus, das von einem Backup wiederhergestellt werden soll.
. Wählen Sie *Data Protection Actions*, *FSX for ONTAP Backup* und dann *Restore from a Backup*.
. Geben Sie im Dialogfeld Wiederherstellen von einem Backup Folgendes an:
+
.. *Zieldateisystem*: Wählen Sie das Zieldateisystem aus dem Dropdown-Menü aus.
.. *Ziel-Speicher-VM*: Wählen Sie die Ziel-Speicher-VM aus dem Dropdown-Menü.
.. *Sicherungsname*: Wählen Sie den Sicherungsnamen aus dem Dropdown-Menü.
.. *Name des wiederhergestellten Volumes*: Geben Sie den Namen des wiederhergestellten Volumes ein.


. Wählen Sie *Wiederherstellen*.

