---
sidebar: sidebar 
permalink: reverse-replication.html 
keywords: reverse replication, change replication 
summary: Wenden Sie eine Replikationsbeziehung um, damit das Ziel-Volume das Quell-Volume wird. 
---
= Wenden Sie eine Replikationsbeziehung in der BlueXP  Workload Factory um
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Wenden Sie eine Replikationsbeziehung in der BlueXP  Workload Factory zurück, so dass das Ziel-Volume das Quell-Volume wird.

Rückwärtsgänge werden für folgende Vorgänge unterstützt:

* Zwei FSX für ONTAP-Dateisysteme
* Ein FSX für ONTAP-Filesystem und ein On-Premises-ONTAP-Cluster


Nachdem Sie die Replikation beendet und Änderungen am Ziel-Volume vorgenommen haben, können Sie diese Änderungen zurück auf das Quell-Volume replizieren. Dieser Prozess ist in einem Disaster-Recovery-Szenario üblich, in dem Sie eine Weile auf dem Ziel-Volume arbeiten und die Rollen der Volumes wechseln möchten.

.Über diese Aufgabe
Wenn Sie eine Replikation rückgängig machen und wieder aufnehmen, wechselt sie die Quell- und Zielrollen der Volumes, das Ziel-Volume wird das neue Quell-Volume und das Quell-Volume wird das neue Ziel-Volume. Bei der Umkehrung wird auch der Inhalt des neuen Ziel-Volume mit dem Inhalt des neuen Quell-Volume überschrieben. Wenn Sie eine Replikation zweimal umkehren, wird die ursprüngliche Replikationsrichtung neu erstellt.


NOTE: Alle Daten, die zwischen der letzten Datenreplikation und der Deaktivierung des Quell-Volumes auf das ursprüngliche Quell-Volume geschrieben wurden, bleiben nicht erhalten.

.Bevor Sie beginnen
Stellen Sie sicher, dass Sie die aktuellen und zukünftigen Rollen Ihrer Quell- und Ziel-Volumes kennen, da Änderungen am neuen Ziel-Volume mit dem neuen Quell-Volume überschrieben werden. Bei unsachgemäßer Verwendung kann es zu unbeabsichtigten Datenverlusten kommen.

.Schritte
. Melden Sie sich mit einem der link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["Konsolenerfahrungen"^]an.
. Wählen Sie unter Speicher die Option *Gehe zu Lagerbestandsbestand* aus.
. Wählen Sie auf der Registerkarte *FSX für ONTAP* das drei-Punkt-Menü des zu aktualisierenden Dateisystems aus und wählen Sie dann *Verwalten*.
. Wählen Sie in der Dateisystemübersicht die Registerkarte *Replikationsbeziehungen* aus.
. Wählen Sie auf der Registerkarte Replikationsbeziehungen das drei-Punkt-Menü der Replikationsbeziehung aus, die umgekehrt werden soll.
. Wählen Sie *Beziehung umkehren*.
. Wählen Sie im Dialogfeld Beziehung umkehren die Option *Umkehren* aus.

