---
sidebar: sidebar 
permalink: update-throughput-capacity.html 
keywords: update throughput, change throughput, throughput capacity 
summary: Aktualisieren Sie bei Bedarf die Durchsatzkapazität für ein FSX für ONTAP-Filesystem in der BlueXP -Workload-Fabrik. 
---
= Aktualisieren der Durchsatzkapazität eines Dateisystems
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Aktualisieren Sie bei Bedarf die Durchsatzkapazität für ein FSX für ONTAP-Filesystem in der BlueXP -Workload-Fabrik.

Weitere Informationen zu Durchsatzkapazitätsgrenzen finden Sie link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/limits.html["Kontingente"^] in der Dokumentation zu AWS FSX for NetApp ONTAP.

.Schritte
. Melden Sie sich mit einem der link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["Konsolenerfahrungen"^]an.
. Wählen Sie unter Speicher die Option *Gehe zu Lagerbestandsbestand* aus.
. Wählen Sie auf der Registerkarte *FSX für ONTAP* das drei-Punkt-Menü des Dateisystems aus, um die Durchsatzkapazität zu aktualisieren, und wählen Sie dann *Verwalten*.
. Wählen Sie unter Information das Bleistiftsymbol neben *Durchsatzkapazität*. Das Bleistiftsymbol wird neben dem Dropdown-Pfeil angezeigt, wenn die Maus über die Zeile *Durchsatzkapazität* schwebt.
. Wählen Sie im Dialogfeld Durchsatzkapazität die benötigte Durchsatzkapazität aus.
. Wählen Sie *Übernehmen*, um die Änderungen zu speichern.

