---
sidebar: sidebar 
permalink: update-snapshot-replication.html 
keywords: update snapshot data, replication 
summary: Aktualisieren Sie Snapshot-Daten, die in einer Replikationsbeziehung zu jedem Zeitpunkt zwischen Quell- und Ziel-Volumes übertragen werden, manuell. 
---
= Aktualisieren von Snapshot-Daten in einer Replikationsbeziehung
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Eine Replizierungsbeziehung verfügt über einen festgelegten Replizierungszeitplan. Sie können jedoch die zwischen Quell- und Ziel-Volumes in der BlueXP  Workload-Fabrik übertragenen Snapshot-Daten jederzeit manuell aktualisieren.

.Schritte
. Melden Sie sich mit einem der link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["Konsolenerfahrungen"^]an.
. Wählen Sie unter Speicher die Option *Gehe zu Lagerbestandsbestand* aus.
. Wählen Sie auf der Registerkarte *FSX für ONTAP* das drei-Punkt-Menü des zu aktualisierenden Dateisystems aus und wählen Sie dann *Verwalten*.
. Wählen Sie in der Dateisystemübersicht die Registerkarte *Replikationsbeziehungen* aus.
. Wählen Sie auf der Registerkarte Replikationsbeziehungen das drei-Punkt-Menü der zu aktualisierenden Replikationsbeziehung aus.
. Wählen Sie *Jetzt aktualisieren*.
. Wählen Sie im Dialogfeld Aktualisieren die Option *Jetzt aktualisieren*.

