---
sidebar: sidebar 
permalink: view-volume-details.html 
keywords: volume details, volume information 
summary: Zeigen Sie Volume-Details, Verteilung, Nutzung, Zugriff und Sicherung an. 
---
= Zeigen Sie Volume-Details in der BlueXP  Workload-Fabrik an
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Zeigen Sie Volume-Details, Verteilung, Nutzung, Zugriff und Sicherung an.

Volume-Details werden erst angezeigt, nachdem ein Volume in einem Dateisystem erstellt wurde.

.Schritte
. Melden Sie sich mit einem der link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["Konsolenerfahrungen"^]an.
. Wählen Sie unter Speicher die Option *Gehe zu Lagerbestandsbestand* aus.
. Wählen Sie auf der Registerkarte Volumes das drei-Punkt-Menü für das Volume aus, das Sie ändern möchten.
. Wählen Sie *Basic actions* und dann *View Volume Details*.
. Wählen Sie unter *Volume Details* die Registerkarten aus, um die folgenden Volume-Details anzuzeigen:
+
.. *Allgemeine Details*: Umfasst Volume-Name, Volume-UUID, Volume-ID, Erstellungszeit, Zustand, Volume-Typ (Lese-/Schreibzugriff/Datensicherung (RW/DP) oder schreibgeschützt), Snapshot-Richtlinienname, Hosting von Storage-VM (SVM) und Tags.
.. *Verteilung*: Umfasst Hosting-Aggregate, Volume-Stil (FlexGroup oder FlexVol), Komponenten (nur FlexGroup) und Ausgleichverhältnis (nur FlexGroup - hoch, mittel oder niedrig).
.. *Verbrauch*: Umfasst Größe, verwendete SSD, verwendeten Kapazitäts-Pool, Autogrow-Einstellung, maximale Wachstumsgröße, Einstellung der Storage-Effizienz, eingesparte Komprimierung, eingesparte Deduplizierung, Tiering-Richtlinie und Arbeitstage
.. *Access*: Umfasst Verbindungspfad, Sicherheitsstil, Exportrichtlinie und NFS-Version für NFS und Active Directory, CIFS-Freigabename, Benutzer oder Gruppen und Berechtigungen für SMB/CIFS sowie Initiatorgruppen und Host-IQNs für iSCSI.
.. *Schutz*: Beinhaltet lokalen Snapshot, Snapshot Policy Name, Remote-Replikation und FSX für ONTAP Backup.



