---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, workload factory, amazon fsx' 
summary: Informieren Sie sich über die Neuerungen bei Amazon FSX for NetApp ONTAP. 
---
= Was ist neu
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Informieren Sie sich über die Neuerungen bei Amazon FSX for NetApp ONTAP.



== 4 August 2024



=== Terraform-Unterstützung

Mit Terraform aus der Codebox können Dateisysteme und Storage-VMs implementiert und gemanagt werden.

* link:create-file-system.html["Erstellen Sie ein Dateisystem"]
* link:create-storage-vm.html["Erstellen einer Storage-VM"]
* link:https://docs.netapp.com/us-en/workload-setup-admin/use-codebox.html["Verwenden Sie Terraform aus der Codebox"^]




=== Empfehlungen zu Durchsatz und IOPS im Storage-Rechner

Der Storage-Rechner gibt Empfehlungen für die Konfiguration des Filesystems FSX für ONTAP für Durchsatz und IOPS auf Basis von AWS Best Practices ab, damit Sie optimale Hinweise für Ihre Auswahl erhalten.



== 7 Juli 2024



=== Erstversion von Workload Factory für Datenbanken

Die erste Version umfasst die Möglichkeit, mit Amazon FSX for NetApp ONTAP als Storage-Umgebung für Ihre Datenbank-Workloads die Einsparungen zu untersuchen, Microsoft SQL-Server zu erkennen, zu managen und zu implementieren, Datenbanken zu implementieren und zu klonen und diese Jobs innerhalb der Workload Factory zu überwachen.
