---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, workload factory, amazon fsx for netapp ontap, fsx for ontap' 
summary: Informieren Sie sich über die Neuerungen bei Amazon FSX for NetApp ONTAP. 
---
= Neuerungen bei Amazon FSX for NetApp ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Informieren Sie sich über die Neuerungen bei Amazon FSX for NetApp ONTAP.



== Bis 3. November 2024



=== Registerkartenansichten im Speicherbestand

Der Bestand des Speichers wurde auf eine Ansicht mit zwei Registerkarten aktualisiert:

* FSX für ONTAP Registerkarte: Zeigt die FSX für ONTAP Dateisysteme, die Sie derzeit haben.
* Registerkarte „Einsparungen“: Zeigt Elastic Block Store-, FSX für Windows File Server- und Elastic File Systems-Storage-Systeme an. Außerdem können Sie die Einsparungen für diese Systeme im Vergleich mit FSX for ONTAP untersuchen.




== 29 September 2024



=== Aktualisierung der Link-Erstellung

* Codebox Viewer: Codebox ist nun in den Prozess der Link-Erstellung integriert. Sie können die CloudFormation-Vorlage aus der Codebox in der Workload Factory anzeigen und kopieren, bevor Sie zur Ausführung des Vorgangs zu AWS umgeleitet werden.
* Erforderliche Berechtigungen: Die für die Ausführung der Link-Erstellung in AWS CloudFormation erforderlichen Berechtigungen sind nun verfügbar, um sie über den Create Link Wizard in Workload Factory anzuzeigen und zu kopieren.
* Unterstützung für manuelle Link-Erstellung: Diese Funktion ermöglicht die eigenständige Erstellung in AWS CloudFormation mit manueller Registrierung des Links ARN. Es ist nützlich, wenn ein Sicherheits- oder DevOps-Team beim Link-Erstellungsprozess hilft.


link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["Erstellen Sie eine Verknüpfung"]



== 1 September 2024



=== Lesemodus-Unterstützung für Speicherverwaltung

Der Lesemodus steht für das Speichermanagement in der Workload Factory zur Verfügung. Der Lesemodus verbessert die Erfahrung des Grundmodus durch Hinzufügen von schreibgeschützten Berechtigungen, sodass die Infrastructure-as-Code-Vorlagen mit Ihren spezifischen Variablen gefüllt werden. Die Infrastructure-as-Code-Vorlagen können direkt über Ihr AWS-Konto ausgeführt werden, ohne dass Änderungen an den Berechtigungen für die Werkseinstellungen des Workloads vorgenommen werden müssen.

link:https://docs.netapp.com/us-en/workload-setup-admin/operational-modes.html["Weitere Informationen zum Lesemodus"]



=== Unterstützung für Backup vor dem Löschen von Volumes

Sie können jetzt ein Volume sichern, bevor Sie es löschen. Die Sicherung bleibt im Dateisystem, bis sie gelöscht wird.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/delete-volume.html["Löschen Sie ein Volume"]



== 4 August 2024



=== Terraform-Unterstützung

Dateisysteme und Storage-VMs können Sie nun mit Terraform von der Codebox implementieren.

* link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-file-system.html["Erstellen Sie ein Dateisystem"]
* link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-storage-vm.html["Erstellen einer Storage-VM"]
* link:https://docs.netapp.com/us-en/workload-setup-admin/use-codebox.html["Verwenden Sie Terraform aus der Codebox"]




=== Empfehlungen zu Durchsatz und IOPS im Storage-Rechner

Der Storage-Rechner gibt Empfehlungen für die Konfiguration des Filesystems FSX für ONTAP für Durchsatz und IOPS auf Basis von AWS Best Practices ab, damit Sie optimale Hinweise für Ihre Auswahl erhalten.



== 7 Juli 2024



=== Erstversion der Workload-Fabrik für Amazon FSX für NetApp ONTAP

Amazon FSX für NetApp ONTAP ist jetzt allgemein in der BlueXP  Workload-Fabrik verfügbar.
